<div class="site"><div class="container-fluid">
<div class="row"><p id="fly-it" class="top_heading col-md-12 center">Developer Registration</p></div>
<div class="col-md-6 col-md-offset-3 dev-form clearfix">
<?php  
$form->setAttribute('action', $this->url('application/default', array('controller'=>'developer','action' => 'add')));
$form->prepare();

 echo $this->form()->openTag($form);
 echo $this->formCollection($form);
 echo $this->form()->closeTag();
?>
</div>
</div>
</div>

