

<!--[if lt IE 9]>
	<script src="http://ie7-js.googlecode.com/svn/version/2.1(beta4)/IE9.js"></script>
<![endif]-->

<style type="text/css" media="screen">

div.checkbox_onoff {
    border-radius:2px;
    display: block;
    height: 24px;
    overflow: hidden;
    width: 68px;
	cursor:pointer;
}
div.checkbox_onoff input[type="checkbox"] {
    display: none;
}
div.checkbox_onoff input[type="checkbox"] + label {
    background: url(images/on.png) no-repeat scroll -68px 0 rgba(0, 0, 0, 0);
    display: block;
    height: 24px;
    line-height: 24px;
    text-indent: -9999px;
    transition: background-position 0.3s ease-in-out 0s;
    width: 68px;
}
div.checkbox_onoff input[type="checkbox"]:checked + label {
    background-position: 0 0;
    transition: background-position 0.3s ease-in-out 0s;
}
</style>
<script>
 
function requestUrlWithAjax(url)
{
   
    var xmlhttp;
 
    //1. create the xmlhttp object
 
    if (window.XMLHttpRequest)
    {// code for IE7+, Firefox, Chrome, Opera, Safari
        xmlhttp=new XMLHttpRequest();
    }
    else
    {// code for IE6, IE5
        xmlhttp=new ActiveXObject("Microsoft.XMLHTTP");
    }
 
    //2. assign the handler for the onchange event of the object
    xmlhttp.onreadystatechange=function()
    {
        if (xmlhttp.readyState==4 && xmlhttp.status==200)
        {
            // we arrive here when we have successfully retrieved  the url we asked for
            //1. Set the response text to the text area's value
            //document.getElementById('ajaxResultTarget').value = xmlhttp.responseText;

            //2. copy the name of the file retrieved directly above the text-area
            document.getElementById('editingFilename').src = url;
            
            
             $('#textvalurl').val(url);
            //3. set the filename to the hidden input - see line 199
//          document.getElementById('frmFileName').value = url;

 
            //4. scroll the document down to editingFilename - just above the text-area
           // var xPos, yPos, tgtElem;
           // tgtElem = document.getElementById('editingFilename');
           // xPos = 0;
           // yPos = tgtElem.offsetTop;
           // window.scrollTo(xPos, yPos);
        }
    }
 
    //3. specify a GET request for the indicated filename,
    //   set asynchronous to true (dont wait for the send method to complete before continuing)
    xmlhttp.open("GET",url,true);
 
    //4. make the request
    xmlhttp.send();
}




</script>
 
<body>
<div class="site">
<div class="slide_right">
	<a href="#" class="slide_button"></a>
    <h3>Page navigation</h3>
    <a href="#" id="prev2">Prev</a> <a href="#" id="next2">Next</a>
    <ul class="slide_banner">
    <?php 
  $url = "http://localhost/zf_new/public/files/".$id."/index.php";
 ?>

  <?php 
  print_r($this->editor); 
  ?>
 


    </ul>
</div>

<div class="container clearfix">
	<h2>Hot one hundred</h2>
    <a href="#" title="Open" class="open">Open</a>
    <a href="#" title="Open2" class="open2">Open2</a>
    <div class="publish">
    	<a href="#" title="Publish settings" class="settings_button">Publish settings</a>
        <div class="publish_settings">
        	<div class="heading">
            	<h4>MAnage your campaign</h4>
                <div>
                	<img alt="" src="images/question_icon2.png" />
                    <span>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam.</span>
                </div>
            </div>
            <form method="post" name="" action="/">
                <label>Campaign saved as:</label>
                <input type="text" name="" value="Photocontest" onblur="if(this.value=='') this.value='Photocontest';" onfocus="if(this.value=='Photocontest') this.value='';" />
                <label>Campaign saved as: <a href="#" title="Down" class="down">down</a></label>
                <div class="date_time">
                    <input type="text" name="date"  class="datepicker" />
                    <input type="text" name="time" id="datetimepicker1" />
                </div>
                <input type="submit" name="submit" value="Save" />
                <input type="reset" name="reset" value="Cancel" />
                <a href="#" title="Preview" class="preview">Preview</a>
            </form>
        </div>
    </div>
    <div class="option">
    	<span>Autosave</span>
        <div class="checkbox_onoff">
            <input id="check" name="1" type="checkbox" value="1" />
            <label for="check">Check-me</label>
        </div>
        <a href="javascript:void(0)" class="save" title="Save">Save</a>
    </div>
    
    
       
	<div class="wrapper">
<iframe id="editingFilename" src="<?php echo $url;?>" style="width: 100%; height:1800%;">
</iframe>
    </div>
