<div class="mobile-social">
        <a style="cursor:pointer" class="button"></a>
        <ul class="social_icon3">
         
          <li><a style="cursor:pointer"></a> <a style="cursor:pointer"></a> <a style="cursor:pointer"></a></li>
        </ul>
        </div>
<!--//========End for mobile social icons===========-->	
       
<!--===== start menu ===-->
<div class="mobile_menu">
  <div class="logo-cont"> <a href="index.html" class="logo"></a> </div>
  <a style="cursor:pointer" class="menu-trigger navicon "><span>Open menu</span></a> </div>
<!--<aside style="left: 0px;" class="main container-fluid">
  <div class="wrapper">
        <nav id="menu"> <strong class="button"><b>&nbsp;</b></strong> <a style="cursor:pointer" class="small_logo"><img src="<?php //echo $this->basePath('newsfpimg/small_logo.png'); ?>" alt="" /></a> <a href="index.html" class="big_logo"><img src="<?php //echo $this->basePath('newsfpimg/big_logo.png'); ?>" alt="" /></a>
      <div class="download"><img src="<?php //echo $this->basePath('newsfpimg/download.png'); ?>" alt="" /></div>
      <div class="logout"> <img src="<?php //echo $this->basePath('newsfpimg/logout.png'); ?>" alt="" />
        <p><a>Studio 365</a>Amsterdam</p>
        <span>67%</span> </div>
      <span class="rate"> <img src="<?php //echo $this->basePath('newsfpimg/rate.png'); ?>" alt="" /> <img src="<?php //echo $this->basePath('newsfpimg/rate.png'); ?>" alt="" /> <img src="<?php //echo $this->basePath('newsfpimg/rate.png'); ?>" alt="" /> <img src="<?php //echo $this->basePath('newsfpimg/rate.png'); ?>" alt="" /> <img src="<?php //echo $this->basePath('newsfpimg/rate.png'); ?>" alt="" /> </span>
      <ul class="nav drop_nav" id="nav">
      
       <li><a href="index.html"><img src="<?php //echo $this->basePath('newsfpimg/icon1.png'); ?>" alt="" /><span>Home</span></a></li>
       
        <li><a href="store.html"><img src="<?php //echo $this->basePath('newsfpimg/icon2.png'); ?>" alt="" /><span>Template store</span></a></li>
        <li><a href="how-does-it-work.html"><img src="<?php //echo $this->basePath('newsfpimg/icon3.png'); ?>" alt="" /><span>How does it work?</span></a></li>
        <li><a href="become-publisher.html"><img src="<?php //echo $this->basePath('newsfpimg/icon4.png'); ?>" alt="" /><span>Connected publishers</span></a></li>
        <li><a href="case-studies.html"><img src="<?php //echo $this->basePath('newsfpimg/icon5.png'); ?>" alt="" /><span>Case Studies</span></a></li>
        <li><a href="faq.html"><img src="<?php //echo $this->basePath('newsfpimg/icon6.png'); ?>" alt="" /><span>FAQ</span></a></li>
        <li><a href="about-us.html"><img src="<?php //echo $this->basePath('newsfpimg/icon7.png'); ?>" alt="" /><span>About us</span></a></li>
        
         <li><a style="cursor:pointer"><img src="<?php //echo $this->basePath('newsfpimg/icon8.png'); ?>" alt="" /><span>Blog</span><img src="<?php //echo $this->basePath('newsfpimg/nav_arrow.png'); ?>" alt="" class="arrow" /><img src="<?php //echo $this->basePath('newsfpimg/nav_arrow2.png'); ?>" alt="" class="arrow2" /></a>
          <div> <a href="detail-information.html">Detail information</a> <a style="cursor:pointer">Template store</a> <a style="cursor:pointer">Template store</a> <a style="cursor:pointer">Template store</a> <a style="cursor:pointer">Template store</a> </div>
        </li>
        
        
        <li><a href="contact.html"><img src="<?php //echo $this->basePath('newsfpimg/icon9.png'); ?>" alt="" /><span>Contact</span></a></li>
      </ul>
      <form action="" method="post" name="search" class="search">
        <input type="text" name="search" value="" />
      </form>
      <ul class="menu">
        <li><a style="cursor:pointer">For developers</a></li>
        <li><a href="t&s.html">Terms &amp; service</a></li>
        <li><a style="cursor:pointer">Disclaimer</a></li>
        <li><a style="cursor:pointer">Privacy policy</a></li>
      </ul>
      <p class="copyright">© Copyright 2013 <a style="cursor:pointer">Smart Fanpage</a></p>
    </nav>
  </div>
</aside>-->
<aside class="mobile container-fluid">
  <nav id="menu"> <!--<strong class="button"><b>&nbsp;</b></strong>--> <a style="cursor:pointer" class="small_logo"><img src="<?php echo $this->basePath('newsfpimg/small_logo.png'); ?>" alt="" /></a> <a href="index.html" class="big_logo"><img src="<?php echo $this->basePath('newsfpimg/big_logo.png'); ?>" alt="" /></a>
    <div class="download"><img src="<?php echo $this->basePath('newsfpimg/download.png'); ?>" alt="" /></div>
    <div class="logout"> <img src="<?php echo $this->basePath('newsfpimg/logout.png'); ?>" alt="" />
      <p><a>Studio 365</a>Amsterdam</p>
      <span>67%</span> </div>
    <span class="rate"> <img src="<?php echo $this->basePath('newsfpimg/rate.png'); ?>" alt="" /> <img src="<?php echo $this->basePath('newsfpimg/rate.png'); ?>" alt="" /> <img src="<?php echo $this->basePath('newsfpimg/rate.png'); ?>" alt="" /> <img src="<?php echo $this->basePath('newsfpimg/unrate.png'); ?>" alt="" /> <img src="<?php echo $this->basePath('newsfpimg/unrate.png'); ?>" alt="" /> </span>
    <ul class="nav drop_nav" id="nav">
    
     <li><a href="index.html"><img src="<?php echo $this->basePath('newsfpimg/icon1.png'); ?>" alt="" /><span>Home</span></a></li>
      
      
      <li><a href="store.html"><img src="<?php echo $this->basePath('newsfpimg/icon2.png'); ?>" alt="" /><span>Template store</span></a></li>
      <li><a href="how-does-it-work.html"><img src="<?php echo $this->basePath('newsfpimg/icon3.png'); ?>" alt="" /><span>How does it work?</span></a></li>
      <li><a href="become-publisher.html"><img src="<?php echo $this->basePath('newsfpimg/icon4.png'); ?>" alt="" /><span>COnnected publishers</span></a></li>
      <li><a href="case-studies.html"><img src="<?php echo $this->basePath('newsfpimg/icon5.png'); ?>" alt="" /><span>Case Studies</span></a></li>
      <li><a href="faq.html"><img src="<?php echo $this->basePath('newsfpimg/icon6.png'); ?>" alt="" /><span>FAQ</span></a></li>
      <li><a href="about-us.html"><img src="<?php echo $this->basePath('newsfpimg/icon7.png'); ?>" alt="" /><span>About us</span></a></li>
      
       <li><a style="cursor:pointer"><img src="<?php echo $this->basePath('newsfpimg/icon8.png'); ?>" alt="" /><span>Blog</span><img src="<?php echo $this->basePath('newsfpimg/nav_arrow.png'); ?>" alt="" class="arrow" /><img src="<?php echo $this->basePath('newsfpimg/nav_arrow2.png'); ?>" alt="" class="arrow2" /></a>
          <div> <a href="detail-information.html">Detail information</a> <a style="cursor:pointer">Template store</a> <a style="cursor:pointer">Template store</a> <a style="cursor:pointer">Template store</a> <a style="cursor:pointer">Template store</a> </div>
        </li>
      
      
      <li><a href="contact.html"><img src="<?php echo $this->basePath('newsfpimg/icon9.png'); ?>" alt="" /><span>Contact</span></a></li>
    </ul>
    <form action="" method="post" name="search" class="search">
      <input type="text" name="search" value="" />
    </form>
    <ul class="menu">
      <li><a style="cursor:pointer">For developers</a></li>
      <li><a href="t&s.html">Terms &amp; service</a></li>
      <li><a style="cursor:pointer">Disclaimer</a></li>
      <li><a style="cursor:pointer">Privacy policy</a></li>
    </ul>
    <p class="copyright">© Copyright 2013 <a style="cursor:pointer">Smart Fanpage</a></p>
  </nav>
</aside>
<!--===== end menu ===-->
<!--===== body start ===-->
<div class="top_ffdmndhdfjkghdhdfjkghdjkhgjkdfhdfjkghdfjkh clearfix">
    	<a style="cursor:pointer" class="logo"><img src="<?php echo $this->basePath('editImg/logo.png') ?>" alt="" /></a>
        <!--<div class="icon">
        <?php
        /*
        if($view == "2")
        {
         */   
        ?>
        <script type="text/javascript">
        $( document ).ready(function() {
         $('.wrapper').removeClass('wrapper1');
         $('.wrapper').removeClass('wrapper_tab');
         $('.wrapper').addClass('wrapper_mobile');
          $('.mobile').addClass('desk-all-opa');
      $('.desktop').removeClass('desk-all-opa');
      $('.tabsme').removeClass('desk-all-opa');
         });
        </script>
         <a href="javascript:void(0)" class="mobile"><span class="icon-mobile"></span></a>
         <a href="javascript:void(0)" class=""><span class="icon-tablet"></span></a>
         <a href="javascript:void(0)" class=""><span class="icon-screen"></span></a>
           
            
        <?php
        /*}
        else if($view == "1"){
         */   
        
        ?>
        <script type="text/javascript">
        $( document ).ready(function() {
        $('.wrapper').addClass('wrapper1');
    $('.wrapper').removeClass('wrapper_tab');
     $('.wrapper').removeClass('wrapper_mobile');
      $('.mobile').removeClass('desk-all-opa');
      $('.desktop').addClass('desk-all-opa');
      $('.tabsme').removeClass('desk-all-opa');
     });
        
        </script>
             <a href="javascript:void(0)" class="mobile"><span class="icon-mobile"></span></a>
             <a href="javascript:void(0)" class="tabsme"><span class="icon-tablet"></span></a>
       	     <a href="javascript:void(0)" class="desktop"><span class="icon-screen"></span></a>
           
            <?php
           /* }
            else
            {*/
            ?>
            <a href="javascript:void(0)" class="mobile"><span class="icon-mobile"></span></a>
            <a href="javascript:void(0)" class="tabsme"><span class="icon-tablet"></span></a>
            <a href="javascript:void(0)" class="desktop"><span class="icon-screen"></span></a>
            
            
            <?php    
            //}
            ?>
        </div>--><!-- end of icon -->
       <!-- <div class="info">
        	<a href="javascript:void(0)" title="Save" class="save_btn" style="display: block;" >save</a>
            
             <div class="checkbox_onoff">
                <input id="check" name="1" type="checkbox" value="1" />
                <label for="check">Check-me</label>
            </div>end of checkbox_onoff 
            
              <div class="checkbox_onoff_jhgdugfyhfuyhdg6565656">
            <input id="check" name="0" type="checkbox" value="0" />
            <label for="check">Check-me</label>
            <input type="text" id="autochk" value=""/>
        </div>
        	<a style="cursor:pointer" title="Publish Campaign" class="campaign_btn">Publish Campaign <span class="icon-arrow-down"></span><span class="icon-arrow-up"></span></a>
          <div class="bell"><span class="icon-bell"></span><p>12</p></div>
            <div class="publish">
                <div class="heading">
                    <h2>MAnage your campaign</h2>
                    <div>
                        <span class="icon-help"></span>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam.</p>
                    </div>
                </div>
                <form method="post" name="" action="/">
                  <?php
                 
                /*  if($rowset->new_template_name == "")
                  {*/
                    
                  ?>
                    
                    <input type="text" name="" value="My Campaign" onblur="if(this.value=='') this.value='My Campaign';" onfocus="if(this.value=='My Campaign') this.value='';" id="photocontest"/>
                    <?php
                   /* }
                    else{*/
                        ?>
                          <input type="text" name="" value="<?php //echo $rowset->new_template_name; ?>" onblur="if(this.value=='') this.value='<?php //echo $rowset->new_template_name; ?>';" onfocus="if(this.value=='<?php //echo $rowset->new_template_name; ?>') this.value='';" id="photocontest"/>
                       <?php
                    //}
                    ?>
                    <label>Campaign saved as: <a style="cursor:pointer" class="down"><span class="icon-arrow-down"></span><span class="icon-arrow-up"></span></a></label>
                    <div class="date_time">
                        <input type="text" name="date"  class="datepicker" id="datepicker" />
                        <input type="text" name="time" id="datetimepicker1" />
                    </div>
                    <input type="button" name="submit" value="Save" class="save_hgdfggfdgdfgfdsygfyfdsy" />
                    <input type="reset" name="reset" value="Cancel" />
                    <a style="cursor:pointer" title="Preview" class="preview">Preview</a>
                   <?php /* $folder = $_SERVER['REQUEST_URI'];
                        $folder = explode('/',$folder);
                        $value = $folder[3];
                        
                        
                        */?>
                    <a href="javascript:void(0)" title="Publish" class="publish" >Publish</a>
                    <input type="hidden" id="ghider" value="<?php //echo $value; ?>" />
               
                </form>
                <input type="hidden" id="hidder" value="" />
                <input type="hidden" id="hiddens" value="<?php //echo $id; ?>" />
            </div>
        </div>-->
        <div class="user">
        	
            <?php
         if($result[0]['fbuser'] == "1" && $result[0]['sfpuser'] == "1")
            {
            ?>
             <span><img src="https://graph.facebook.com/<?php echo $result[0]['fbId'];?>/picture?type=small" alt="" /></span>
            <?php
            if($sfpuser == "sfpuser")
            {
            ?>
            <p style="color: white;"><?php echo $result[0]['fname']." ".$result[0]['lname']; ?></p>
            <?php  
            }
            else
            {
            ?>
            <p style="color: white;"><?php echo $result[0]['fbName']." ".$result[0]['fbLastName']; ?></p>
            <?php   
            }  
            }
            else if($result[0]['fbuser'] == "1")
            {    
            ?>
           <span><img src="https://graph.facebook.com/<?php echo $result[0]['fbId'];?>/picture?type=small" alt="" /></span>
            <p style="color: white;"><?php echo $result[0]['fbName']." ".$result[0]['fbLastName']; ?></p>
            <?php
            }
            else if($result[0]['sfpuser'] == "1")
            {
            ?>
            <span><img src="/img/no_img1.png" alt="" /></span>
            <p style="color: white;"><?php echo $result[0]['fname']." ".$result[0]['lname']; ?></p>
            <?php
            }
            
            
            ?>
            <a href="#"><span class="icon-arrow-down"></span><span class="icon-arrow-up"></span></a>
        </div><!-- end of user -->
        <div class="user_list">
        	<ul>
            	<li><a style="cursor:pointer" title="Account"><span class="icon-user"></span> Account</a></li>
            	<!--<li><a style="cursor:pointer" title="Settings"><span class="icon-cogs"></span> Settings</a></li>
                <li><hr /></li>-->
            	<li><a href="<?php echo $this->url('application/default',array('controller'=>'Frontend','action' =>'dashboard'));?>" title="Dashboard"><span class="icon-dashboard"></span> Dashboard</a></li>
            	<!--<li><a href="<?php echo $this->url('application/default',array('controller'=>'Frontend','action' =>'report'));?>" title="My Campaigns"><span class="icon-pen"></span> My Campaigns</a></li>-->
            	<!--<li><a style="cursor:pointer" title="Favourites"><span class="icon-heart"></span> Favourites</a></li>-->
            	<!--<li><a style="cursor:pointer" title="Reports"><span class="icon-stats"></span> Reports</a></li>-->
            	<li><a href="<?php echo $this->url('application/default',array('controller'=>'Frontend','action' =>'index1'));?>" title="New Campaign"><span class="icon-institution"></span> New Campaign</a></li>
            	<!--<li><a style="cursor:pointer" title="Coins"><span class="icon-gift"></span> Coins</a></li>-->
                <li><hr /></li>
            	<li><a id="logout" style="cursor: pointer;" class="lgot"  title="Log Out"><span class="icon-logout"></span> Log Out</a></li>
            </ul>
        </div><!-- end of user_list -->
    </div>
<div  class="site" style="margin: 0 auto; padding: 0; width: 80%;">
  
 <div class="container-fluid campaign-reports">
 <div class="row">
 <div class="close-reports-wrap col-lg-12">
 <h3>REPORTS</h3>
 <a style="cursor:pointer" href="<?php echo $this->url('application/default',array('controller'=>'Frontend','action' =>'dashboard'));?>" class="close-report">Close report</a>
 </div> 
 <div class="clearfix"></div>
 <hr class="mar-eaighteen">
<div class="campaign-for-client col-lg-12">
<div class="campaign-report-left">
<h4><?php print_r($tdetails->new_template_name) ; ?></h4>
</div>
<div class="campaign-report-right">
<a style="cursor: pointer;" onclick="downloadReport();" class="download-report">Download report (Excel)</a>
<!-- <div class="report-pagnination">
<ul>
	<li><a style="cursor:pointer">101 – 200 of 1,005 </a></li>
	<li><a style="cursor:pointer"><img src="img/report-icon-pag-1.png" alt=""></a></li>
	<li><a style="cursor:pointer"><img src="img/report-icon-pag-2.png" alt=""></a></li>
</ul>
</div> -->
</div>
</div>
<div class="clearfix"></div>
<div class="col-lg-12">
        
        <div id="no-more-tables" class="report">
            <table class="col-md-12 table-bordered table-striped table-condensed cf tablesorter" id="report">
        		<thead class="cf">
        			<tr>
        				
        			</tr>
        		</thead>
        		<tbody>
                    <?php 
                    $arrCount = array();
                  
                    for($i=0;$i<sizeof($formDetails);$i++)
                    {
                        $arrCount[] =  $formDetails[$i]['count'];
                    }
                        $maxSubmit = max($arrCount);
                        
                        echo "<tr>";
                        for($i=0;$i<sizeof($arrCount);$i++)
                        {
                            if($arrCount[$i] != 0)
                            {
                                if($arrCount[$i] != $arrCount[$i+1])
                                {
                                  echo '<td>'.$formDetails[$i]['form_element_values'].'</td>'."</tr><tr>";   
                                }
                                else
                                {
                                    echo '<td>'.$formDetails[$i]['form_element_values'].'</td>';
                                }
                            }
                        }
                        
                        
                        
                        
                    ?>
                      </tr>  
        		</tbody>
        	</table>
        </div>
    </div>
    
<!--<div class="report-view-rows col-md-12">
<div class="view-rows">
          <select id="standard-dropdown" name="standard-dropdown" class="custom-class1 custom-class2">
            <option value="1" class="test-class-1">View 20 rows</option>
            <option value="1" class="test-class-1">dfgsdfgsdgfd</option>
            <option value="1" class="test-class-1">Select category</option>
          </select>
        </div>
<div class="report-pagnination">
<ul>
	<li><a style="cursor:pointer">101 – 200 of 1,005 </a></li>
	<li><a style="cursor:pointer"><img src="img/report-icon-pag-1.png" alt=""></a></li>
	<li><a style="cursor:pointer"><img src="img/report-icon-pag-2.png" alt=""></a></li>
</ul>
</div>
        
    </div>-->
    
</div>
 <div style="position:relative;"><hr class="mar-eaighteen2"> <a id="back-to-top" class="go_to_up" style="cursor:pointer"></a></div>
</div> 

  <!--===== body_container end ===--> 
  </div> <!--===== main_container end ===--> 




<!-- jQuery (necessary for Bootstrap's JavaScript plugins) --> 
<!--<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>--> 
<script src="js/jquery-1.10.1.min.js"></script> 
<script type="text/javascript" src="js/jquery.prettyPhoto.js"></script>
<script src="js/bootstrap.min.js"></script> 
<!-- Include all compiled plugins (below), or include individual files as needed --> 
<script type="text/javascript" src="js/jquery.fittext.js"></script> 
<script type="text/javascript" src="js/jquery.selectBox.js"></script> 
<script type="text/javascript" src="js/owl.carousel.js"></script> 
 <script src="js/jquery.responsiveTabs.js" type="text/javascript"></script>
 <script src="js/jquery.tablesorter.js"></script>
<script type="text/javascript" src="js/jquery_004.js"></script> 
<script type="text/javascript" src="js/onload.js"></script> 

<script type="text/javascript" src="js/main.js"></script>
<script type="text/javascript" src="js/table_list.js"></script> 

        

</body>
</html>
