<aside style="left: 0px;" class="main container-fluid">
  <div class="wrapper">
        <nav id="menu"> <!--<strong class="button"><b>&nbsp;</b></strong>--> <a href="#" class="small_logo"><img src="<?php echo $this->basePath('img/small_logo.png') ?>" alt="" /></a> <a href="<?php echo $this->url('home') ?>" class="big_logo"><img src="<?php echo $this->basePath('img/big_logo.png') ?>" alt="" /></a>
      <div class="download"><img src="<?php echo $this->basePath('img/download.png') ?>" alt="" /></div>
      <div class="logout"> <img src="<?php echo $this->basePath('img/logout.png') ?>" alt="" />
        <p><a>Studio 365</a>Amsterdam</p>
        <span>67%</span> </div>
      <span class="rate"> <img src="<?php echo $this->basePath('img/rate.png') ?>" alt="" /> <img src="<?php echo $this->basePath('img/rate.png') ?>" alt="" /> <img src="<?php echo $this->basePath('img/rate.png') ?>" alt="" /> <img src="<?php echo $this->basePath('img/unrate.png') ?>" alt="" /> <img src="<?php echo $this->basePath('img/unrate.png') ?>" alt="" /> </span>
      <ul class="nav drop_nav" id="nav">
      
       <li><a href="<?php echo $this->url('home') ?>"><img src="<?php echo $this->basePath('img/icon1.png') ?>" alt="" /><span>Home</span></a></li>
       
        <li><a href="<?=$this->url('application/default', array('controller' => 'index', 'action' => 'store')); ?>"><img src="<?php echo $this->basePath('img/icon2.png') ?>" alt="" /><span>Template store</span></a></li>
        <li><a href="<?=$this->url('application/default', array('controller' => 'index', 'action' => 'howswork')); ?>"><img src="<?php echo $this->basePath('img/icon3.png') ?>" alt="" /><span>How does it work?</span></a></li>
        <li><a href="<?=$this->url('application/default', array('controller' => 'index', 'action' => 'becomepublisher')); ?>"><img src="<?php echo $this->basePath('img/icon4.png') ?>" alt="" /><span>Connected publishers</span></a></li>
        <li><a href="<?=$this->url('application/default', array('controller' => 'index', 'action' => 'casestudies')); ?>"><img src="<?php echo $this->basePath('img/icon5.png') ?>" alt="" /><span>Case Studies</span></a></li>
        <li><a href="<?=$this->url('application/default', array('controller' => 'index', 'action' => 'faq')); ?>"><img src="<?php echo $this->basePath('img/icon6.png') ?>" alt="" /><span>FAQ</span></a></li>
        <li><a href="<?=$this->url('application/default', array('controller' => 'index', 'action' => 'aboutus')); ?>"><img src="<?php echo $this->basePath('img/icon7.png') ?>" alt="" /><span>About us</span></a></li>
        
         <li><a href="#"><img src="<?php echo $this->basePath('img/icon8.png') ?>" alt="" /><span>Blog</span><img src="<?php echo $this->basePath('img/nav_arrow.png') ?>" alt="" class="arrow" /><img src="<?php echo $this->basePath('img/nav_arrow2.png') ?>" alt="" class="arrow2" /></a>
          <div> <a href="<?=$this->url('application/default', array('controller' => 'index', 'action' => 'detailinformation')); ?>">Detail information</a> <a href="#">Template store</a> <a href="#">Template store</a> <a href="#">Template store</a> <a href="#">Template store</a> </div>
        </li>
        
        
        <li><a href="<?=$this->url('application/default', array('controller' => 'index', 'action' => 'contact')); ?>"><img src="<?php echo $this->basePath('img/icon9.png') ?>" alt="" /><span>Contact</span></a></li>
      </ul>
      <form action="" method="post" name="search" class="search">
        <input type="text" name="search" value="" />
      </form>
      <ul class="menu">
        <li><a target="_blank" href="<?=$this->url('application/default', array('controller' => 'developer', 'action' => 'index')); ?>">For developers</a></li>
        <li><a href="<?=$this->url('application/default', array('controller' => 'index', 'action' => 'termscondition')); ?>">Terms &amp; service</a></li>
        <li><a href="#">Disclaimer</a></li>
        <li><a href="#">Privacy policy</a></li>
      </ul>
      <p class="copyright">© Copyright 2013 <a href="#">Smart Fanpage</a></p>
    </nav>
  </div>
</aside>