<div  class="site">
  <div class="container-fluid"> 
    <!--===== start banner ===-->
    <div class="row">
      <div class="banner how-does-bg">
        <ul class="social_icon">
          <li><a href="#">Share this website</a></li>
          <li><a href="#"></a> <a href="#"></a> <a href="#"></a></li>
        </ul>
        <div class="clearfix"></div>
        <div class="banner_caption3 col-md-8 res-text" >
          <h1>How does it work?</h1>
          
          
      </div>
      
    </div>
      
    </div><!--===== end banner ===--> 
    <div class="container-fluid" > 
      
     <section class="how-does-work-cont row">
        <div class="step-wrapper col-lg-6 col-sm-6">
        <div class="step-left-overlay">
        <div class="step-left"><span><img src="<?php echo $this->basePath('img/how-does-img1.png') ?>" alt=""></span></div>
        </div>
        <div class="step-right">
        <h3>Step 1</h3>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris sodales scelerisque eros, sed porttitor sem pellentesque quis. Ut interdum nunc nibh, sed dapibus lacus egestas sit amet. Nunc ullamcorper convallis arcu, a congue arcu ultricies ac. Etiam vitae est vitae est adipiscing dictum. Sed in magna arcu. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse ullamcorper massa et tellus tempor.</p>
        </div>
        </div>
        
        <div class="step-wrapper right-align col-lg-6 col-sm-6">
        <div class="step-left-overlay">
        <div class="step-left"><span><img src="<?php echo $this->basePath('img/how-does-img2.png') ?>" alt=""></span></div>
        </div>
        <div class="step-right">
        <h3>Step 2</h3>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris sodales scelerisque eros, sed porttitor sem pellentesque quis. Ut interdum nunc nibh, sed dapibus lacus egestas sit amet. Nunc ullamcorper convallis arcu, a congue arcu ultricies ac. Etiam vitae est vitae est adipiscing dictum. Sed in magna arcu. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse ullamcorper massa et tellus tempor.</p>
        </div>
        </div>
        
        <div class="step-wrapper col-lg-6 col-sm-6">
        <div class="step-left-overlay ">
        <div class="step-left"><span><img src="<?php echo $this->basePath('img/how-does-img3.png') ?>" alt=""></span></div>
        </div>
        <div class="step-right">
        <h3>Step 3</h3>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris sodales scelerisque eros, sed porttitor sem pellentesque quis. Ut interdum nunc nibh, sed dapibus lacus egestas sit amet. Nunc ullamcorper convallis arcu, a congue arcu ultricies ac. Etiam vitae est vitae est adipiscing dictum. Sed in magna arcu. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse ullamcorper massa et tellus tempor.</p>
        </div>
        </div>
        
        <div class="step-wrapper right-align col-lg-6 col-sm-6">
        <div class="step-left-overlay">
        <div class="step-left"><span><img src="<?php echo $this->basePath('img/how-does-img4.png') ?>" alt=""></span></div>
        </div>
        <div class="step-right">
        <h3>Step 4</h3>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris sodales scelerisque eros, sed porttitor sem pellentesque quis. Ut interdum nunc nibh, sed dapibus lacus egestas sit amet. Nunc ullamcorper convallis arcu, a congue arcu ultricies ac. Etiam vitae est vitae est adipiscing dictum. Sed in magna arcu. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse ullamcorper massa et tellus tempor.</p>
        </div>
        </div>
        </section>