<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Smartfanpage || About Us</title>
<link rel="shortcut icon" type="image/x-icon" href="/favicon.ico"/>
<!-- Bootstrap 
<link href="css/bootstrap.min.css" rel="stylesheet">
<link href="css/style.css" type="text/css" media="all" rel="stylesheet" >
<link rel="stylesheet" type="text/css" media="all" href="css/nav_menu.css">
<link href="css/owl.theme.css" type="text/css" media="all" rel="stylesheet">
<link type="text/css" rel="stylesheet" href="css/easy-responsive-tabs.css" />
<link href="css/responsive.css" type="text/css" media="all" rel="stylesheet">
<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
<style>
.home_publisher_tab {width: 100%;}
</style>
<?php
     $protocol = '';
        if (isset($_SERVER['HTTPS']) &&
       ($_SERVER['HTTPS'] == 'on'|| $_SERVER['HTTPS'] == 1) ||
        isset($_SERVER['HTTP_X_FORWARDED_PROTO']) &&
        $_SERVER['HTTP_X_FORWARDED_PROTO'] == 'https') {
         $protocol = 'https://';
        }
        else {
        $protocol = 'http://';
           }
       // echo $_SERVER['SERVER_PROTOCOL'].$_SERVER['HTTP_HOST'].$_SERVER['REQUEST_URI'];
        $url = $protocol.$_SERVER["SERVER_NAME"];
?>
</head>
<body>
<!--//========for mobile social icons===========-->
<div class="mobile-social">
	<a href="#" class="button"></a>
	<ul class="social_icon3">
		<li><a href="#"></a><a href="#"></a><a href="#"></a></li>
	</ul>
</div>
<!--//========End for mobile social icons===========-->
<!--===== start menu ===-->
<div class="mobile_menu">
	<div class="logo-cont">
		<a href="index.html" class="logo"></a>
	</div>
	<a href="#" class="menu-trigger navicon "><span>Open menu</span></a>
</div>
<!--===== end menu ===-->
<!--===== body start ===-->
<div class="site">
	<div class="container-fluid">
		<!--===== start banner ===-->
		<div class="row">
			<div class="banner documentation">
				<h1>Devlopers Section</h1>
				<span><img src="../img/documentation_bg.jpg" alt=""/></span>
			</div>
		</div>
		<div class="container-fluid">
			<section class="documentation-cont row col-lg-12">
			<h5>Hey Developers !!!</h5>
			<p>
				 It is now possible to make your facebook application in a very easiest way. Smartfanpage is helping you to reduce all hastles of facebook application building.<br/>
				Just upload your code and make your application.<br/>
				Following are the steps which will help you to upload your code.
			</p>
			<hr>
			<div class="horizontalTab">
				<ul class="resp-tabs-list home_publisher_tab">
					<li><a href="#tab-1">Step 1</a></li>
					<li><a href="#tab-2">Step 2</a></li>
					<li><a href="#tab-3">Step 3</a></li>
					<li><a href="#tab-4">Step 4</a></li>
				</ul>
				<hr>
				<div id="tab-1">
					<div class="doc_data">
						<h2>Registration and login section :</h2>
						<ul>
							<li>A. If you are a new user, register your account in Developer Registration section.<a href="<?php echo $url?>/sfpdeveloper/devregister" target="_blank">Click here</a></li>
							<li>B. If you are already registered , login your profile.<a href="<?php echo $url?>/sfpdeveloper/devlogin" target="_blank">Click here</a></li>
						</ul>
					</div>
					<p class="urg_msg">
						This is a message bar for urgent or important messages
					</p>
					<div class="doc_data">
						<h2>Title of this code field</h2>
						<ul>
							<li>"type": "subscribe", </li>
							<li>"fired_at": "2009-03-26 21:35:57",</li>
							<li>"data[id]": "8a25ff1d98", </li>
							<li>"data[list_id]": "a6b5da1054",</li>
							<li>"data[email]": "api@mailchimp.com", </li>
							<li>"data[email_type]": "html", </li>
							<li>"data[merges][EMAIL]": "api@mailchimp.com", </li>
							<li>"data[merges][FNAME]": "MailChimp", </li>
							<li>"data[merges][LNAME]": "API", </li>
							<li>"data[merges][INTERESTS]": "Group1,Group2", </li>
							<li>"data[ip_opt]": "10.20.10.30", </li>
							<li>"data[ip_signup]": "10.20.10.30"</li>
						</ul>
					</div>
					<div class="doc_data">
						<h2>Title of this code field</h2>
						<table width="100%" border="0" cellspacing="0" cellpadding="0">
						<tr>
							<td>
								Parameter
							</td>
							<td>
								<ul>
									<li>"type": "subscribe", </li>
								</ul>
							</td>
						</tr>
						<tr>
							<td>
								SQL
							</td>
							<td>
								<ul>
									<li>"data[id]": "8a25ff1d98", </li>
									<li>"data[list_id]": "a6b5da1054",</li>
									<li>"data[email]": "api@mailchimp.com", </li>
								</ul>
							</td>
						</tr>
						<tr>
							<td>
								Output
							</td>
							<td>
								<ul>
									<li>data[merges][EMAIL]": "api@mailchimp.com", </li>
									<li>"data[merges][FNAME]": "MailChimp", </li>
									<li>"data[merges][LNAME]": "API", </li>
								</ul>
							</td>
						</tr>
						<tr>
							<td>
								Connection
							</td>
							<td>
								<ul>
									<li>"data[ip_opt]": "10.20.10.30",</li>
									<li>"data[ip_signup]": "10.20.10.30"</li>
								</ul>
							</td>
						</tr>
						</table>
					</div>
					<div class="hTab2">
						<div class="horizontalTab">
							<ul class="resp-tabs-list home_publisher_tab">
								<li><a href="#tabs-1">tab 1</a></li>
								<li><a href="#tabs-2">tab 2</a></li>
								<li><a href="#tabs-3">tab 3</a></li>
							</ul>
							<div id="tabs-1">
								<div class="doc_data">
									<ul>
										<li>"type": "subscribe", </li>
										<li>"fired_at": "2009-03-26 21:35:57",</li>
										<li>"data[id]": "8a25ff1d98", </li>
										<li>"data[list_id]": "a6b5da1054",</li>
										<li>"data[email]": "api@mailchimp.com", </li>
										<li>"data[email_type]": "html", </li>
										<li>"data[merges][EMAIL]": "api@mailchimp.com", </li>
										<li>"data[merges][FNAME]": "MailChimp", </li>
										<li>"data[merges][LNAME]": "API", </li>
										<li>"data[merges][INTERESTS]": "Group1,Group2", </li>
										<li>"data[ip_opt]": "10.20.10.30", </li>
										<li>"data[ip_signup]": "10.20.10.30"</li>
									</ul>
								</div>
							</div>
							<div id="tabs-2">
								<div class="doc_data">
									<ul>
										<li>"type": "subscribe", </li>
										<li>"fired_at": "2009-03-26 21:35:57",</li>
										<li>"data[id]": "8a25ff1d98", </li>
										<li>"data[list_id]": "a6b5da1054",</li>
										<li>"data[email]": "api@mailchimp.com", </li>
										<li>"data[email_type]": "html", </li>
										<li>"data[merges][EMAIL]": "api@mailchimp.com", </li>
										<li>"data[merges][FNAME]": "MailChimp", </li>
										<li>"data[merges][LNAME]": "API", </li>
										<li>"data[merges][INTERESTS]": "Group1,Group2", </li>
										<li>"data[ip_opt]": "10.20.10.30", </li>
										<li>"data[ip_signup]": "10.20.10.30"</li>
									</ul>
								</div>
							</div>
							<div id="tabs-3">
								<div class="doc_data">
									<ul>
										<li>"type": "subscribe", </li>
										<li>"fired_at": "2009-03-26 21:35:57",</li>
										<li>"data[id]": "8a25ff1d98", </li>
										<li>"data[list_id]": "a6b5da1054",</li>
										<li>"data[email]": "api@mailchimp.com", </li>
										<li>"data[email_type]": "html", </li>
										<li>"data[merges][EMAIL]": "api@mailchimp.com", </li>
										<li>"data[merges][FNAME]": "MailChimp", </li>
										<li>"data[merges][LNAME]": "API", </li>
										<li>"data[merges][INTERESTS]": "Group1,Group2", </li>
										<li>"data[ip_opt]": "10.20.10.30", </li>
										<li>"data[ip_signup]": "10.20.10.30"</li>
									</ul>
								</div>
							</div>
						</div>
					</div>
					<div class="header2">
						<h5>Header 2</h5>
						<p>
							Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris sodales scelerisque eros, sed porttitor sem pellentesque quis. Ut interdum nunc nibh, sed dapibus lacus egestas sit amet. Nunc ullamcorper convallis arcu, a congue arcu ultricies ac. Etiam vitae est vitae est adipiscing dictum. Sed in magna arcu. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse ullamcorper massa et tellus tempor. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris sodales scelerisque eros, sed porttitor sem pellentesque quis. Ut interdum nunc nibh, sed dapibus lacus egestas sit amet. Nunc ullamcorper <a href="#">link</a> arcu, a congue arcu ultricies ac. Etiam vitae est vitae est adipiscing dictum. Sed in magna arcu. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse ullamcorper massa et tellus tempor.
						</p>
					</div>
				</div>
				<div id="tab-2">
					<div class="doc_data">
						<h2>Steps To Upload Your Template</h2>
						<ul>
							<li>1. You should provide the Campaign Name.This campaign name will be your root template folder name.</li>
							<li>2. You should provide Campaign Description.</li>
							<li>3. Please upload your ZIP template</li>
							<li>4. Please upload your ZIP template's Screenshot</li>
						</ul>
					</div>
					<p class="urg_msg">
						This is a message bar for urgent or important messages
					</p>
					<div class="doc_data">
						<h2>Title of this code field</h2>
						<ul>
							<li>"type": "subscribe", </li>
							<li>"fired_at": "2009-03-26 21:35:57",</li>
							<li>"data[id]": "8a25ff1d98", </li>
							<li>"data[list_id]": "a6b5da1054",</li>
							<li>"data[email]": "api@mailchimp.com", </li>
							<li>"data[email_type]": "html", </li>
							<li>"data[merges][EMAIL]": "api@mailchimp.com", </li>
							<li>"data[merges][FNAME]": "MailChimp", </li>
							<li>"data[merges][LNAME]": "API", </li>
							<li>"data[merges][INTERESTS]": "Group1,Group2", </li>
							<li>"data[ip_opt]": "10.20.10.30", </li>
							<li>"data[ip_signup]": "10.20.10.30"</li>
						</ul>
					</div>
					<div class="doc_data">
						<h2>Title of this code field</h2>
						<table width="100%" border="0" cellspacing="0" cellpadding="0">
						<tr>
							<td>
								Parameter
							</td>
							<td>
								<ul>
									<li>"type": "subscribe", </li>
								</ul>
							</td>
						</tr>
						<tr>
							<td>
								SQL
							</td>
							<td>
								<ul>
									<li>"data[id]": "8a25ff1d98", </li>
									<li>"data[list_id]": "a6b5da1054",</li>
									<li>"data[email]": "api@mailchimp.com", </li>
								</ul>
							</td>
						</tr>
						<tr>
							<td>
								Output
							</td>
							<td>
								<ul>
									<li>data[merges][EMAIL]": "api@mailchimp.com", </li>
									<li>"data[merges][FNAME]": "MailChimp", </li>
									<li>"data[merges][LNAME]": "API", </li>
								</ul>
							</td>
						</tr>
						<tr>
							<td>
								Connection
							</td>
							<td>
								<ul>
									<li>"data[ip_opt]": "10.20.10.30",</li>
									<li>"data[ip_signup]": "10.20.10.30"</li>
								</ul>
							</td>
						</tr>
						</table>
					</div>
					<div class="hTab2">
						<div class="horizontalTab">
							<ul class="resp-tabs-list home_publisher_tab">
								<li><a href="#tabs-1">tab 1</a></li>
								<li><a href="#tabs-2">tab 2</a></li>
								<li><a href="#tabs-3">tab 3</a></li>
							</ul>
							<div id="tabs-1">
								<div class="doc_data">
									<ul>
										<li>"type": "subscribe", </li>
										<li>"fired_at": "2009-03-26 21:35:57",</li>
										<li>"data[id]": "8a25ff1d98", </li>
										<li>"data[list_id]": "a6b5da1054",</li>
										<li>"data[email]": "api@mailchimp.com", </li>
										<li>"data[email_type]": "html", </li>
										<li>"data[merges][EMAIL]": "api@mailchimp.com", </li>
										<li>"data[merges][FNAME]": "MailChimp", </li>
										<li>"data[merges][LNAME]": "API", </li>
										<li>"data[merges][INTERESTS]": "Group1,Group2", </li>
										<li>"data[ip_opt]": "10.20.10.30", </li>
										<li>"data[ip_signup]": "10.20.10.30"</li>
									</ul>
								</div>
							</div>
							<div id="tabs-2">
								<div class="doc_data">
									<ul>
										<li>"type": "subscribe", </li>
										<li>"fired_at": "2009-03-26 21:35:57",</li>
										<li>"data[id]": "8a25ff1d98", </li>
										<li>"data[list_id]": "a6b5da1054",</li>
										<li>"data[email]": "api@mailchimp.com", </li>
										<li>"data[email_type]": "html", </li>
										<li>"data[merges][EMAIL]": "api@mailchimp.com", </li>
										<li>"data[merges][FNAME]": "MailChimp", </li>
										<li>"data[merges][LNAME]": "API", </li>
										<li>"data[merges][INTERESTS]": "Group1,Group2", </li>
										<li>"data[ip_opt]": "10.20.10.30", </li>
										<li>"data[ip_signup]": "10.20.10.30"</li>
									</ul>
								</div>
							</div>
							<div id="tabs-3">
								<div class="doc_data">
									<ul>
										<li>"type": "subscribe", </li>
										<li>"fired_at": "2009-03-26 21:35:57",</li>
										<li>"data[id]": "8a25ff1d98", </li>
										<li>"data[list_id]": "a6b5da1054",</li>
										<li>"data[email]": "api@mailchimp.com", </li>
										<li>"data[email_type]": "html", </li>
										<li>"data[merges][EMAIL]": "api@mailchimp.com", </li>
										<li>"data[merges][FNAME]": "MailChimp", </li>
										<li>"data[merges][LNAME]": "API", </li>
										<li>"data[merges][INTERESTS]": "Group1,Group2", </li>
										<li>"data[ip_opt]": "10.20.10.30", </li>
										<li>"data[ip_signup]": "10.20.10.30"</li>
									</ul>
								</div>
							</div>
						</div>
					</div>
					<div class="header2">
						<h5>Header 2</h5>
						<p>
							Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris sodales scelerisque eros, sed porttitor sem pellentesque quis. Ut interdum nunc nibh, sed dapibus lacus egestas sit amet. Nunc ullamcorper convallis arcu, a congue arcu ultricies ac. Etiam vitae est vitae est adipiscing dictum. Sed in magna arcu. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse ullamcorper massa et tellus tempor. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris sodales scelerisque eros, sed porttitor sem pellentesque quis. Ut interdum nunc nibh, sed dapibus lacus egestas sit amet. Nunc ullamcorper <a href="#">link</a> arcu, a congue arcu ultricies ac. Etiam vitae est vitae est adipiscing dictum. Sed in magna arcu. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse ullamcorper massa et tellus tempor.
						</p>
					</div>
				</div>
				<div id="tab-3">
					<div class="doc_data">
						<h2>Dashboard Section:</h2>
						<ul>
							<li>A. Click on 'Delete Template' to delete your uploaded templates</li>
							<li>B. Click on 'Upload File' to upload a new template.</li>
							<li>C. Click on 'Edit Template' to edit your template's file.</li>
							<li>C. Click on 'Promote' to market your template.</li>
						</ul>
					</div>
					<p class="urg_msg">
						This is a message bar for urgent or important messages
					</p>
					<div class="doc_data">
						<h2>Title of this code field</h2>
						<ul>
							<li>"type": "subscribe", </li>
							<li>"fired_at": "2009-03-26 21:35:57",</li>
							<li>"data[id]": "8a25ff1d98", </li>
							<li>"data[list_id]": "a6b5da1054",</li>
							<li>"data[email]": "api@mailchimp.com", </li>
							<li>"data[email_type]": "html", </li>
							<li>"data[merges][EMAIL]": "api@mailchimp.com", </li>
							<li>"data[merges][FNAME]": "MailChimp", </li>
							<li>"data[merges][LNAME]": "API", </li>
							<li>"data[merges][INTERESTS]": "Group1,Group2", </li>
							<li>"data[ip_opt]": "10.20.10.30", </li>
							<li>"data[ip_signup]": "10.20.10.30"</li>
						</ul>
					</div>
					<div class="doc_data">
						<h2>Title of this code field</h2>
						<table width="100%" border="0" cellspacing="0" cellpadding="0">
						<tr>
							<td>
								Parameter
							</td>
							<td>
								<ul>
									<li>"type": "subscribe", </li>
								</ul>
							</td>
						</tr>
						<tr>
							<td>
								SQL
							</td>
							<td>
								<ul>
									<li>"data[id]": "8a25ff1d98", </li>
									<li>"data[list_id]": "a6b5da1054",</li>
									<li>"data[email]": "api@mailchimp.com", </li>
								</ul>
							</td>
						</tr>
						<tr>
							<td>
								Output
							</td>
							<td>
								<ul>
									<li>data[merges][EMAIL]": "api@mailchimp.com", </li>
									<li>"data[merges][FNAME]": "MailChimp", </li>
									<li>"data[merges][LNAME]": "API", </li>
								</ul>
							</td>
						</tr>
						<tr>
							<td>
								Connection
							</td>
							<td>
								<ul>
									<li>"data[ip_opt]": "10.20.10.30",</li>
									<li>"data[ip_signup]": "10.20.10.30"</li>
								</ul>
							</td>
						</tr>
						</table>
					</div>
					<div class="hTab2">
						<div class="horizontalTab">
							<ul class="resp-tabs-list home_publisher_tab">
								<li><a href="#tabs-1">tab 1</a></li>
								<li><a href="#tabs-2">tab 2</a></li>
								<li><a href="#tabs-3">tab 3</a></li>
							</ul>
							<div id="tabs-1">
								<div class="doc_data">
									<ul>
										<li>"type": "subscribe", </li>
										<li>"fired_at": "2009-03-26 21:35:57",</li>
										<li>"data[id]": "8a25ff1d98", </li>
										<li>"data[list_id]": "a6b5da1054",</li>
										<li>"data[email]": "api@mailchimp.com", </li>
										<li>"data[email_type]": "html", </li>
										<li>"data[merges][EMAIL]": "api@mailchimp.com", </li>
										<li>"data[merges][FNAME]": "MailChimp", </li>
										<li>"data[merges][LNAME]": "API", </li>
										<li>"data[merges][INTERESTS]": "Group1,Group2", </li>
										<li>"data[ip_opt]": "10.20.10.30", </li>
										<li>"data[ip_signup]": "10.20.10.30"</li>
									</ul>
								</div>
							</div>
							<div id="tabs-2">
								<div class="doc_data">
									<ul>
										<li>"type": "subscribe", </li>
										<li>"fired_at": "2009-03-26 21:35:57",</li>
										<li>"data[id]": "8a25ff1d98", </li>
										<li>"data[list_id]": "a6b5da1054",</li>
										<li>"data[email]": "api@mailchimp.com", </li>
										<li>"data[email_type]": "html", </li>
										<li>"data[merges][EMAIL]": "api@mailchimp.com", </li>
										<li>"data[merges][FNAME]": "MailChimp", </li>
										<li>"data[merges][LNAME]": "API", </li>
										<li>"data[merges][INTERESTS]": "Group1,Group2", </li>
										<li>"data[ip_opt]": "10.20.10.30", </li>
										<li>"data[ip_signup]": "10.20.10.30"</li>
									</ul>
								</div>
							</div>
							<div id="tabs-3">
								<div class="doc_data">
									<ul>
										<li>"type": "subscribe", </li>
										<li>"fired_at": "2009-03-26 21:35:57",</li>
										<li>"data[id]": "8a25ff1d98", </li>
										<li>"data[list_id]": "a6b5da1054",</li>
										<li>"data[email]": "api@mailchimp.com", </li>
										<li>"data[email_type]": "html", </li>
										<li>"data[merges][EMAIL]": "api@mailchimp.com", </li>
										<li>"data[merges][FNAME]": "MailChimp", </li>
										<li>"data[merges][LNAME]": "API", </li>
										<li>"data[merges][INTERESTS]": "Group1,Group2", </li>
										<li>"data[ip_opt]": "10.20.10.30", </li>
										<li>"data[ip_signup]": "10.20.10.30"</li>
									</ul>
								</div>
							</div>
						</div>
					</div>
					<div class="header2">
						<h5>Header 2</h5>
						<p>
							Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris sodales scelerisque eros, sed porttitor sem pellentesque quis. Ut interdum nunc nibh, sed dapibus lacus egestas sit amet. Nunc ullamcorper convallis arcu, a congue arcu ultricies ac. Etiam vitae est vitae est adipiscing dictum. Sed in magna arcu. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse ullamcorper massa et tellus tempor. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris sodales scelerisque eros, sed porttitor sem pellentesque quis. Ut interdum nunc nibh, sed dapibus lacus egestas sit amet. Nunc ullamcorper <a href="#">link</a> arcu, a congue arcu ultricies ac. Etiam vitae est vitae est adipiscing dictum. Sed in magna arcu. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse ullamcorper massa et tellus tempor.
						</p>
					</div>
				</div>
				<div id="tab-4">
					<div class="doc_data">
						<h2>Template Edit Section:</h2>
						<ul>
							<li>A. Click on any file name from left side bar, and find your code in the textarea.</li>
							<li>B. Edit your file.</li>
							<li>C. Click on 'Update' to save your edited file.</li>
						</ul>
					</div>
				</div>
				<div style="position:relative;">
					<hr>
					<a id="back-to-top" class="go_to_up" href="#"></a>
				</div>
			</div>
			</section>
		</div>
	</div>
	<!--===== body_container end ===-->
</div>
<!--===== main_container end ===-->
<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<!--<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script> <script src="js/jquery-1.10.1.min.js"></script> 
<script src="js/bootstrap.min.js"></script>--->
<!-- Include all compiled plugins (below), or include individual files as needed 
<script type="text/javascript" src="js/jquery.fittext.js"></script> 
<script type="text/javascript" src="js/jquery.selectBox.js"></script> 
<script src="js/owl.carousel.js"></script>
 <script src="js/jquery.responsiveTabs.js" type="text/javascript"></script>
<script type="text/javascript" src="js/jquery_004.js"></script> 
<script type="text/javascript" src="js/onload.js"></script> 
<script type="text/javascript" src="js/main.js"></script>---->
<script type="text/javascript">
$(function(){
    $("a.js_onPageLink").bind("click", function (event) {
        event.preventDefault ? event.preventDefault() : event.returnValue = false;
        var target = $(this).attr("href");
        $("html, body").stop().animate({
                scrollLeft: $(target).offset().left,
                scrollTop: $(target).offset().top
            }, 1200);
    });
});
</script>
</body>
</html>