<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js">
<!--<![endif]-->
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<title></title>
<meta name="description" content="">
<meta name="viewport" content="width=device-width, initial-scale=1">

       <link rel="shortcut icon" type="image/x-icon" href="<?php echo $this->basePath('img/favicon.ico') ?>" />
<link href='http://fonts.googleapis.com/css?family=Economica:400,400italic,700,700italic' rel='stylesheet' type='text/css'>
</head>
<body>
<!--[if lt IE 7]>
            <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->
<div id="developer-main-container" class="clearfix">
	<div class="developer-menu-left-pannel">
		<a href="<?php echo $this->url('home') ?>" class="logo"><figure><img src="<?php echo $this->basePath('sfpdeveloper/img/dev_logo.png') ?>" alt=""></figure></a>
		<h5 class="dev-title">- Development centre - </h5>
	</div>
	<div class="copyright-menu clearfix">
		<ul>
			<li><a href="<?php echo $this->url('application/default',array('controller'=>'Index','action'=>'termsconditiondeveloper'));?>"><span class="icon-arrow-right"></span> Terms & service </a>
                </li>
                <li>
                    <a href="<?php echo $this->url('application/default',array('controller'=>'Index','action'=>'disclaimerdeveloper'));?>"> <span class="icon-arrow-right"></span> Disclaimer </a>
                </li>
                <li><a href="<?php echo $this->url('application/default',array('controller'=>'Index','action'=>'privacypolicydeveloper'));?>"><span class="icon-arrow-right"></span> Privacy policy </a>
                </li>
			<li>© Copyright 2014 Smart Fanpage</li>
		</ul>
	</div>
	<div class="developer-menu-right-pannel clearfix">
		<div class="developer-menu-right-pannel-image-holder clearfix">
			<figure><img src="<?php echo $this->basePath('sfpdeveloper/img/developers-2.jpg') ?>" alt=""></figure>
			<div class="social-share clearfix">
				<ul>
					<li>Share this website</li>
					<li><a href="#"><span class="icon-social-facebook-circular"></span></a></li>
					<li><a href="#"><span class="icon-social-twitter-circular"></span></a></li>
					<li><a href="#"><span class="icon-social-linkedin-circular"></span></a></li>
				</ul>
			</div>
		</div>
		<section class="developer-body-section clearfix">
		<div class="devs-login-content">
			<h2>GET YOUR PASSWORD</h2>
			<ul>
				<li><label for="">Username or email</label>
				<input name="" type="text" id="username"/>
				</li>
				<li>
				<p id="blank" style="color: red;text-align: right;margin: 0 33px 0 0;display: none;">
					PLEASE PUT YOUR USERNAME OR EMAIL
				</p>
				</li>
				<li>
				<p id="error" style="color: red;text-align: right;margin: 0 33px 0 0;display: none;">
					SORRY!!! WE DONT HAVE THIS RECORD
				</p>
				</li>
				<li>
				<p id="correct" style="color: green;text-align: right;margin: 0 33px 0 0;display: none;">
					CHECK YOUR MAIL TO RESET YOUR PASSWORD
				</p>
				</li>
				<li><label for="">&nbsp;</label>
				</li>
			</ul>
			<input type="button" class="continue" value="send" onclick="save()"/>
		</div>
		<div class="back-to-top-cont" style="position:relative;">
			<hr>
			<a id="back-to-top" class="go_to_up" href="#">Back to top</a>
		</div>
		</section>
	</div>
</div>
<script type="text/javascript">
        function save()
        {
        var basepath = window.location.protocol+"//" + window.location.host;    
        var username = $("#username").val();
        if (username == '')
        {
            $('#blank').show();
            $('#error').hide();
            $('#correct').hide();
            return false;
        }
        $.ajax({
            type:'POST',
            data:{user:username},
            url:basepath+"/sfpdeveloper/checkuser",
              success:function(data){       
                if(data == 1){
                    $('#correct').show();
                      $('#error').hide();
                      $('#blank').hide();
                }
                else{
                      $('#error').show();
                        $('#correct').hide();
                        $('#blank').hide();
                }
            }
        }); 
        }   
        </script>
</body>
</html>