<?php
    $protocol = '';
        if (isset($_SERVER['HTTPS']) &&
       ($_SERVER['HTTPS'] == 'on' || $_SERVER['HTTPS'] == 1) ||
        isset($_SERVER['HTTP_X_FORWARDED_PROTO']) &&
        $_SERVER['HTTP_X_FORWARDED_PROTO'] == 'https') {
         $protocol = 'https://';
        }
        else {
        $protocol = 'http://';
           }
       // echo $_SERVER['SERVER_PROTOCOL'].$_SERVER['HTTP_HOST'].$_SERVER['REQUEST_URI'];
        $url = $protocol.$_SERVER["SERVER_NAME"];
?>
<link href='http://fonts.googleapis.com/css?family=Economica:400,400italic,700,700italic' rel='stylesheet' type='text/css'/>
<style>

@font-face {
	font-family: 'icomoon';
	src:url('../fonts2/icomoon.eot?-e0hb3x');
	src:url('../fonts2/icomoon.eot?#iefix-e0hb3x') format('embedded-opentype'),
		url('../fonts2/icomoon.woff?-e0hb3x') format('woff'),
		url('../fonts2/icomoon.ttf?-e0hb3x') format('truetype'),
		url('../fonts2/icomoon.svg?-e0hb3x#icomoon') format('svg');
	font-weight: normal;
	font-style: normal;
}



.icon-cancel:before {
	content: "\e610";
}
.icon-cog:before {
	content: "\e606";
}
.icon-power-off:before {
	content: "\f011";
}
.icon-instagram:before {
	content: "\f16d";
}
.icon-info-outline:before {
	content: "\e60b";
}
.icon-social-twitter-circular:before {
	content: "\e601";
}
.icon-social-linkedin-circular:before {
	content: "\e602";
}
.icon-social-facebook-circular:before {
	content: "\e603";
}
.icon-check:before {
	content: "\f03a";
}
.icon-pencil:before {
	content: "\f058";
}
.icon-checkmark-circle:before {
	content: "\e607";
}
.icon-arrow-left:before {
	content: "\e609";
}
.icon-warning:before {
	content: "\e604";
}
.icon-arrow-down:before {
	content: "\e608";
}
.icon-arrow-right:before {
	content: "\e600";
}
.icon-arrow-up:before {
	content: "\e605";
}
.icon-dot:before {
	content: "\e60a";
}
.icon-twitter:before {
	content: "\e60c";
}
.icon-facebook:before {
	content: "\e60d";
}
.icon-pinterest:before {
	content: "\e60e";
}
.icon-linkedin:before {
	content: "\e60f";
}

h5.dev-title {
    color: #fff;
    font-family: "Economica",sans-serif;
    font-size: 22px;
    margin: 22px 0;
    text-align: center;
}

.copyright-menu {
    bottom: 19px;
    left: 12px;
    position: absolute;
}
.copyright-menu ul{ padding: 0;}
.copyright-menu li {
  display: block;
  font-family: "ubunturegular";
  font-size: 12px;
  margin-bottom: 5px;
  
}
.copyright-menu li a{ text-decoration: none;color: #fff;}
.copyright-menu li:last-child {
  color: #7c7f83;
  margin-top: 12px;
}
.main-menu li {
	height:auto;
	overflow:hidden;
	display:block;
	font-size:12px;
}
.main-menu li > a {
	height:42px;
	line-height:42px;
	border-bottom:1px solid #39404b;
	display:block;
	text-transform: uppercase;
	padding-left: 12px;
}
.main-menu li:first-child a {
	border-top:1px solid #39404b;
}
.main-menu {
	margin-top: 48px;
}
.main-menu li a:hover {
	color:#a9c5bc
}
.main-menu li a:hover:after {
	content:">";
	float:right;
	margin-right:12px;
	font-size:15px
}
.main-menu ul {
  min-width: 216px;
  padding: 0;
}
.main-menu li > a {
  color: #fff;
  }
  
  .copyright-menu li {
	display:block;
	font-size:12px;
	font-family: 'ubunturegular';
	margin-bottom:5px;
}
.copyright-menu li:last-child {
	color:#7c7f83;
	margin-top:12px
}
.copyright-menu ul li a span {
	display: block;
	float: left;
	margin: 3px 6px 0 0;
}
.copyright-menu {
	bottom: 19px;
	position: absolute;
    left: 12px;
}

.publisher-wrap h3 + span + span {
    display: block;
    margin: 12px 182px;
}
</style>
<div id="developer-main-container" class="clearfix">
<div class="developer-menu-left-pannel">

  
     <div class="developer-menu-left-pannel">
        <div class="development-center-wrapper clearfix">
        <a href="<?php echo $this->url('application/default',array('controller'=>'Index','action'=>'index'));?>" class="logo"><figure><img src="<?php echo $this->basePath('sfpdeveloper/img/dev_logo.png') ?>" alt=""></figure></a>
        <h5 class="dev-title">-  Development centre  - </h5>
         <div class="log-out-container clearfix">
        <a class="log-out-bt" href="<?php echo $url; ?>/sfpdeveloper/devlogout"><span class="icon-power-off"></span></a>
        <div class="log-out-person">
        <strong><?php echo $result->fName." ".$result->lName; ?></strong>
        <p><?php echo $result->ccity; ?></p>
        </div>
        </div>
        </div>
        
          <div class="main-menu clearfix">
        <ul>
        	<li><a href="<?php echo $this->url('application/default',array('controller'=>'sfpdeveloper','action' =>'dashboard','id'=>$result->id));?>">Dashboard </a> </li>
        	<!---<li><a href="javascript:void(0)">My campaigns</a></li>
        	<li><a href="javascript:void(0)">Upload wizard</a></li>
        	<li><a href="javascript:void(0)">My account</a></li>--->
        	<li><a  target="_blank" href="<?php echo $url; ?>/index/documentation">Documentation</a></li>
            <!---<li><a href="<?php echo $this->url('application/default',array('controller'=>'index','action' =>'blogdetails','id'=>$result->id));?>">Blog</a></li>--->
            
            <!--<li><a href="<?php //echo $this->url('application/default',array('controller'=>'developer','action' =>'createapp'));?>">Create App</a></li>--->
    
        </ul>
        </div>
        </div>
    

    </nav>
</div>
     <div class="copyright-menu clearfix">
        <ul>
        	<li><a href="<?php echo $this->url('application/default',array('controller'=>'Index','action'=>'termscondition'));?>"><span class="icon-arrow-right"></span> Terms & service </a>
                </li>
                <li>
                    <a href="<?php echo $this->url('application/default',array('controller'=>'Index','action'=>'disclaimer'));?>"> <span class="icon-arrow-right"></span> Disclaimer </a>
                </li>
                <li><a href="<?php echo $this->url('application/default',array('controller'=>'Index','action'=>'privacypolicy'));?>"><span class="icon-arrow-right"></span> Privacy policy </a>
                </li>
        	<li>&#64; Copyright 2014 Smart Fanpage</li>
        </ul>
        </div>

<div  class="developer-menu-right-pannel clearfix">
  <div class="container-fluid"> 
     <!--===== start banner ===-->
    <div class="row">
      <div class="banner_detail_info">
        <ul class="social_icon">
          <li><a href="#">Share this website</a></li>
          <li><a href="#"></a> <a href="#"></a> <a href="#"></a></li>
        </ul> <!--=== social icon ===-->
        <div class="col-md-8">
        <h3>Restaurant</h3>
        <h2>coupon give-away</h2>
        
        </div>
      </div>
      
    </div><!--===== end banner ===--> 
<div id="detail-info-cont" class="row">
   
        <div class="horizontalTab">
            <ul class="resp-tabs-list col-md-6">
                <li class="col-lg-4"><a href="#tab1">Information</a></li>
                <li class="col-lg-4"><a href="#tab2">Comments</a></li>
                 </ul>
            <section class="resp-tabs-container">
                <div class="information-wrapper" id="tab1">
                
                <div class="information-left-cont col-lg-7">
                <div class="about-this clearfix">
                <h3 class="col-lg-12">About this campaign</h3>
                <p><?php echo $promote->aboutCmp; ?></p>
                                </div>
                
                <div class="about-this clearfix">
                <h5>Campain goals</h5>
                <p><?php echo $promote->campGoal; ?></p>
                </div>
                
                <div class="about-this clearfix">
                <h5>Screenshots</h5>
                <ul class="screenshots" id="mycarousel">
                <?php
                $i=1;
                foreach($screen as $screens)
                {
                    //echo $screens->screenshot_image;
                ?>
                	<li>
                    <span class="image">
                    	<figure><a href="#"><img src="<?php echo $screens->screenshot_image; ?>" alt=""/></a></figure>
                        <div class="popup">
<a href="<?php echo $screens->screenshot_image; ?>"  rel="prettyPhoto[gallery1]" class="sreach-button"><img src="<?php echo $url;?>/img/magnifine-glass.png" alt="" /></a>
</div>
                    </span>
                    <span>
                    <p>Step <?php echo $i; ?>: <?php echo $screens->screenshot_header; ?></p>
                    <p><?php echo $screens->screenshot_desc; ?></p>
                    </span>
                    
                    </li>
                	
                <?php
                $i++;
                }
                ?>	
                	
                </ul>
                </div>
                
                <div class="about-this clearfix">
                <h5>Facebook coverphoto</h5>
                <p><?php echo $promote->fbcoverDesc; ?>.</p>
                <span>
                <figure>
                <img src="<?php echo $promote->fbcoverImage; ?>" alt="">
                </figure>
                </span>
                </div>
                
                <!--<div class="about-this clearfix">
                <h5>Responsive app</h5>
                <p>We have adjusted and incorporated Visual Composer plugin into our theme. You can easily build unlimited number of layout, because you can visualize what you will get at site page in the process of creation. Also it is very easy to rearrange and edit already created layouts.</p>
                <span>
                <figure>
                <img src="http://test.scampaigns.com/img/d-img-6.jpg" alt="">
                </figure>
                </span>
                </div>-->
                
                <!--<div class="about-this clearfix">
                <h5>Key features</h5>
                <div class="key-feature">
                <ul>
                	<li><a href="#">Feature  1</a></li>
                	<li><a href="#">Feature  2</a></li>
                	<li><a href="#">Feature  3</a></li>
                	<li><a href="#">Feature  4</a></li>
                	<li><a href="#">Feature  5</a></li>
                    </ul>
                    <ul>
                	<li><a href="#">Feature  6</a></li>
                	<li><a href="#">Feature  7</a></li>
                	<li><a href="#">Feature  8</a></li>
                	<li><a href="#">Feature  9</a></li>
                    <li><a href="#">Feature  10</a></li>
                </ul>
                
                </div>--->
                <div class="down-arrow">
                <a href=".sign-up-wrapper" class="drop-arrow-main js_onPageLink"><img src="<?php echo $url;?>/img/arrow.png" alt=""></a>
                </div>
                </div>
                
                
                
                <div class="information-right-cont col-lg-5">
                <!---<h4>Campaign costs: <strong>&#8364;19,</strong>- p/m</h4>--->
                 <h5>Use this campaign?</h5> 
                 <a href="#" class="sign-up-free">Sign up free</a> 
                  <div class="social-wrap">
                  <ul>
                  	<li>Suitable for:</li>
                  	<li><a class="active" href="#"></a></li>
                  	<li><a href="#"></a></li>
                  	
                  
                  </ul>
                  </div>
                  <div class="ratings-wrapp">
                  <ul>
                  	<li>Campaign rating:</li>
                  	<li><img src="<?php echo $url;?>/img/star-ratings.jpg" alt=""></li>
                  	<li>3.00 average based on 7 ratings</li>
                  	<li><a href="#">details</a></li>
                  </ul>
                  
                  </div>
                  <div class="other-user-campaign-info">
                  <table width="100%" border="1" cellspacing="0" cellpadding="0">
  <tr>
    <th colspan="3" scope="col">Other users who have used this campaign</th>
    </tr>
    <?php
    
    $count = count($promotion);
    $j=1;
for($i=$count;$i>0;$i--)
{
    if($promotion[$i][0]['fbemail'] != "")
    {
    if($j<=3)
    {
    ?>
    
  <tr>
    <td><?php echo $j;?>.</td>
    <td><?php echo $promotion[$i][0]['fbemail']; ?></td>
    <td>Reached 2.000.282 people</td>
  </tr>
<?php
}
$j++;
}
}
?>
</table>

                  </div>
                  <div class="purchase-n-cmmnt">
                  
                  <div class="purchases">
                  <span>
                  <figure>
                  <img src="<?php echo $url;?>/img/cart.png" alt="">
                  </figure>
                  </span>
                  <div class="pur-infos">
                  <span>Purchases</span>
                  <span>0</span>
                  </div>
                  </div>
                  
                  <div class="purchases cmmnt">
                  <span>
                  <figure>
                  <img src="<?php echo $url;?>/img/commnt.png" alt="">
                  </figure>
                  </span>
                  <div class="pur-infos">
                  <span>Comments</span>
                  <span>0</span>
                  </div>
                  </div>
                  
                  
                  
                  </div>
                  <div class="social-share">
                  <ul>
                  	<li><a href="#"><img src="<?php echo $url;?>/img/fb.jpg" alt=""></a></li>
                  	<li><a href="#"><img src="<?php echo $url;?>/img/tw.jpg" alt=""></a></li>
                  	<li><a href="#"><img src="<?php echo $url;?>/img/share.jpg" alt=""></a></li>
                  </ul>
                  </div>
                  
                  <div class="publisher-wrap">
                  
                  <h3>Publisher</h3>
                  <span><figure><img src="<?php echo $developer->cimage; ?>" alt=""></figure></span>
                  <span><?php echo $developer->fName." ".$developer->lName; ?></span>
                  <p><?php echo $developer->cdesc; ?></p>
                  <div class="rating-cont"><img src="<?php echo $url;?>/img/star.png" alt=""></div>
                 <!--- <div class="publish-bt">
                  <ul>
                  	<li><a href="#">campaigns</a></li>
                  	<li><img src="http://test.scampaigns.com/img/icon-1.png" alt=""></li>
                  </ul>
                  </div>--->
                  
                  <div class="contact-author">
                  <h3>Contact author</h3>
                  <ul>
                  	<li><?php echo $developer->cphone; ?> </li>
                  	<li>Send a request</li>
                  </ul>
                  </div>
                  
                  
                  </div>
                  
                  <!--<div class="tag-container">
                  <h3>Tags</h3>
                  <div class="tags">
			<ul class="alt">
				<li><a href="#">Lorem ipsum</a></li> 
				<li class="active"><a href="#">Dolor sit amet</a></li>
				<li><a href="#">Consectetur adipiscing elit</a></li>
				<li><a href="#">Proin </a></li>
				<li><a href="#">Sagittis libero</a></li>
				<li><a href="#">Aliquet augue</a></li>
				<li><a href="#">Quisque dui lacus</a></li>
				<li><a href="#">Consequat</a></li>
				<li><a href="#">Dictum non</a></li>
				<li><a href="#">Venenatis et tortor</a></li>
				<li><a href="#">Suspendisse mauris</a></li>
				<li><a href="#">In accumsan </a></li>
				<li><a href="#">Egestas neque</a></li>
				<li><a href="#">Mauris eget felis</a></li>
				<li><a href="#">Suspendisse</a></li>
				<li><a href="#">condimentum eleifend nulla</a></li>
			</ul>
		</div>
                  </div>--->
                    
                  </div>
                </div>
                
              <!--  ================================================== first tab end   ==================================================-->
                
                <div class="information-wrapper comment-wrapper" id="tab2">
                
                <div class="information-left-cont col-lg-7">
                <div class="about-this clearfix">
                <div class="commnt-head">
                <h3>Comments about this campaign (12)</h3>
                <span><figure><img src="<?php echo $url;?>/img/commnt-2.png" alt=""></figure><p>Leave a new comment</p></span>
                </div>
                
                
                </div>
                
                <div class="commnt-box">
                <ul>
                	<li>
                    <span>
                    <h5>weibinhuang </h5><p>12 december 2013</p>
                    </span>
                    <span>Hi, I am a beginner of using wordpress. May I know how to reduce the space between the header and post in this theme? I have set the static page as homepage. Many thanks!</span>
                    </li>
                	<li>
                    <div class="commnt-fig"><figure><img src="<?php echo $url;?>/img/cmmnt.jpg" alt=""></figure></div>
                    <div class="commnt-raw">
                    <span>
                    <h5>eaf1ef </h5><p>12 december 2013</p>
                    </span>
                    <span>Hi! Please provide link to your page (or just screenshot) and explain what space do you mean. Thanks!</span>
                    </div>
                    </li>
                </ul>
                </div>
                <div class="leave-a-reply">
                <figure><img src="<?php echo $url;?>/img/commnt-2.png" alt=""></figure><p>Leave a new comment</p>
                </div>
                <div class="commnt-box">
                <ul>
                	<li>
                    <span>
                    <h5>weibinhuang </h5><p>12 december 2013</p>
                    </span>
                    <span>Hi, I am a beginner of using wordpress. May I know how to reduce the space between the header and post in this theme? I have set the static page as homepage. Many thanks!</span>
                    </li>
                	<li>
                    <div class="commnt-fig"><figure><img src="<?php echo $url;?>/img/cmmnt.jpg" alt=""></figure></div>
                    <div class="commnt-raw">
                    <span>
                    <h5>eaf1ef </h5><p>12 december 2013</p>
                    </span>
                    <span>Hi! Please provide link to your page (or just screenshot) and explain what space do you mean. Thanks!</span>
                    </div>
                    </li>
                </ul>
                </div>
                
                <div class="form-conatainer">
                <form method="post" name="login">
                    <ul>
                        <li class="clearfix">
                            <label id="emailtab"> Name</label>
                            <input type="text" name=" Name" value="">
                        </li>
                        
                        <li class="clearfix">
                            <label id="emailtab"> Email</label>
                            <input type="text" name=" Email" value="">
                        </li>
                        
                        <li class="clearfix">
                            <label id="emailtab"> Comment</label>
                            <textarea name="comment" cols="" rows=""></textarea>
                        </li>
                        
                        <li class="clearfix">
                            <label id="emailtab"></label>
                            <input type="submit" name=" submit" value="SUBMIT COMMENT">
                        </li>
                        
                    </ul>
                </form>
                </div>
                <div class="commnt-box">
                <ul>
                	<li>
                    <span>
                    <h5>weibinhuang </h5><p>12 december 2013</p>
                    </span>
                    <span>Hi, I am a beginner of using wordpress. May I know how to reduce the space between the header and post in this theme? I have set the static page as homepage. Many thanks!</span>
                    </li>
                	<li>
                    <div class="commnt-fig"><figure><img src="<?php echo $url;?>/img/cmmnt.jpg" alt=""></figure></div>
                    <div class="commnt-raw">
                    <span>
                    <h5>eaf1ef </h5><p>12 december 2013</p>
                    </span>
                    <span>Hi! Please provide link to your page (or just screenshot) and explain what space do you mean. Thanks!</span>
                    </div>
                    </li>
                </ul>
                </div>
                <div class="leave-a-reply">
                <figure><img src="<?php echo $url;?>/img/commnt-2.png" alt=""></figure><p>Leave a new comment</p>
                </div>
                <hr>
                <a class="big-leave-comment">
                Leave a new comment
                </a>
                
                
                
                
                
                
                
                </div>
                
                <div class="information-right-cont col-lg-5">
                <!---<h4>Campaign costs: <strong>&#8364;19,</strong>- p/m</h4>--->
                 <h5>Use this campaign?</h5> 
                 <a href="#" class="sign-up-free">Sign up free</a> 
                  <div class="social-wrap">
                  <ul>
                  	<li>Suitable for:</li>
                  	<li><a class="active" href="#"></a></li>
                  	<li><a href="#"></a></li>
                  	
                  
                  </ul>
                  </div>
                  <div class="ratings-wrapp">
                  <ul>
                  	<li>Campaign rating:</li>
                  	<li><img src="<?php echo $url;?>/img/star-ratings.jpg" alt=""></li>
                  	<li>3.00 average based on 7 ratings</li>
                  	<li><a href="#">details</a></li>
                  </ul>
                  
                  </div>
                  <div class="other-user-campaign-info">
                  <table width="100%" border="1" cellspacing="0" cellpadding="0">
  <tr>
    <th colspan="3" scope="col">Other users who have used this campaign</th>
    </tr>
    <?php
    
    $count = count($promotion);
    $j=1;
for($i=$count;$i>0;$i--)
{
    if($promotion[$i][0]['fbemail'] != "")
    {
    if($j<=3)
    {
    ?>
    
  <tr>
    <td><?php echo $j;?>.</td>
    <td><?php echo $promotion[$i][0]['fbemail']; ?></td>
    <td>Reached 2.000.282 people</td>
  </tr>
<?php
}
$j++;
}
}
?>
</table>

                  </div>
                  <div class="purchase-n-cmmnt">
                  
                  <div class="purchases">
                  <span>
                  <figure>
                  <img src="<?php echo $url;?>/img/cart.png" alt="">
                  </figure>
                  </span>
                  <div class="pur-infos">
                  <span>Purchases</span>
                  <span>0</span>
                  </div>
                  </div>
                  
                  <div class="purchases cmmnt">
                  <span>
                  <figure>
                  <img src="<?php echo $url;?>/img/commnt.png" alt="">
                  </figure>
                  </span>
                  <div class="pur-infos">
                  <span>Comments</span>
                  <span>0</span>
                  </div>
                  </div>
                  
                  
                  
                  </div>
                  <div class="social-share">
                  <ul>
                  	<li><a href="#"><img src="<?php echo $url;?>/img/fb.jpg" alt=""></a></li>
                  	<li><a href="#"><img src="<?php echo $url;?>/img/tw.jpg" alt=""></a></li>
                  	<li><a href="#"><img src="<?php echo $url;?>/img/share.jpg" alt=""></a></li>
                  </ul>
                  </div>
                  
                  <div class="publisher-wrap">
                  
                  <h3>Publisher</h3>
                  <span><figure><img src="<?php echo $developer->cimage; ?>" alt=""></figure></span>
                  <span><?php echo $developer->fName." ".$developer->lName; ?></span>
                  <p><?php echo $developer->cdesc; ?></p>
                  <div class="rating-cont"><img src="<?php echo $url;?>/img/star.png" alt=""></div>
                 <!--- <div class="publish-bt">
                  <ul>
                  	<li><a href="#">campaigns</a></li>
                  	<li><img src="http://test.scampaigns.com/img/icon-1.png" alt=""></li>
                  </ul>
                  </div>--->
                  
                  <div class="contact-author">
                  <h3>Contact author</h3>
                  <ul>
                  	<li><?php echo $developer->cphone; ?> </li>
                  	<li>Send a request</li>
                  </ul>
                  </div>
                  
                  
                  </div>
                  
                  <!--<div class="tag-container">
                  <h3>Tags</h3>
                  <div class="tags">
			<ul class="alt">
				<li><a href="#">Lorem ipsum</a></li> 
				<li class="active"><a href="#">Dolor sit amet</a></li>
				<li><a href="#">Consectetur adipiscing elit</a></li>
				<li><a href="#">Proin </a></li>
				<li><a href="#">Sagittis libero</a></li>
				<li><a href="#">Aliquet augue</a></li>
				<li><a href="#">Quisque dui lacus</a></li>
				<li><a href="#">Consequat</a></li>
				<li><a href="#">Dictum non</a></li>
				<li><a href="#">Venenatis et tortor</a></li>
				<li><a href="#">Suspendisse mauris</a></li>
				<li><a href="#">In accumsan </a></li>
				<li><a href="#">Egestas neque</a></li>
				<li><a href="#">Mauris eget felis</a></li>
				<li><a href="#">Suspendisse</a></li>
				<li><a href="#">condimentum eleifend nulla</a></li>
			</ul>
		</div>
                  </div>--->
                    
                  </div>
                </div>
                
                <!--  ================================================== secoend tab end   ==================================================-->
            </section>
        </div>
        

           
      <div class="row row_text">
      <h4>Sign up now, it's free!</h4>
      <p class="sign_up_p">You can have a 14 days free trial to convince yourself and experience
the power of Smartfanpage. What are you waiting for?</p>
<a href="#" class="sign_up">Sign up free</a>
</div>

        </div>
         <div style="position:relative;">
          <hr>
          <a href="#" class="go_to_up" id="back-to-top"></a></div> <!--=== sign up section ===--> 
    </div><!--===== body_container end ===--> 
  </div>
  </div>