<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
<?php 
$form = $this->form;
$form->prepare();
?>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        
       <link rel="shortcut icon" type="image/x-icon" href="<?php echo $this->basePath('img/favicon.ico') ?>" />
		<link href='http://fonts.googleapis.com/css?family=Economica:400,400italic,700,700italic' rel='stylesheet' type='text/css'>
        
    </head>
    <body>
        <!--[if lt IE 7]>
            <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->

        <div id="developer-main-container" class="clearfix">
        <div class="developer-menu-left-pannel">
        <a href="<?php echo $this->url('home') ?>" class="logo"><figure><img src="<?php echo $this->basePath('sfpdeveloper/img/dev_logo.png') ?>" alt=""></figure></a>
        <h5 class="dev-title">-  Development centre  - </h5>
        
        
        </div>
        <div class="copyright-menu clearfix">
        <ul>
        <li><a href="<?php echo $this->url('application/default',array('controller'=>'Index','action'=>'termscondition'));?>"><span class="icon-arrow-right"></span> Terms & service </a>
                </li>
                <li>
                    <a href="<?php echo $this->url('application/default',array('controller'=>'Index','action'=>'disclaimer'));?>"> <span class="icon-arrow-right"></span> Disclaimer </a>
                </li>
                <li><a href="<?php echo $this->url('application/default',array('controller'=>'Index','action'=>'privacypolicy'));?>"><span class="icon-arrow-right"></span> Privacy policy </a>
                </li>
        	<li>© Copyright 2014 Smart Fanpage</li>
        </ul>
        </div>
        <div class="developer-menu-right-pannel clearfix">
        <div class="developer-menu-right-pannel-image-holder clearfix">
        <figure><img src="<?php echo $this->basePath('sfpdeveloper/img/developers-2.jpg') ?>" alt=""></figure>
        <div class="social-share clearfix">
        <ul>
        	<li>Share this website</li>
        	<li><a href="#"><span class="icon-social-facebook-circular"></span></a></li>
        	<li><a href="#"><span class="icon-social-twitter-circular"></span></a></li>
        	<li><a href="#"><span class="icon-social-linkedin-circular"></span></a></li>
        </ul></div>
        </div>
        
        <section class="developer-body-section clearfix">
        <div class="devs-login-content">
        <?php echo $this->form()->openTag($form);?>
        <h2>RESET YOUR PASSWORD</h2>
        <ul>
        
        	<li><label for="">New password</label>
            <?php echo $this->formElement($form->get('newpass'));?>
            </li>
            <li><label for="">Confirm password</label>
            <?php echo $this->formElement($form->get('conpass'));?>
            </li>
        	<li>
            <p id="error" style="color: red;text-align: right;margin: 0 33px 0 0;display: none;">CONFIRM PASSWORD DONT MATCH</p>
            </li>
            <li>
            <p id="passmsg" style="color: red;text-align: right;margin: 0 33px 0 0;display: none;">The size of your password  must be between 8 to 20</p>
            </li>
            <li>
            <p id="blank" style="color: red;text-align: right;margin: 0 33px 0 0;display: none;">Please set your password</p>
            </li>
            <li><label for="">&nbsp;</label>
           
            </li>
        </ul>
       <input type="button" name="button" value="SEND" class ="continue" id="passwordCheck" onClick="return submitFunction();" />
        <?php echo $this->formElement($form->get('submit'));?>
        <?php echo $this->form()->closeTag();?>
        </div>
        <input type="text" id="lengthFlag" value="<?php echo $lengthFlag;?>" style="display: none;" />
        <input type="text" id="checkFlag" value="<?php echo $checkFlag;?>" style="display: none;" />
        <input type="text" id="blank" value="<?php echo $blank;?>" style="display: none;" />        
        <div class="back-to-top-cont" style="position:relative;">
          <hr>
          <a id="back-to-top" class="go_to_up" href="#">Back to top</a></div>
          
        </section>
        
        </div>
        </div>
<script type="text/javascript">

      //  $(document).ready(function() {
//        
//        var lengthFlag = $("#lengthFlag").val();
//        var checkFlag = $("#checkFlag").val();
//        var blankcheck = $("#blank").val();
//     
//        if (checkFlag == 1)
//        {
//        $('#error').css('display','block');
//        }
//        else if (lengthFlag == 1)
//        {
//            
//        $('#passmsg').css('display','block');
//        }
//        
//         else if (blankcheck == 1)
//        {
//        $('#blank').css('display','block');
//        }
//        else{
//           
//            window.location.href="http://test.scampaigns.com/sfpdeveloper/devlogin";
//        }
//        });
/*added by Anima */ 
function submitFunction()
{
         var newPass=$("#newpass").val();
         var confirmPass=$("#conpass").val();
         if (newPass==null || confirmPass=="")
         {    
         $('#blank').css('display','block');
         $('#error').css('display','none');
         $('#passmsg').css('display','none');
         return false;
         }   
         else if (newPass!=confirmPass)
         {    
         $('#error').css('display','block');
         $('#passmsg').css('display','none');
         $('#blank').css('display','none');
         return false;
         }
         else if (newPass.length<8||newPass.length>20)
         {    
            $('#passmsg').css('display','block');
            $('#error').css('display','none');
            $('#blank').css('display','none');
            return false;
         }
        else
        {
          $('#submitbutton_check').trigger('click');
          $('#submitbutton_check').show();
          $('#passwordCheck').hide();
          
        }
}
</script>

    </body>
</html>
