<div class="site">


<div>

   <?php 
 
   foreach($templatedetails as $temp)
   {
   ?>
   <a href="<?php echo $this->url('application/default',array('controller'=>'template','action' => 'tempedit','id'=>$temp['template_name']));?>">Edit Template</a>
 
   <a href="#">
   <?php 
    echo $temp['template_name'];
    ?>
    </a>
    <?php
    echo "<br/>";
    }
   ?>
    </div>
    </div>