<!----------- added by Poulami ----------->
<div class="site">



<div class="container-fluid"> 
    <!--===== start banner ===-->
     <!--===== start banner ===-->
    <div class="row">
      <div class="banner wizard">
      	
      </div>
      
    </div><!--===== end banner ===--> <!--===== end banner ===--> 
    


<!--===================================tab html start=================================-->
<div class="wizard-cont row col-lg-12">
<div class="horizontalTab" >
  <ul class="resp-tabs-list home_publisher_tab">

 
  <li><a href="#">3) Validation</a></li>

  </ul>
  <hr>

<div id="tab-3" class="creat-acc-section">
  
 <h1 class="heading">Step 3 - Validating your pages</h1>
  <!--<p class="pro_war">In order to continue you have to fix <span>2 problems</span>.<br />--->
  <?php

  $res = explode("++",$result);
  $co = count($res)-1;
  ?>
<p class="pro_war">Even though they are not required whenever possible please fix the <span><?php echo $co; ?> warnings</span>.</p>





<div class="result_tab">
	
    <!--<table width="100%" border="0" cellspacing="0" cellpadding="0">
  <tr>
    <th>Problems (2)</th>
    <th colspan="2">&nbsp;</th>
  </tr>
  <tr>
    <td width="120">file2.php</td>
    <td>PHP error found in line 8</td>
    <td width="130"><a href="#" title="Expand details">Expand details</a></td>
  </tr>
  <tr>
    <td width="120">file1.php</td>
    <td>YouTube tag not closed</td>
    <td width="130"><a href="#" title="Expand details">Expand details</a></td>
  </tr>
</table>-->


    <table width="100%" border="0" cellspacing="0" cellpadding="0">
  <tr>
  
    <th>Warnings (<?php echo count($res)-1; ?>)</th>
    <th colspan="2">&nbsp;</th>
  </tr>
  <?php
  foreach($res as $results)
  {
    if($results !=""){
  ?>
  <tr>
    <?php echo $results; ?>
  </tr>
<?php
}
}
?>
</table>

</div>

<hr>
  
  <a href="http://test.scampaigns.com/template/setup/<?php print_r($folders); ?>" class="back_page" title="Previous step">Previous step</a>
   <a href="http://test.scampaigns.com/developer/dashboard" class="back_page" title="Previous step"><input name="submit" type="submit" value="Save &amp; continue" class="save_btn" /></a>

    
  </div>
  


</div>


<div style="position:relative;"><hr> <a id="back-to-top" class="go_to_up" href="#"></a></div>


 </div> 

  

<!--===================================tab html end=================================-->





 
    </div>