<div  class="site">
  <div class="container-fluid"> 
    <!--===== start banner ===-->
  <div class="row">  
  <div class="banner case-studies-bg">
        <ul class="social_icon2">
          <li><a href="#">Share this website</a></li>
          <li><a href="#"></a> <a href="#"></a> <a href="#"></a></li>
        </ul>
        <div class="banner_caption4 col-md-8" >
          <h1 class="">CASE STUDIES</h1>
          
           </div>
      </div>
    
    </div>
    <div class="row">
     <div class="col-lg-12 case-studies">
     
     <div class="case-studies-wrapper clearfix col-lg-6 col-sm-6">
     <span>
                <figure>
                <img alt="" src="<?php echo $this->basePath('img/case-img-1.jpg') ?>">
                </figure>
                </span>
      <span>
      <h3>Facebook campaign LFS</h3>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris sodales scelerisque eros, sed porttitor sem pellentesque quis. Ut interdum nunc nibh, sed dapibus lacus egestas sit amet. Nunc ullamcorper convallis arcu, a congue arcu ultricies ac. Etiam vitae est vitae est adipiscing dictum. Sed in magna arcu. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse ullamcorper massa et tellus tempor.</p>
      </span>          
                
     </div>
     <div class="case-studies-wrapper clearfix col-lg-6 col-sm-6">
     <span>
                <figure>
                <img alt="" src="<?php echo $this->basePath('img/case-img-2.jpg') ?>">
                </figure>
                </span>
      <span>
      <h3>Redux awareness campaign</h3>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris sodales scelerisque eros, sed porttitor sem pellentesque quis. Ut interdum nunc nibh, sed dapibus lacus egestas sit amet. Nunc ullamcorper convallis arcu, a congue arcu ultricies ac. Etiam vitae est vitae est adipiscing dictum. Sed in magna arcu. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse ullamcorper massa et tellus tempor.</p>
      </span>          
                
     </div>
     <div class="case-studies-wrapper clearfix col-lg-6 col-sm-6">
     <span>
                <figure>
                <img alt="" src="<?php echo $this->basePath('img/case-img-3.jpg') ?>">
                </figure>
                </span>
      <span>
      <h3>The Jump launches a mobile contest</h3>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris sodales scelerisque eros, sed porttitor sem pellentesque quis. Ut interdum nunc nibh, sed dapibus lacus egestas sit amet. Nunc ullamcorper convallis arcu, a congue arcu ultricies ac. Etiam vitae est vitae est adipiscing dictum. Sed in magna arcu. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse ullamcorper massa et tellus tempor.</p>
      </span>          
                
     </div>
     <div class="case-studies-wrapper clearfix col-lg-6 col-sm-6">
     <span>
                <figure>
                <img alt="" src="<?php echo $this->basePath('img/case-img-4.jpg') ?>">
                </figure>
                </span>
      <span>
      <h3>Mister de Vries Twitter app</h3>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris sodales scelerisque eros, sed porttitor sem pellentesque quis. Ut interdum nunc nibh, sed dapibus lacus egestas sit amet. Nunc ullamcorper convallis arcu, a congue arcu ultricies ac. Etiam vitae est vitae est adipiscing dictum. Sed in magna arcu. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse ullamcorper massa et tellus tempor.</p>
      </span>          
                
     </div>
     </div> 
      
    </div><!--===== end banner ===--> 