<div  class="site">
  <div class="container-fluid"> 
     <!--===== start banner ===-->
    <div class="row">
      <div class="banner_contact">
        <ul class="social_icon">
          <li><a href="#">Share this website</a></li>
          <li><a href="#"></a> <a href="#"></a> <a href="#"></a></li>
        </ul> <!--=== social icon ===-->
        <div class="cont-title">
        <h1>contact</h1>
        </div>
      </div>
      
    </div><!--===== end banner ===--> 
    
<section class="contact col-lg-12 row">
        <div class="con-left-conetnt col-lg-8">
        <h3>Submit your question</h3>
        <div class="contact-form">
       <form name="login" method="post">
                    <ul>
                        <li class="clearfix">
                            <label> Subject</label>
                            <input type="text" value="" name=" Subject" placeholder="Input text">
                        </li>
                        
                        <li class="clearfix">
                            <label> Message</label>
                            <textarea name="Message" cols="" rows="" placeholder="Input text"></textarea>
                            
                        </li>
                        
                        <li class="clearfix">
                            <label>NAME</label>
                            <input type="text" value="" name=" NAME" placeholder="Input text">
                        </li>
                        
                        <li class="clearfix">
                            <label>Phone</label>
                            <input type="text" value="" name="Phone" placeholder="Input text">
                        </li>
                        
                        <li class="clearfix">
                            <label>Email</label>
                            <input type="text" value="" name=" Phone" placeholder="Input text">
                        </li>
                        
                        <li class="clearfix">
                            <label></label>
                            <input type="submit" value="submit" name=" submit" placeholder="Input text">
                        </li>
                        
                    </ul>
                </form>

       </div>
        </div>
        
        <div class="con-right-conetnt col-lg-3">
        <h4>Contact info</h4>
        <p>Smartfanpage</p>
        <p>Liessentstraat 9a
5405 AH Uden</p>
<span>info@smartfanpage.com</span>
<span><figure><img src="<?php echo $this->basePath('img/cont-img.png') ?>" alt=""></figure></span>
<a href="#" class="find-a-pub">Find a publisher</a>
<a href="#" class="chat-closed">Chat closed</a>
        </div>
        </section>
        <div class="row_margin col-lg-12">
        <hr>
      </div>        