<div  class="site" id="menu">
  <div class="container-fluid"> 
     <!--===== start banner ===-->
    <div class="row">
      <div class="banner_detail_info">
        <ul class="social_icon">
          <li><a href="#">Share this website</a></li>
          <li><a href="#"></a> <a href="#"></a> <a href="#"></a></li>
        </ul> <!--=== social icon ===-->
        <div class="col-md-8">
        <h3>Restaurant</h3>
        <h2>coupon give-away</h2>
        
        </div>
      </div>
      
    </div><!--===== end banner ===--> 
<div id="detail-info-cont" class="row">
   
        <div id="horizontalTab">
            <ul class="resp-tabs-list col-md-6">
                <li class="col-lg-4"><a href="#tab1">Information</a></li>
                <li class="col-lg-4"><a href="#tab2">Comments</a></li>
                 </ul>
            <section class="resp-tabs-container">
                <div class="information-wrapper" id="tab1">
                
                <div class="information-left-cont col-lg-7">
                <div class="about-this clearfix">
                <h3 class="col-lg-12">About this campaign</h3>
                <p>Impreza is modern professional and flexible fully responsive retina-ready WordPress theme, developed with great attention to details. Theme can be used for any type of website: business, corporate, portfolio, products, marketing, etc.</p>

<p>You can modify layout, styling, colors directly from within the backend. Build your own style or use one of 10 predefined color styles right out from your WordPress Admin Panel. In addition to the global options you can set unqiue styling options for each entry as seen in the theme demo.</p>

<p>Impreza theme provides responsive and flexible design. All page layouts works perfectly on all devices, from large monitors to mobile phones. All elements enhanced for Retina displays, so they look clean and sharp on modern gadgets.</p>
                </div>
                
                <div class="about-this clearfix">
                <h5>Campain goals</h5>
                <p>We have adjusted and incorporated Visual Composer plugin into our theme. You can easily build unlimited number of layout, because you can visualize what you will get at site page in the process of creation. Also it is very easy to rearrange and edit already created layouts.</p>
                </div>
                
                <div class="about-this clearfix">
                <h5>Screenshots</h5>
                <ul class="screenshots" id="mycarousel">
                	<li>
                    <span class="image">
                    	<figure><a href="#"><img src="<?php echo $this->basePath('img/d-img-1.jpg') ?>" alt=""></a></figure>
                        <div class="popup">
<a href="img/d-img-1_big.png"  rel="prettyPhoto[gallery1]" class="sreach-button"><img src="<?php echo $this->basePath('img/magnifine-glass.png') ?>" alt="" /></a>
</div>
                    </span>
                    <span>
                    <p>Step 1: Like gate</p>
                    <p>We have adjusted and incorporated Visual Composer plugin into our theme. You can easily build unlimited number of layout, because you can visualize what you will get at site page in the process of creation. Also it is very easy to rearrange and edit already created layouts.</p>
                    </span>
                    
                    </li>
                	<li>
                    <span  class="image">
                    	<figure><a href="#"><img src="<?php echo $this->basePath('img/d-img-2.jpg') ?>" alt=""></a></figure>
                        <div class="popup">
<a href="img/d-img-1_big.png"  rel="prettyPhoto[gallery1]" class="sreach-button"><img src="<?php echo $this->basePath('img/magnifine-glass.png') ?>" alt="" /></a>
</div>
                    </span>
                    <span>
                    <p>Step 2: Photo upload</p>
                    <p>We have adjusted and incorporated Visual Composer plugin into our theme. You can easily build unlimited number of layout, because you can visualize what you will get at site page in the process of creation. </p>
                    </span>
                    
                    </li>
                	<li>
                    <span class="image">
                    	<figure><a href="#"><img src="<?php echo $this->basePath('img/d-img-3.jpg') ?>" alt=""></a></figure>
                        <div class="popup">
<a href="img/d-img-3.jpg"  rel="prettyPhoto[gallery1]" class="sreach-button"><img src="<?php echo $this->basePath('img/magnifine-glass.png') ?>" alt="" /></a>
</div>
                    </span>
                    <span>
                    <p>Step 3: Thank you page</p>
                    <p>We have adjusted and incorporated Visual Composer plugin into our theme. You can easily build unlimited number of layout, because you can visualize what you will get at site page in the process of creation.</p>
                    </span>
                    
                    </li>
                	<li>
                    <span>
                    	<figure><img src="<?php echo $this->basePath('img/d-img-4.jpg') ?>" alt=""></figure>
                    </span>
                    <span>
                    <p>Frames</p>
                    <p>We have adjusted and incorporated Visual Composer plugin into our theme. You can easily build unlimited number of layout, because you can visualize what you will get at site page in the process of creation. Also it is very easy to rearrange and edit already created layouts.</p>
                    </span>
                    
                    </li>
                </ul>
                </div>
                
                <div class="about-this clearfix">
                <h5>Facebook coverphoto</h5>
                <p>We have adjusted and incorporated Visual Composer plugin into our theme. You can easily build unlimited number of layout, because you can visualize what you will get at site page in the process of creation. Also it is very easy to rearrange and edit already created layouts.</p>
                <span>
                <figure>
                <img src="<?php echo $this->basePath('img/d-img-5.jpg') ?>" alt="">
                </figure>
                </span>
                </div>
                
                <div class="about-this clearfix">
                <h5>Responsive app</h5>
                <p>We have adjusted and incorporated Visual Composer plugin into our theme. You can easily build unlimited number of layout, because you can visualize what you will get at site page in the process of creation. Also it is very easy to rearrange and edit already created layouts.</p>
                <span>
                <figure>
                <img src="<?php echo $this->basePath('img/d-img-6.jpg') ?>" alt="">
                </figure>
                </span>
                </div>
                
                <div class="about-this clearfix">
                <h5>Key features</h5>
                <div class="key-feature">
                <ul>
                	<li><a href="#">Feature  1</a></li>
                	<li><a href="#">Feature  2</a></li>
                	<li><a href="#">Feature  3</a></li>
                	<li><a href="#">Feature  4</a></li>
                	<li><a href="#">Feature  5</a></li>
                    </ul>
                    <ul>
                	<li><a href="#">Feature  6</a></li>
                	<li><a href="#">Feature  7</a></li>
                	<li><a href="#">Feature  8</a></li>
                	<li><a href="#">Feature  9</a></li>
                    <li><a href="#">Feature  10</a></li>
                </ul>
                
                </div>
                <div class="down-arrow">
                <a href=".sign-up-wrapper" class="drop-arrow-main js_onPageLink"><img src="<?php echo $this->basePath('img/arrow.png') ?>" alt=""></a>
                </div>
                </div>
                
                
                
               
                
                
                
                </div>
                
                
                <div class="information-right-cont col-lg-5">
                <h4>Campaign costs: <strong>€19,</strong>- p/m</h4>
                 <h5>Use this campaign?</h5> 
                 <a href="#" class="sign-up-free">Sign up free</a> 
                  <div class="social-wrap">
                  <ul>
                  	<li>Suitable for:</li>
                  	<li><a class="active" href="#"></a></li>
                  	<li><a href="#"></a></li>
                  	<li><a href="#"></a></li>
                  	<li><a href="#"></a></li>
                  	<li><a href="#"></a></li>
                  </ul>
                  </div>
                  <div class="ratings-wrapp">
                  <ul>
                  	<li>Campaign rating:</li>
                  	<li><img src="<?php echo $this->basePath('img/star-ratings.jpg') ?>" alt=""></li>
                  	<li>3.00 average based on 7 ratings</li>
                  	<li><a href="#">details</a></li>
                  </ul>
                  
                  </div>
                  <div class="other-user-campaign-info">
                  <table width="100%" border="1" cellspacing="0" cellpadding="0">
  <tr>
    <th colspan="3" scope="col">Other users who have used this campaign</th>
    </tr>
  <tr>
    <td>1.</td>
    <td>Koen1234</td>
    <td>Reached 2.000.282 people</td>
  </tr>
  <tr>
    <td>2.</td>
    <td>Henrik</td>
    <td>Reached 2.000.282 people</td>
  </tr>
  <tr>
    <td>3.</td>
    <td>Souvik</td>
    <td>Reached 2.000.282 people</td>
  </tr>
</table>

                  </div>
                  <div class="purchase-n-cmmnt">
                  
                  <div class="purchases">
                  <span>
                  <figure>
                  <img src="<?php echo $this->basePath('img/cart.png') ?>" alt="">
                  </figure>
                  </span>
                  <div class="pur-infos">
                  <span>Purchases</span>
                  <span>89</span>
                  </div>
                  </div>
                  
                  <div class="purchases cmmnt">
                  <span>
                  <figure>
                  <img src="<?php echo $this->basePath('img/commnt.png') ?>" alt="">
                  </figure>
                  </span>
                  <div class="pur-infos">
                  <span>Comments</span>
                  <span>89</span>
                  </div>
                  </div>
                  
                  
                  
                  </div>
                  <div class="social-share">
                  <ul>
                  	<li><a href="#"><img src="<?php echo $this->basePath('img/fb.jpg') ?>" alt=""></a></li>
                  	<li><a href="#"><img src="<?php echo $this->basePath('img/tw.jpg') ?>" alt=""></a></li>
                  	<li><a href="#"><img src="<?php echo $this->basePath('img/share.jpg') ?>" alt=""></a></li>
                  </ul>
                  </div>
                  
                  <div class="publisher-wrap">
                  
                  <h3>Publisher</h3>
                  <span><figure><img src="<?php echo $this->basePath('img/pub.jpg') ?>" alt=""></figure></span>
                  <span><figure><img src="<?php echo $this->basePath('img/pub-2.png') ?>" alt=""></figure></span>
                  <p>Lorem ipm dolor sit amet, consectetur adipiscing elit. Morbi consequat sollicitudin sagittis. Cras non elit nec urna adipiscing ullamcorper.</p>
                  <div class="rating-cont"><img src="<?php echo $this->basePath('img/star.png') ?>" alt=""></div>
                  <div class="publish-bt">
                  <ul>
                  	<li><a href="#">campaigns</a></li>
                  	<li><img src="<?php echo $this->basePath('img/icon-1.png') ?>" alt=""></li>
                  </ul>
                  </div>
                  
                  <div class="contact-author">
                  <h3>Contact author</h3>
                  <ul>
                  	<li>+31 413 266 380</li>
                  	<li>Send a request</li>
                  </ul>
                  </div>
                  
                  
                  </div>
                  
                  <div class="tag-container">
                  <h3>Tags</h3>
                  <div class="tags">
			<ul class="alt">
				<li><a href="#">Lorem ipsum</a></li> 
				<li class="active"><a href="#">Dolor sit amet</a></li>
				<li><a href="#">Consectetur adipiscing elit</a></li>
				<li><a href="#">Proin </a></li>
				<li><a href="#">Sagittis libero</a></li>
				<li><a href="#">Aliquet augue</a></li>
				<li><a href="#">Quisque dui lacus</a></li>
				<li><a href="#">Consequat</a></li>
				<li><a href="#">Dictum non</a></li>
				<li><a href="#">Venenatis et tortor</a></li>
				<li><a href="#">Suspendisse mauris</a></li>
				<li><a href="#">In accumsan </a></li>
				<li><a href="#">Egestas neque</a></li>
				<li><a href="#">Mauris eget felis</a></li>
				<li><a href="#">Suspendisse</a></li>
				<li><a href="#">condimentum eleifend nulla</a></li>
			</ul>
		</div>
                  </div>
                    
                  </div>
                </div>
                
              <!--  ================================================== first tab end   ==================================================-->
                
                <div class="information-wrapper comment-wrapper" id="tab2">
                
                <div class="information-left-cont col-lg-7">
                <div class="about-this clearfix">
                <div class="commnt-head">
                <h3>Comments about this campaign (12)</h3>
                <span><figure><img src="<?php echo $this->basePath('img/commnt-2.png') ?>" alt=""></figure><p>Leave a new comment</p></span>
                </div>
                
                
                </div>
                
                <div class="commnt-box">
                <ul>
                	<li>
                    <span>
                    <h5>weibinhuang </h5><p>12 december 2013</p>
                    </span>
                    <span>Hi, I am a beginner of using wordpress. May I know how to reduce the space between the header and post in this theme? I have set the static page as homepage. Many thanks!</span>
                    </li>
                	<li>
                    <div class="commnt-fig"><figure><img src="<?php echo $this->basePath('img/cmmnt.jpg') ?>" alt=""></figure></div>
                    <div class="commnt-raw">
                    <span>
                    <h5>eaf1ef </h5><p>12 december 2013</p>
                    </span>
                    <span>Hi! Please provide link to your page (or just screenshot) and explain what space do you mean. Thanks!</span>
                    </div>
                    </li>
                </ul>
                </div>
                <div class="leave-a-reply">
                <figure><img src="<?php echo $this->basePath('img/commnt-2.png') ?>" alt=""></figure><p>Leave a new comment</p>
                </div>
                <div class="commnt-box">
                <ul>
                	<li>
                    <span>
                    <h5>weibinhuang </h5><p>12 december 2013</p>
                    </span>
                    <span>Hi, I am a beginner of using wordpress. May I know how to reduce the space between the header and post in this theme? I have set the static page as homepage. Many thanks!</span>
                    </li>
                	<li>
                    <div class="commnt-fig"><figure><img src="<?php echo $this->basePath('img/cmmnt.jpg') ?>" alt=""></figure></div>
                    <div class="commnt-raw">
                    <span>
                    <h5>eaf1ef </h5><p>12 december 2013</p>
                    </span>
                    <span>Hi! Please provide link to your page (or just screenshot) and explain what space do you mean. Thanks!</span>
                    </div>
                    </li>
                </ul>
                </div>
                
                <div class="form-conatainer">
                <form method="post" name="login">
                    <ul>
                        <li class="clearfix">
                            <label id="emailtab"> Name</label>
                            <input type="text" name=" Name" value="">
                        </li>
                        
                        <li class="clearfix">
                            <label id="emailtab"> Email</label>
                            <input type="text" name=" Email" value="">
                        </li>
                        
                        <li class="clearfix">
                            <label id="emailtab"> Comment</label>
                            <textarea name="comment" cols="" rows=""></textarea>
                        </li>
                        
                        <li class="clearfix">
                            <label id="emailtab"></label>
                            <input type="submit" name=" submit" value="SUBMIT COMMENT">
                        </li>
                        
                    </ul>
                </form>
                </div>
                <div class="commnt-box">
                <ul>
                	<li>
                    <span>
                    <h5>weibinhuang </h5><p>12 december 2013</p>
                    </span>
                    <span>Hi, I am a beginner of using wordpress. May I know how to reduce the space between the header and post in this theme? I have set the static page as homepage. Many thanks!</span>
                    </li>
                	<li>
                    <div class="commnt-fig"><figure><img src="<?php echo $this->basePath('img/cmmnt.jpg') ?>" alt=""></figure></div>
                    <div class="commnt-raw">
                    <span>
                    <h5>eaf1ef </h5><p>12 december 2013</p>
                    </span>
                    <span>Hi! Please provide link to your page (or just screenshot) and explain what space do you mean. Thanks!</span>
                    </div>
                    </li>
                </ul>
                </div>
                <div class="leave-a-reply">
                <figure><img src="<?php echo $this->basePath('img/commnt-2.png') ?>" alt=""></figure><p>Leave a new comment</p>
                </div>
                <hr>
                <a class="big-leave-comment">
                Leave a new comment
                </a>
                
                
                
                
                
                
                
                </div>
                
                <div class="information-right-cont col-lg-5">
                <h4>Campaign costs: <strong>€19,</strong>- p/m</h4>
                 <h5>Use this campaign?</h5> 
                 <a href="#" class="sign-up-free">Sign up free</a> 
                  <div class="social-wrap">
                  <ul>
                  	<li>Suitable for:</li>
                  	<li><a class="active" href="#"></a></li>
                  	<li><a href="#"></a></li>
                  	<li><a href="#"></a></li>
                  	<li><a href="#"></a></li>
                  	<li><a href="#"></a></li>
                  </ul>
                  </div>
                  <div class="ratings-wrapp">
                  <ul>
                  	<li>Campaign rating:</li>
                  	<li><img src="<?php echo $this->basePath('img/star-ratings.jpg') ?>" alt=""></li>
                  	<li>3.00 average based on 7 ratings</li>
                  	<li><a href="#">details</a></li>
                  </ul>
                  
                  </div>
                  <div class="other-user-campaign-info">
                  <table width="100%" border="1" cellspacing="0" cellpadding="0">
  <tbody><tr>
    <th scope="col" colspan="3">Other users who have used this campaign</th>
    </tr>
  <tr>
    <td>1.</td>
    <td>Koen1234</td>
    <td>Reached 2.000.282 people</td>
  </tr>
  <tr>
    <td>2.</td>
    <td>Henrik</td>
    <td>Reached 2.000.282 people</td>
  </tr>
  <tr>
    <td>3.</td>
    <td>Souvik</td>
    <td>Reached 2.000.282 people</td>
  </tr>
</tbody></table>

                  </div>
                  <div class="purchase-n-cmmnt">
                  
                  <div class="purchases">
                  <span>
                  <figure>
                  <img src="<?php echo $this->basePath('img/cart.png') ?>" alt="">
                  </figure>
                  </span>
                  <div class="pur-infos">
                  <span>Purchases</span>
                  <span>89</span>
                  </div>
                  </div>
                  
                  <div class="purchases cmmnt">
                  <span>
                  <figure>
                  <img src="<?php echo $this->basePath('img/commnt.png') ?>" alt="">
                  </figure>
                  </span>
                  <div class="pur-infos">
                  <span>Comments</span>
                  <span>89</span>
                  </div>
                  </div>
                  
                  
                  
                  </div>
                  <div class="social-share">
                  <ul>
                  	<li><a href="#"><img src="<?php echo $this->basePath('img/fb.jpg') ?>" alt=""></a></li>
                  	<li><a href="#"><img src="<?php echo $this->basePath('img/tw.jpg') ?>" alt=""></a></li>
                  	<li><a href="#"><img src="<?php echo $this->basePath('img/share.jpg') ?>" alt=""></a></li>
                  </ul>
                  </div>
                  
                  <div class="publisher-wrap">
                  
                  <h3>Publisher</h3>
                  <span><figure><img src="<?php echo $this->basePath('img/pub.jpg') ?>" alt=""></figure></span>
                  <span><figure><img src="<?php echo $this->basePath('img/pub-2.png') ?>" alt=""></figure></span>
                  <p>Lorem ipm dolor sit amet, consectetur adipiscing elit. Morbi consequat sollicitudin sagittis. Cras non elit nec urna adipiscing ullamcorper.</p>
                  <div class="rating-cont"><img src="<?php echo $this->basePath('img/star.png') ?>" alt=""></div>
                  <div class="publish-bt">
                  <ul>
                  	<li><a href="#">campaigns</a></li>
                  	<li><img src="<?php echo $this->basePath('img/icon-1.png') ?>" alt=""></li>
                  </ul>
                  </div>
                  
                  <div class="contact-author">
                  <h3>Contact author</h3>
                  <ul>
                  	<li>+31 413 266 380</li>
                  	<li>Send a request</li>
                  </ul>
                  </div>
                  
                  
                  </div>
                  
                  <div class="tag-container">
                  <h3>Tags</h3>
                  <div class="tags">
			<ul class="alt">
				<li><a href="#">Lorem ipsum</a></li> 
				<li class="active"><a href="#">Dolor sit amet</a></li>
				<li><a href="#">Consectetur adipiscing elit</a></li>
				<li><a href="#">Proin </a></li>
				<li><a href="#">Sagittis libero</a></li>
				<li><a href="#">Aliquet augue</a></li>
				<li><a href="#">Quisque dui lacus</a></li>
				<li><a href="#">Consequat</a></li>
				<li><a href="#">Dictum non</a></li>
				<li><a href="#">Venenatis et tortor</a></li>
				<li><a href="#">Suspendisse mauris</a></li>
				<li><a href="#">In accumsan </a></li>
				<li><a href="#">Egestas neque</a></li>
				<li><a href="#">Mauris eget felis</a></li>
				<li><a href="#">Suspendisse</a></li>
				<li><a href="#">condimentum eleifend nulla</a></li>
			</ul>
		</div>
                  </div>
                    
                  </div>
                </div>
                
                <!--  ================================================== secoend tab end   ==================================================-->
            </section>
        </div>