
<div  class="site">
  <div class="container-fluid"> 
    <!--===== start banner ===-->
    <div class="row">
      <div class="banner developers">
        <ul class="social_icon">
          <li><a href="#">Share this website</a></li>
          <li><a href="#"></a> <a href="#"></a> <a href="#"></a></li>
        </ul>
      
    </div>
      
    </div><!--===== end banner ===--> 
    <div class="container-fluid" > 
      
     <section class="developers-cont row col-lg-12">
     
     
       
        <h2>For Developers</h2>
        <p>what do you want to do?</p>
        <a href="<?=$this->url('application/default', array('controller' => 'index', 'action' => 'documentation')); ?>">Visit our Documentation centre</a>
        <a href="<?=$this->url('application/default', array('controller' => 'developer', 'action' => 'index')); ?>">Add your app to our themestore</a>
        
        
        </section>
    
      </div>
       <div style="position:relative;"><hr> <a id="back-to-top" class="go_to_up" href="#"></a></div>
    </div><!--===== body_container end ===--> 
  </div> <!--===== main_container end ===--> 


<script type="text/javascript" src="js/main.js"></script>
<script type="text/javascript">
$(function(){
    $("a.js_onPageLink").bind("click", function (event) {
        event.preventDefault ? event.preventDefault() : event.returnValue = false;
        var target = $(this).attr("href");
        $("html, body").stop().animate({
                scrollLeft: $(target).offset().left,
                scrollTop: $(target).offset().top
            }, 1200);
    });
});
</script>
</body>
</html>
