<!--===== body start ===-->
<div class="site">
  <div class="container-fluid"> 
    <!--===== start banner ===-->
  <div class="row">  
  <div class="banner documentation">
  
  <h1>Devlopers Section</h1>
  <span><!---<img src="img/documentation_bg.jpg" alt="" />---></span>
  
      </div>
    
    </div>
    
    <div class="container-fluid">
    
    
   <section class="documentation-cont row col-lg-12">
     
    <h5>Hey Developers !!!</h5>
    <p> It is now possible to make your facebook application in a very easiest way. Smartfanpage is helping you to reduce all hastles of facebook application building.<br />
    Just upload your code and make your application.<br />
    Following are the steps which will help you to upload your code.</p>
       
       <hr/>
       
       

<div class="horizontalTab">


  <ul class="resp-tabs-list home_publisher_tab">
  <li><a href="#tab-1">Step 1</a></li>
  <li><a href="#tab-2">Step 2</a></li>
  <li><a href="#tab-3">Step 3</a></li>
  <li><a href="#tab-4">Step 4</a></li>
  </ul>
  <hr>


<div id="tab-1">

	<div class="doc_data">
    
     <h2>Registration and login section :</h2>
    <ul>
    
        	<li>A. If you are a new user, register your account in Developer Registration section.<a href="http://test.scampaigns.com/developer/index" target="_blank">Click here</a> </li>
        	<li>B. If you are already registered , login your profile.<a href="http://test.scampaigns.com/developer/login" target="_blank">Click here</a></li></ul>
    </div>
    


</div>


<div id="tab-2">
<div class="doc_data">

      <h2>Steps To Upload Your Template</h2>
    	<ul>
      
        	<li>1. You should provide the Campaign Name.This campaign name will be your root template folder name.</li>
            <li>2. You should provide Campaign Description.</li>
            <li>3. Please upload your ZIP template</li>
            <li>4. Please upload your ZIP template's Screenshot</li>
        	
        </ul>
    </div>
    <p class="urg_msg">Important Information of uploading files</p>
    <div class="doc_data">
    <h2>Note:</h2>
    	<ul>
            <li>A. Your campaign name should be unique.</li>
        	<li>B. You should upload files in ZIP format</li>
        	<li>C. Your uploaded file format will be following:<br />
            &nbsp;&nbsp;1. Index file should present in your root tempalte folder i.e index.php or index.html<br />
            &nbsp;&nbsp;2. Your uploaded screen-shot image should not be present in Zip folder.
            </li>
            <li>D. After you upload your files an automatic mail will be sent to Admin.Admin will approve your template.</li>

        </ul>
    </div>
    
    
</div>
<div id="tab-3">
<div class="doc_data">

          <h2>Dashboard Section:</h2>
    	<ul>
        	<li>A. Click on 'Delete Template' to delete your uploaded templates</li>
        	<li>B. Click on 'Upload File' to upload a new template.</li>
        	<li>C. Click on 'Edit Template' to edit your template's file.</li>
        </ul>
    </div>

</div>
<div id="tab-4">
<div class="doc_data">

          <h2>Template Edit Section:</h2>
    	<ul>
        	<li>A. Click on any file name from left side bar, and find your code in the textarea.</li>
        	<li>B. Edit your file.</li>
        	<li>C. Click on 'Update' to save your edited file.</li>
        </ul>
    </div>
   
   
</div>
<div style="position:relative;"><hr> <a id="back-to-top" class="go_to_up" href="#"></a></div>
</div>
  
        </section>
		</div>
    </div><!--===== body_container end ===-->     
  </div> <!--===== main_container end ===--> 

<script type="text/javascript">
$(function(){
    $("a.js_onPageLink").bind("click", function (event) {
        event.preventDefault ? event.preventDefault() : event.returnValue = false;
        var target = $(this).attr("href");
        $("html, body").stop().animate({
                scrollLeft: $(target).offset().left,
                scrollTop: $(target).offset().top
            }, 1200);
    });
});
</script>
</body>
</html>
