<div  class="site">
  <div class="container-fluid"> 
    <!--===== start banner ===-->
    <div class="row">
      <div class="banner how-does-bg" style="background:url(<?php echo $content->Imagelink; ?>) no-repeat top center; background-size: cover -webkit-background-size: cover;-moz-background-size: cover;-o-background-size: cover;background-size: 100% 100%;">
    
        <ul class="social_icon">
          <li><a href="#">Share this website</a></li>
          <li><a href="#"></a> <a href="#"></a> <a href="#"></a></li>
        </ul>
        <div class="clearfix"></div>
        <div class="banner_caption3 col-md-8 res-text" >
          <h1><?php echo $content->bannerheader;?></h1>
          
          
      </div>
      
    </div>
      
    </div><!--===== end banner ===--> 
    <div class="container-fluid" > 
      
     <section class="how-does-work-cont row">
     <?php foreach ($contentpass as $p) :?>
        <div class="step-wrapper col-lg-6 col-sm-6">
        
        <div class="step-left-overlay">
        
        <div class="step-left"><span><img src="<?php echo $p->Imagepath; ?>" alt=""></span></div>
        </div>
        <div class="step-right">
        <h3><?php echo $p->header; ?></h3>
        <p><?php echo $p->Description; ?></p>
        </div>
        </div>
        <?php endforeach; ?>    
        
        </section>