<img src="https://test.scampaigns.com/img/divider.png" id="imgdragable" style="display: none;">
 



<meta http-equiv="Content-Type" content="text/html; charset=utf-8">

<link rel="stylesheet" href="//test.scampaigns.com/user_template/82454620ee9cf63712-Optinapp--mod-template/css/style.css">
<!--<link rel="stylesheet" href="http://localhost/zf_new/public/css/styles.css"/>
<link rel="stylesheet" href="http://localhost/zf_new/public/css/textarea.css"/>---->

<link rel="stylesheet" type="text/css" media="all" href="//test.scampaigns.com/user_template/82454620ee9cf63712-Optinapp--mod-template/css/jui.checkboxes.css">

<!-- <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>
   <script src = "http://js.nicedit.com/nicEdit-latest.js"></script>--->
 

<!---<script type="text/javascript" src="http://localhost/zf_new/public/js/jquery.form.js"></script>
<script type="text/javascript" src="http://localhost/zf_new/public/js/style.js"></script>---->



(complete.php)
<div class="details-n-winn-wrapper">
<div class="SFPTWO_IMAGEEDIT rand_529" style="display: none;" id=""><img id="images1" src="//test.scampaigns.com/user_template/82454620ee9cf63712-Optinapp--mod-template/img/top-img.jpg" alt=""><div class="setting-2" style="display: none;"><a title="Edit" class="edit" href="javascript:void(0)"></a><a title="delete" class="delete" href="javascript:void(0)"></a><input type="hidden" value="82454620ee9cf63712-Optinapp--mod-template" id="hid"><input type="hidden" value="0" id="imgCount"></div><div class="setting-2" style="display:none"><a title="Edit" class="edit" href="javascript:void(0)"></a><a title="delete" class="delete" href="javascript:void(0)"></a><input type="hidden" value="82454620ee9cf63712-Optinapp--mod-template" id="hid"><input type="hidden" value="0" id="imgCount"></div><div class="setting-2" style="display:none"><a title="Edit" class="edit" href="javascript:void(0)"></a><a title="delete" class="delete" href="javascript:void(0)"></a><input type="hidden" value="82454620ee9cf63712-Optinapp--mod-template" id="hid"><input type="hidden" value="0" id="imgCount"></div><div class="setting-2" style="display:none"><a title="Edit" class="edit" href="javascript:void(0)"></a><a title="delete" class="delete" href="javascript:void(0)"></a><input type="hidden" value="82454620ee9cf63712-Optinapp--mod-template" id="hid"><input type="hidden" value="0" id="imgCount"></div></div> 
<div class="SFPTWO_IMAGEEDIT ui-resizable" id="editable" style="height: 360px; width: 763px; top: 0px; left: 0px;"><div id="draggable0" style="z-index: 0; position: absolute; left: -79px; top: -94px;" class="ui-draggable"><div><div id="resizable0" style="z-index:0; height:768px; width:1024px;" class="ui-resizable"><img class="layeredImage ui-draggable" id="images0" src="http://test.scampaigns.com/library/3ad5f635e16ff007d3c3e43fa7e1782d.jpg" style="height: 100%; width: 100%; z-index: 0; position: relative;"><div class="ui-resizable-handle ui-resizable-ne" style="z-index: 1000;"></div><div class="ui-resizable-handle ui-resizable-se ui-icon ui-icon-gripsmall-diagonal-se" style="z-index: 1000;"></div><div class="ui-resizable-handle ui-resizable-sw" style="z-index: 1000;"></div><div class="ui-resizable-handle ui-resizable-nw" style="z-index: 1000;"></div></div></div></div><div class="setting-2" style="display: none;"><a title="Edit" class="edit" href="javascript:void(0)"></a><a title="delete" class="delete" href="javascript:void(0)"></a><input type="hidden" value="82454620ee9cf63712-Optinapp--mod-template" id="hid"><input type="hidden" value="1" id="imgCount"></div><div class="ui-resizable-handle ui-resizable-s" style="z-index: 1000;"></div><div class="setting-2" style="display: none;"><a title="Edit" class="edit" href="javascript:void(0)"></a><a title="delete" class="delete" href="javascript:void(0)"></a><input type="hidden" value="82454620ee9cf63712-Optinapp--mod-template" id="hid"><input type="hidden" value="0" id="imgCount"></div><div class="setting-2" style="display: none;"><a title="Edit" class="edit" href="javascript:void(0)"></a><a title="delete" class="delete" href="javascript:void(0)"></a><input type="hidden" value="82454620ee9cf63712-Optinapp--mod-template" id="hid"><input type="hidden" value="0" id="imgCount"></div><div class="setting-2" style="display: none;"><a title="Edit" class="edit" href="javascript:void(0)"></a><a title="delete" class="delete" href="javascript:void(0)"></a><input type="hidden" value="82454620ee9cf63712-Optinapp--mod-template" id="hid"><input type="hidden" value="0" id="imgCount"></div></div>         
        
<div class="tool-tip SFPTWO_TEXTEDIT"><h2 class="textedit SFPTWO_TAGEDIT edit explicit_edit" contenteditable="false"><font color="#50d8f1">Fill in you<font face="Times New Roman">r dails and win! </font></font></h2><div class="setting-2" id="text" style="display: none;"><a title="Edit" class="edit" href="javascript:void(0)"></a><a title="delete" class="delete" href="javascript:void(0)"></a></div><div class="setting-2" id="text" style="display:none"><a title="Edit" class="edit" href="javascript:void(0)"></a><a title="delete" class="delete" href="javascript:void(0)"></a></div><div class="setting-2" id="text" style="display:none"><a title="Edit" class="edit" href="javascript:void(0)"></a><a title="delete" class="delete" href="javascript:void(0)"></a></div><div class="setting-2" id="text" style="display:none"><a title="Edit" class="edit" href="javascript:void(0)"></a><a title="delete" class="delete" href="javascript:void(0)"></a></div></div>
<div class="form-container jui-checkboxes-container" id="checkboxesInit2">


<ul class="designelements clearfix" style="position:absolute;left:20%;">
 <li id="lilabelme" style="top: 52px; left: 9px; position: relative; display: none;"><a style="cursor: pointer;" onclick="chechTypeAndAdd(this.rel)" rel="checkbox" id="checkbox"><span>Checkbox</span><img src="https://test.scampaigns.com/formbuild/checkbox_icon.png" alt=""></a></li>
   
</ul>
<form id="" action="complete.php" class="SFPTWO_EDITFORM" style="margin-top:25px;">

 <img src="https://test.scampaigns.com/img/divider.png" id="imgdrag" style="position: relative; top: 52px; display: none;">


<ul class="sortable-list ui-sortable">

	<li class="dottedLi ui-draggable" style="position: relative; z-index: 1;"><div id="diveditme" class="labeledit addmechk checkboxdrag"><p style="font-size: 19px;" id="pid_form" class="opt">What kind of campaign are you Looking for? 
    </p></div><div class="checksboxes p_scents chkboxaddnow editmyopt adding" id="checksboxes_form657"><div id="chkclone"><div for="p_scnts" class="jui-checkbox-row" id="jui-checkbox-rowform657"><span class="checkboxWrapper"><input type="checkbox" value="1" name="name"> </span> <p class="opt" id="1">option1</p> </div><div class="jui-checkbox-row"> <span class="checkboxWrapper"><input type="checkbox" value="2" name="name"></span> <p class="opt" id="2">option2</p> </div><div class="jui-checkbox-row"><span class="checkboxWrapper"><input type="checkbox" value="3" name="name"></span><p class="opt" id="3">option3</p></div><div class="jui-checkbox-row"><span class="checkboxWrapper"><input type="checkbox" name="name" value="4"></span><p id="4" class="opt">option4</p></div></div><p id="mepp" class="pchkadd"></p></div> <div class="setting-2 prevnext"><a title="Edit" class="edit" href="javascript:void(0)"></a><a title="delete" class="delete" href="javascript:void(0)"></a><input type="hidden" id="hid"><input type="hidden" value="0" id="imgCount"><a class="prev" href="#">Previous</a>&nbsp;<a class="next" href="#">After</a></div><div class="setting-2 prevnext"><a title="Edit" class="edit" href="javascript:void(0)"></a><a title="delete" class="delete" href="javascript:void(0)"></a><input type="hidden" id="hid"><input type="hidden" value="0" id="imgCount"><a class="prev" href="#">Previous</a>&nbsp;<a class="next" href="#">After</a></div></li><li class="" style="position: relative;"><div id="diveditme" class="labeledit editmyoptme"><p style="font-size: 19px;" id="pid_formmsg" class="opt">Your message</p><div><textarea id="editmetext" name=""></textarea></div></div><div class="setting-2 prevnext"><a title="Edit" class="edit" href="javascript:void(0)"></a><a title="delete" class="delete" href="javascript:void(0)"></a><input type="hidden" id="hid"><input type="hidden" value="0" id="imgCount"><a class="prev" href="#">Previous</a>&nbsp;<a class="next" href="#">After</a></div><div class="setting-2 prevnext"><a title="Edit" class="edit" href="javascript:void(0)"></a><a title="delete" class="delete" href="javascript:void(0)"></a><input type="hidden" id="hid"><input type="hidden" value="0" id="imgCount"><a class="prev" href="#">Previous</a>&nbsp;<a class="next" href="#">After</a></div></li><li class="dottedLi ui-draggable"><div id="labeledit" class="labeledit emaildrag editlabelme"><p style="font-size: 19px;" id="pid_" class="opt">EmaiL address</p></div><input name="" type="text">
    <div class="setting-2 prevnext"><a title="Edit" class="edit" href="javascript:void(0)"></a><a title="delete" class="delete" href="javascript:void(0)"></a><input type="hidden" id="hid"><input type="hidden" value="0" id="imgCount"><a class="prev" href="#">Previous</a>&nbsp;<a class="next" href="#">After</a></div>
    <div class="setting-2 prevnext"><a title="Edit" class="edit" href="javascript:void(0)"></a><a title="delete" class="delete" href="javascript:void(0)"></a><input type="hidden" id="hid"><input type="hidden" value="0" id="imgCount"><a class="prev" href="#">Previous</a>&nbsp;<a class="next" href="#">After</a></div></li>
    

	
    

	 
	<li><input name="" type="submit" value="Send" class="inputdisabled"><div class="setting-2 prevnext"><a title="Edit" class="edit" href="javascript:void(0)"></a><a title="delete" class="delete" href="javascript:void(0)"></a><input type="hidden" id="hid"><input type="hidden" value="0" id="imgCount"><a class="prev" href="#">Previous</a>&nbsp;<a class="next" href="#">After</a></div><div class="setting-2 prevnext"><a title="Edit" class="edit" href="javascript:void(0)"></a><a title="delete" class="delete" href="javascript:void(0)"></a><input type="hidden" id="hid"><input type="hidden" value="0" id="imgCount"><a class="prev" href="#">Previous</a>&nbsp;<a class="next" href="#">After</a></div></li>

</ul>
<div class="setting-2" style="display:none"><a title="setup" class="setup" href="javascript:void(0)"></a><a title="delete" class="delete" href="javascript:void(0)"></a><input type="hidden" value="82454620ee9cf63712-Optinapp--mod-template" id="hid"></div><div class="setting-2" style="display:none"><a title="setup" class="setup" href="javascript:void(0)"></a><a title="delete" class="delete" href="javascript:void(0)"></a><input type="hidden" value="82454620ee9cf63712-Optinapp--mod-template" id="hid"></div><div class="setting-2" style="display:none"><a title="setup" class="setup" href="javascript:void(0)"></a><a title="delete" class="delete" href="javascript:void(0)"></a><input type="hidden" value="82454620ee9cf63712-Optinapp--mod-template" id="hid"></div><div class="setting-2" style="display:none"><a title="setup" class="setup" href="javascript:void(0)"></a><a title="delete" class="delete" href="javascript:void(0)"></a><input type="hidden" value="82454620ee9cf63712-Optinapp--mod-template" id="hid"></div></form>[(complete.php)]
</div>
</div>