<div class="site">
<table class="table">
<tr>
    <th>id</th>
    <th>First Name</th>
   <th>Last Name</th>
   <th>Email</th>
   <th>Action</th>
</tr>

<?php foreach ($developers as $developer) : ?>
<tr>
    <td><?php echo $this->escapeHtml($developer->id);?></td>
    <td><?php echo $this->escapeHtml($developer->fName);?></td>
    <td><?php echo $this->escapeHtml($developer->lName);?></td>
    <td><?php echo $this->escapeHtml($developer->eId);?></td>
     <td><a href="#">Update</a><p></p><a href="#">delete</a></td>
    
    
  
</tr>
<?php endforeach; ?>
</table>