<div class="site">
<div class="container-fluid" id="devlogin">
<div class="row"><p id="fly-it" class="top_heading col-md-12 center">Developer Login</p></div>
<div class="col-md-6 col-md-offset-3 dev-form clearfix">
<?php 

$form->setAttribute('action', $this->url('application/default', array('controller'=>'developer','action' => 'logging')));
$form->prepare();

 echo $this->form()->openTag($form);?>
<li>
    <?php echo $this->formRow($form->get('uname'));?>
</li>
<li>
    <?php echo $this->formRow($form->get('pwd'));?>    
</li>
<li>
    <?php echo $this->formElement($form->get('login'));?>
</li>
<?php echo $this->form()->closeTag();
?>

<div id="message">
<?php 

    $protocol = '';
        if (isset($_SERVER[‘HTTPS’]) &&
       ($_SERVER[‘HTTPS’] == ‘on’ || $_SERVER[‘HTTPS’] == 1) ||
        isset($_SERVER[‘HTTP_X_FORWARDED_PROTO’]) &&
        $_SERVER[‘HTTP_X_FORWARDED_PROTO’] == ‘https’) {
         $protocol = 'https://';
        }
        else {
        $protocol = 'http://';
           }
       // echo $_SERVER['SERVER_PROTOCOL'].$_SERVER['HTTP_HOST'].$_SERVER['REQUEST_URI'];
        $url = $protocol.$_SERVER["SERVER_NAME"];

if($error)
{
    echo "Please register <a href='".$url."/developer'>here</a> to log in";
}
?></div>

</div>
</div>
