<div class="site">
<div class="container-fluid">
<?php  
$url="http://". $_SERVER['SERVER_NAME'];
?>
<p>If you are already registered , login your profile.<a href="<?php echo $url;?>/developer">Click here</a></p>
<div class="row"><p id="fly-it" class="top_heading col-md-12 center">Developer Registration</p></div>
<div class="col-md-6 col-md-offset-3 dev-form clearfix">

<?php  
$form->setAttribute('action', $this->url('application/default', array('controller'=>'developer','action' => 'registering')));
$form->prepare();
echo $this->form()->openTag($form);?>
<li>
    <?php echo $this->formRow($form->get('id'));?>
</li>
<li>
    <?php echo $this->formRow($form->get('fName'));?>
</li>
<li>
    <?php echo $this->formRow($form->get('lName'));?>
</li>
<li>
    <?php echo $this->formRow($form->get('eId'));?>
</li>
 <li>
    <?php echo $this->formRow($form->get('uname'));?>
</li>
<li>
    <?php echo $this->formRow($form->get('pwd'));?>    
</li>
<li>
    <?php echo $this->formElement($form->get('submit'));?>
</li>
<?php echo $this->form()->closeTag();
?>

<div id="message">
<?php 

if($error)
{
    echo "The email id is already registered.";
}
?></div>
</div>
</div>