<div class="site">
<h1>
Upload File</h1>
<?php 

$form = $this->form;
$form->setAttribute('action', $this->url('application/default', array('controller'=>'template','action' => 'addTemplate')));
$form->prepare();

?>

<!-- T?o th? <form...> và các giá tr? thu?c tính c?a th? này -->
<?php echo $this->form()->openTag($form);?>

<ul>
<li>
<?php echo $this->formRow($form->get('tempName'));?>
</li>
<li>
      <!--In ra giá tr? nhãn  -->
      <span><?php echo '<br />'; echo $this->formLabel($form->get('picture')); ?></span>
      
      <!--T?o ph?n t? HTML cho vi?c Upload -->
      <?php echo $this->formElement($form->get('picture')); ?>
   </li>
<li>
      <!--T?o nút Submit -->
      <?php echo $this->formElement($form->get('submit'));?>
   </li>
</ul>
<!-- Ðóng th? </form>
-->
<?php echo $this->form()->closeTag() ?>
