<div class="site">
<div class="row">
<div class="col-lg-8 col-md-offset-2">

<?php  


$form = $this->form;

$form->setAttribute('action', $this->url('application/default', array('controller'=>'admin','action' => 'insert')));
$form->prepare();?>
<div class="table_button">
<a href="<?php echo $this->url('application/default',array('controller'=>'Admin','action'=>'pagedetails'));?>">Back to page details</a>


<?php echo $this->form()->openTag($form);?>

<?php
 echo $this->formRow($form->get('id'));?>

<table width="100%" cellspacing="0" cellpadding="0" border="0" class="table_wrap">
<tr><th colspan="2">Add Steps</th></tr>
<tr><td><label>Header</label></td><td><?php echo $this->formRow($form->get('header'));?></td></tr>
<tr><td><label>Image upload:</label></td><td><?php echo $this->formRow($form->get('imagename'));?></td></tr>
<tr><td><label>Description</label></td><td><?php echo $this->formRow($form->get('Description'));?></td></tr>
<tr><td>&nbsp;</td><td> <?php
 


 echo $this->formSubmit($form->get('submit'));
 //echo $this->formCollection($form);
 
 ?></td></tr>

 
 

 </table>
 
 <?php 
 echo $this->form()->closeTag();
 
?>
 




</div>
</div>