

<div class="site">

 <div class="row">
 <div class="col-lg-8 col-md-offset-2">

<?php 

$form = $this->form;
$form->prepare();
?>

<?php echo $this->form()->openTag($form);?>
 <div class="table_button">
<a href="<?php echo $this->url('application/default',array('controller'=>'Admin','action'=>'pagedetails'));?>">Back to page details</a>

<?php $id;?>

 <table width="100%" border="0" cellspacing="0" cellpadding="0" class="table_wrap">
 <tr>
 <th colspan="2">Image Edit</th> </tr>
<tr>
<td> <?php echo $this->formLabel($form->get('imgHeader')); ?></td>
     <td> <?php echo $this->formElement($form->get('imgHeader'));?></td>
     
     </tr>
 

   <tr>
   <td><?php echo $this->formLabel($form->get('imgSubHeader')); ?></td>
     <td><?php echo $this->formElement($form->get('imgSubHeader'));?></td>
     </tr>
  <tr>
  <td><?php echo $this->formLabel($form->get('imgDescription')); ?></td>
     <td><?php echo $this->formElement($form->get('imgDescription'));?></td>
     </tr>
   
<tr><td>
  
      <?php echo $this->formLabel($form->get('picture')); ?>
      
 </td>
     <td> 
      <?php echo $this->formElement($form->get('picture')); ?>
      </td>
     </tr>
      <tr><td></td><td>
      <?php echo $this->formElement($form->get('submit'));?></td>
     </tr>
 
   </table>   

  
</div>
</div>
</div>
<?php echo $this->form()->closeTag() ?>

