<div class="site">
<div class="row">
<div class="col-lg-8 col-md-offset-2">

<?php 

$form = $this->form;
$form->prepare();
?>

<?php echo $this->form()->openTag($form);?>

<div class="table_button">
<a href="<?php echo $this->url('application/default',array('controller'=>'Admin','action'=>'pagedetails'));?>">Back to page details</a>


<table width="100%" cellspacing="0" cellpadding="0" border="0" class="table_wrap">


 <tr><th colspan="2">Insert Case Studies</th></tr>
  <tr>
      <td><?php echo $this->formLabel($form->get('vedioHeader')); ?></td>
      <td><?php echo $this->formElement($form->get('vedioHeader'));?></td>
  </tr>
  <tr>
      <td><?php echo $this->formLabel($form->get('VedioDescription')); ?></td>
      <td><?php echo $this->formElement($form->get('VedioDescription'));?></td>
  </tr>
  <tr>
      <td><?php echo $this->formLabel($form->get('VedioPath')); ?></td>
      <td><?php echo $this->formElement($form->get('VedioPath'));?></td>
  </tr>
  <tr>
      <td>&nbsp;</td>
      <td><?php echo $this->formElement($form->get('submit'));?></td>
  </tr>


   </table>




</div>
</div>
<?php echo $this->form()->closeTag() ?>
