  
<div class="site">
<div class="row">
<div class="col-lg-8 col-md-offset-2">
 
<?php  

$form = $this->form;

$form->setAttribute('action', $this->url('application/default', array('controller'=>'Admin','action' => 'updatevalue','id'=>$id)));
$form->prepare();

 echo $this->form()->openTag($form);
 ?>
 <div class="table_button">
<a href="<?php echo $this->url('application/default',array('controller'=>'Admin','action'=>'show'));?>">Show Slides </a>
<a href="<?php echo $this->url('application/default',array('controller'=>'Admin','action'=>'showwalloffame'));?>">Show Wall off fame Picture</a>
<a href="<?php echo $this->url('application/default',array('controller'=>'Admin','action'=>'pagedetails'));?>">Back to page details</a>
</div>
<table width="100%" border="0" cellspacing="0" cellpadding="0" class="table_wrap">

 
<tr><th colspan="2">Home Page Edit</th></tr>

 <tr><td><label>Banner Header</label></td><td><?php echo $this->formRow($form->get('change_tagline'));?></td></tr>
<tr><td><label>Banner Tagline</label></td><td><?php echo $this->formRow($form->get('text2'));?></td></tr>
<tr><td><label>campaign Heading</label></td><td><?php echo $this->formRow($form->get('text3'));?></td></tr>
 <tr><td><label>Blog Header</label></td><td><?php echo $this->formRow($form->get('text5'));?></td></tr>
 <tr><td><label>Slider Heading</label></td><td><?php echo $this->formRow($form->get('text6'));?></td></tr>
  <tr><td><label>Wall Header</label></td><td><?php echo $this->formRow($form->get('header'));?></td></tr>
 <tr><td><label>Wall Header Description</label></td><td><?php echo $this->formRow($form->get('hdescription'));?></td></tr>
 <tr><td><label>Image upload for Frontend:</label></td><td><?php echo $this->formRow($form->get('pname'));?></td></tr>
 
<tr><td><label>Previous Image</label><img src="<?php echo $content;?>" height="100" width="100" ></td><td> <?php
  echo $this->formSubmit($form->get('submit'));
 //echo $this->formCollection($form);
  echo $this->form()->closeTag();
 
?><?php echo $this->formRow($form->get('id')); ?></td></tr>

 </table>
</div>
</div>