<div class="site">
<div class="row">
<div class="col-lg-8 col-md-offset-2">
<div class="table_button">
<a href="<?php echo $this->url('application/default',array('controller'=>'Admin','action' =>'casestudies'));?>">Insert Slide</a>

<a href="<?php echo $this->url('application/default',array('controller'=>'Admin','action'=>'pagedetails'));?>">Back to page details</a>

</div>
 <table width="100%" cellspacing="0" cellpadding="0" border="0" class="table_wrap">
 <tr><th colspan="2">Show Case Studies</th></tr>
 

<?php 
foreach ($res as $a){
    
    $vediourl = $a->VedioPath;
    
    if (preg_match('%(?:youtube(?:-nocookie)?\.com/(?:[^/]+/.+/|(?:v|e(?:mbed)?)/|.*[?&]v=)|youtu\.be/)([^"&?/ ]{11})%i', $vediourl, $match)) {
    $video_id = $match[1];
    }
    //$vedioHeader= $a->vedioHeader;
//    if (preg_match('/watch/',$vediourl))
//    {
//    $vurl =  explode("=" ,  $vediourl);
//    $vtwo = $vurl[1];
//    $vone="http://www.youtube.com/v/";
//    $vthree = "?hl=en_US&amp";
//    $vfour='&#59';
//    $vfive="version=3";
//    $originalurl=$vone.$vtwo.$vthree.$vfour.$vfive;
//    //echo $originalurl;
//   }
//   elseif(preg_match('/embed/',$vediourl))
//    {
//      $vurl = explode('/', $vediourl);
//    $vtwo = $vurl[4];
//    $vone="http://www.youtube.com/v/";
//    $vthree = "?hl=en_US&amp";
//    $vfour='&#59';
//    $vfive="version=3";
//    $originalurl=$vone.$vtwo.$vthree.$vfour.$vfive;
//    //echo $originalurl;
//   
//   }
//   else {
//    
//    $r = explode('/', $vediourl);
//     $vtwo = $r[3];
//    $vone="http://www.youtube.com/v/";
//    $vthree = "?hl=en_US&amp";
//    $vfour='&#59';
//    $vfive="version=3";
//    $originalurl=$vone.$vtwo.$vthree.$vfour.$vfive;
//    
//    
//   }
//   
//   
   
    ?>
       <tr>
    <td>
  <!--  <video>
    <iframe width="420" height="315" src= frameborder="0" allowfullscreen></iframe>
    </video>-->
    <object width="200" height="180">
    <!-- See: value="http://.. -->
    <iframe width="200" height="180" src="https://www.youtube.com/embed/<?php echo $video_id; ?>" frameborder="0" allowfullscreen></iframe>  
    
    <param name="allowFullScreen" value="true"></param>
    <param name="allowscriptaccess" value="always"></param>

    <!-- See: src="http://.. -->
    <embed src="<?php echo $originalurl ; ?>" type="application/x-shockwave-flash" width="200" height="180" allowscriptaccess="always" allowfullscreen="true"></embed>
</object>
 </td>
 <td>
    <a class="table_btn" href="<?php echo $this->url('application/default',array('controller'=>'Admin','action' =>'casestudies','id' => $a->vedioId));?>">EDIT</a>
  
     <a class="table_btn" href="<?php echo $this->url('application/default',array('controller'=>'Admin','action' =>'deletecasestudies','id' => $a->vedioId));?>">DELETE</a>
     </td>
  </tr>
  
    <?php
    
}

?>
 </table>
  
 </div>
  </div>
   </div>
