<html>
	<strong>Bevestiging inschrijving student/programmeur</string>

(Subject/)Onderwerp: Bevestiging aanmelding Hackathon Den Bosch

Beste deelnemer, 

Bedankt voor je aanmelding voor de 1e Hackathon Den Bosch! We nemen je inschrijving in behandeling en zullen je op zo snel mogelijk nader informeren.  

We doen er alles aan om er een inspirerend en motiverend event van te maken. Ken je iemand met een business of IT achtergrond die ook geïnteresseerd zou kunnen zijn? We zijn nog steeds op zoek naar toffe, creatieve en enthousiaste developers! Blijf ondertussen op de hoogte van de laatste updates via Facebook of Twitter.

Heb je een vraag? Aarzel dan niet om contact op te nemen met onze supportdesk: support@hackathonmasters.com

Met vriendelijke groet, 

Team Hackathon Masters
</html>