<img src="https://test.scampaigns.com/img/divider.png" id="imgdragable" style="display: none;">
 
<img src="https://test.scampaigns.com/img/divider.png" id="imgdragable" style="display: none;">
 
<img src="https://test.scampaigns.com/img/divider.png" id="imgdragable" style="position: absolute; top: 1133px; display: none; left: 352px;">
 



<meta http-equiv="Content-Type" content="text/html; charset=utf-8">

<link rel="stylesheet" href="//test.scampaigns.com/user_template/753546c511c4a3105-Optinapp--mod-template/css/style.css">
<!--<link rel="stylesheet" href="http://localhost/zf_new/public/css/styles.css"/>
<link rel="stylesheet" href="http://localhost/zf_new/public/css/textarea.css"/>---->

<link rel="stylesheet" type="text/css" media="all" href="//test.scampaigns.com/user_template/753546c511c4a3105-Optinapp--mod-template/css/jui.checkboxes.css">

<!-- <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>
   <script src = "http://js.nicedit.com/nicEdit-latest.js"></script>--->
 

<!---<script type="text/javascript" src="http://localhost/zf_new/public/js/jquery.form.js"></script>
<script type="text/javascript" src="http://localhost/zf_new/public/js/style.js"></script>---->



(complete.php)
<div class="details-n-winn-wrapper">
<div class="SFPTWO_IMAGEEDIT"><img id="images1" src="//test.scampaigns.com/user_template/753546c511c4a3105-Optinapp--mod-template/img/top-img.jpg" alt=""><div class="setting-2" style="display: none;"><a title="Edit" class="edit disabled" href="javascript:void(0)"></a><a title="delete" class="delete disabled" href="javascript:void(0)"></a><input value="753546c511c4a3105-Optinapp--mod-template" id="hid" type="hidden"><input value="0" id="imgCount" type="hidden"></div><div class="setting-2" style="display: none;"><a title="Edit" class="edit disabled" href="javascript:void(0)"></a><a title="delete" class="delete disabled" href="javascript:void(0)"></a><input value="753546c511c4a3105-Optinapp--mod-template" id="hid" type="hidden"><input value="0" id="imgCount" type="hidden"></div><div class="setting-2" style="display: none;"><a title="Edit" class="edit" href="javascript:void(0)"></a><a title="delete" class="delete" href="javascript:void(0)"></a><input value="753546c511c4a3105-Optinapp--mod-template" id="hid" type="hidden"><input value="0" id="imgCount" type="hidden"></div></div> 
<div class="SFPTWO_IMAGEEDIT"><img id="images1" src="//test.scampaigns.com/user_template/753546c511c4a3105-Optinapp--mod-template/img/top-img.jpg" alt=""><div class="setting-2" style="display: none;"><a title="Edit" class="edit disabled" href="javascript:void(0)"></a><a title="delete" class="delete disabled" href="javascript:void(0)"></a><input value="753546c511c4a3105-Optinapp--mod-template" id="hid" type="hidden"><input value="0" id="imgCount" type="hidden"></div><div class="setting-2" style="display: none;"><a title="Edit" class="edit disabled" href="javascript:void(0)"></a><a title="delete" class="delete disabled" href="javascript:void(0)"></a><input value="753546c511c4a3105-Optinapp--mod-template" id="hid" type="hidden"><input value="0" id="imgCount" type="hidden"></div><div class="setting-2" style="display:none"><a title="Edit" class="edit" href="javascript:void(0)"></a><a title="delete" class="delete" href="javascript:void(0)"></a><input value="753546c511c4a3105-Optinapp--mod-template" id="hid" type="hidden"><input value="0" id="imgCount" type="hidden"></div></div>         
        
<div class="tool-tip SFPTWO_TEXTEDIT"><h2 class="textedit SFPTWO_TAGEDIT edit explicit_edit" contenteditable="false">Fill in your details and win! </h2><div class="setting-2" id="text" style="display: none;"><a title="delete" class="delete disabled" href="javascript:void(0)"></a></div><div class="setting-2" id="text" style="display: none;"><a title="delete" class="delete disabled" href="javascript:void(0)"></a></div><div class="setting-2" id="text" style="display:none"><a title="delete" class="delete" href="javascript:void(0)"></a></div></div>
<div class="form-container jui-checkboxes-container" id="checkboxesInit2">


<ul class="designelements clearfix" style="position:absolute;left:20%;">
 <li id="lilabelme" style="top: 132px; left: 122px; position: relative; display: none;"><a class="disabled" style="cursor: pointer;" onclick="chechTypeAndAdd(this.rel)" rel="checkbox" id="checkbox"><span>Checkbox</span><img src="https://test.scampaigns.com/formbuild/checkbox_icon.png" alt=""></a></li>
   
</ul>
<form id="editable" action="complete.php" class="SFPTWO_EDITFORM" style="margin-top:25px;">

 <img src="https://test.scampaigns.com/img/divider.png" id="imgdrag" style="position: relative; top: 132px; display: none;">


<ul style="" class="sortable-list ui-sortable ui-draggable">

	<li style="" class="dottedLi"><div id="labeledit" class="labeledit emaildrag"><p style="font-size: 19px;" id="pid_" class="opt explicit_edit" contenteditable="false">EmaiL adjkjhkjkjhkjhkjhkdress</p></div><input name="" type="text">
    <div class="setting-2 prevnext"><a title="delete" class="delete" href="javascript:void(0)"></a><input id="hid" type="hidden"><input value="0" id="imgCount" type="hidden"><a class="prev" href="#">Previous</a>&nbsp;<a class="next" href="#">After</a></div>
    <div class="setting-2 prevnext"><a title="delete" class="delete" href="javascript:void(0)"></a><input id="hid" type="hidden"><input value="0" id="imgCount" type="hidden"><a class="prev" href="#">Previous</a>&nbsp;<a class="next" href="#">After</a></div><div class="setting-2 prevnext"><a title="delete" class="delete" href="javascript:void(0)"></a><input id="hid" type="hidden"><input value="0" id="imgCount" type="hidden"><a class="prev" href="#">Previous</a>&nbsp;<a class="next" href="#">After</a></div><div class="setting-2 prevnext"><a title="delete" class="delete" href="javascript:void(0)"></a><input id="hid" type="hidden"><input value="0" id="imgCount" type="hidden"><a class="prev" href="#">Previous</a>&nbsp;<a class="next" href="#">After</a></div></li>
    

	<li style="position: relative; left: 0px; top: 0px;" class="dottedLi"><div id="diveditme" class="labeledit addmechk checkboxdrag"><p style="font-size: 19px;" id="pid_form" class="opt explicit_edit" contenteditable="false">What kind of campaigghfhfhfghhn are you Looking for? 
    </p></div><div class="checksboxes p_scents chkboxaddnow" id="checksboxes_form657"><div id="chkclone"><div for="p_scnts" class="jui-checkbox-row" id="jui-checkbox-rowform657"><span class="checkboxWrapper"><input value="1" name="name" type="checkbox"> </span> <p class="opt" id="1">option1</p> </div><div class="jui-checkbox-row"> <span class="checkboxWrapper"><input value="2" name="name" type="checkbox"></span> <p class="opt" id="2">option2</p> </div><div class="jui-checkbox-row"><span class="checkboxWrapper"><input value="3" name="name" type="checkbox"></span><p class="opt" id="3">option3</p></div></div><p id="mepp" class="pchkadd"></p></div> <div class="setting-2 prevnext"><a title="delete" class="delete" href="javascript:void(0)"></a><input id="hid" type="hidden"><input value="0" id="imgCount" type="hidden"><a class="prev" href="#">Previous</a>&nbsp;<a class="next" href="#">After</a></div><div class="setting-2 prevnext"><a title="delete" class="delete" href="javascript:void(0)"></a><input id="hid" type="hidden"><input value="0" id="imgCount" type="hidden"><a class="prev" href="#">Previous</a>&nbsp;<a class="next" href="#">After</a></div><div class="setting-2 prevnext"><a title="delete" class="delete" href="javascript:void(0)"></a><input id="hid" type="hidden"><input value="0" id="imgCount" type="hidden"><a class="prev" href="#">Previous</a>&nbsp;<a class="next" href="#">After</a></div><div class="setting-2 prevnext"><a title="delete" class="delete" href="javascript:void(0)"></a><input id="hid" type="hidden"><input value="0" id="imgCount" type="hidden"><a class="prev" href="#">Previous</a>&nbsp;<a class="next" href="#">After</a></div></li>
    

	 <li style="display: list-item;" class="">
    	<div class="setting-2 prevnext"><a title="delete" class="delete" href="javascript:void(0)"></a><input id="hid" type="hidden"><input value="0" id="imgCount" type="hidden"><a class="prev" href="#">Previous</a>&nbsp;<a class="next" href="#">After</a></div><div class="setting-2 prevnext"><a title="delete" class="delete" href="javascript:void(0)"></a><input id="hid" type="hidden"><input value="0" id="imgCount" type="hidden"><a class="prev" href="#">Previous</a>&nbsp;<a class="next" href="#">After</a></div></li><li class="dottedLi"><div id="diveditme" class="labeledit"><p id="pid_844" class="opt explicit_edit" contenteditable="false">Label</p><div><textarea id="editmetext" name=""></textarea></div></div><div class="setting-2 prevnext"><a title="delete" class="delete" href="javascript:void(0)"></a><input id="hid" type="hidden"><input value="0" id="imgCount" type="hidden"><a class="prev" href="#">Previous</a>&nbsp;<a class="next" href="#">After</a></div><div class="setting-2 prevnext"><a title="delete" class="delete" href="javascript:void(0)"></a><input id="hid" type="hidden"><input value="0" id="imgCount" type="hidden"><a class="prev" href="#">Previous</a>&nbsp;<a class="next" href="#">After</a></div><div class="setting-2 prevnext"><a title="delete" class="delete" href="javascript:void(0)"></a><input id="hid" type="hidden"><input value="0" id="imgCount" type="hidden"><a class="prev" href="#">Previous</a>&nbsp;<a class="next" href="#">After</a></div></li>
    <li style="" class="dottedLi"><div id="diveditme" class="labeledit"><p style="font-size: 19px;" id="pid_formmsg" class="opt explicit_edit" contenteditable="false">Your message</p><div><textarea id="editmetext" name=""></textarea></div></div><div class="setting-2 prevnext"><a title="delete" class="delete" href="javascript:void(0)"></a><input id="hid" type="hidden"><input value="0" id="imgCount" type="hidden"><a class="prev" href="#">Previous</a>&nbsp;<a class="next" href="#">After</a></div><div class="setting-2 prevnext"><a title="delete" class="delete" href="javascript:void(0)"></a><input id="hid" type="hidden"><input value="0" id="imgCount" type="hidden"><a class="prev" href="#">Previous</a>&nbsp;<a class="next" href="#">After</a></div><div class="setting-2 prevnext"><a title="delete" class="delete" href="javascript:void(0)"></a><input id="hid" type="hidden"><input value="0" id="imgCount" type="hidden"><a class="prev" href="#">Previous</a>&nbsp;<a class="next" href="#">After</a></div><div class="setting-2 prevnext"><a title="delete" class="delete" href="javascript:void(0)"></a><input id="hid" type="hidden"><input value="0" id="imgCount" type="hidden"><a class="prev" href="#">Previous</a>&nbsp;<a class="next" href="#">After</a></div></li>
	<li style=""><input class="inputdisabled" name="" value="Send" type="submit"><div class="setting-2 prevnext"><a title="delete" class="delete" href="javascript:void(0)"></a><input id="hid" type="hidden"><input value="0" id="imgCount" type="hidden"><a class="prev" href="#">Previous</a>&nbsp;<a class="next" href="#">After</a></div><div class="setting-2 prevnext"><a title="delete" class="delete" href="javascript:void(0)"></a><input id="hid" type="hidden"><input value="0" id="imgCount" type="hidden"><a class="prev" href="#">Previous</a>&nbsp;<a class="next" href="#">After</a></div><div class="setting-2 prevnext"><a title="delete" class="delete" href="javascript:void(0)"></a><input id="hid" type="hidden"><input value="0" id="imgCount" type="hidden"><a class="prev" href="#">Previous</a>&nbsp;<a class="next" href="#">After</a></div><div class="setting-2 prevnext"><a title="delete" class="delete" href="javascript:void(0)"></a><input id="hid" type="hidden"><input value="0" id="imgCount" type="hidden"><a class="prev" href="#">Previous</a>&nbsp;<a class="next" href="#">After</a></div></li><li style="display: list-item;" class="">
    	<div class="setting-2 prevnext"><a title="delete" class="delete" href="javascript:void(0)"></a><input id="hid" type="hidden"><input value="0" id="imgCount" type="hidden"><a class="prev" href="#">Previous</a>&nbsp;<a class="next" href="#">After</a></div><div class="setting-2 prevnext"><a title="delete" class="delete" href="javascript:void(0)"></a><input id="hid" type="hidden"><input value="0" id="imgCount" type="hidden"><a class="prev" href="#">Previous</a>&nbsp;<a class="next" href="#">After</a></div></li><li class="dottedLi"><div id="diveditme" class="labeledit editmyoptme"><p id="pid_564" class="opt explicit_edit" contenteditable="false">Label</p><div><textarea id="editmetext" name=""></textarea></div></div><div class="setting-2 prevnext"><a title="delete" class="delete" href="javascript:void(0)"></a><input id="hid" type="hidden"><input value="0" id="imgCount" type="hidden"><a class="prev" href="#">Previous</a>&nbsp;<a class="next" href="#">After</a></div><div class="setting-2 prevnext"><a title="delete" class="delete" href="javascript:void(0)"></a><input id="hid" type="hidden"><input value="0" id="imgCount" type="hidden"><a class="prev" href="#">Previous</a>&nbsp;<a class="next" href="#">After</a></div><div class="setting-2 prevnext"><a title="delete" class="delete" href="javascript:void(0)"></a><input id="hid" type="hidden"><input value="0" id="imgCount" type="hidden"><a class="prev" href="#">Previous</a>&nbsp;<a class="next" href="#">After</a></div></li>
    

<li class="dottedLi"><div id="labeledit" class="labeledit editmyoptme editlabelme"><p id="pid_929" class="opt explicit_edit" contenteditable="false">Ladfdfdddfddfdfdfdfdfbel<a style="cursor: pointer;" onclick="chechTypeAndAdd(this.rel)" rel="textbox" id="textbox"><img src="https://test.scampaigns.com/formbuild/inputfield_icon.png" alt=""></a><a style="cursor: pointer;" onclick="chechTypeAndAdd(this.rel)" rel="textbox" id="textbox"><img src="https://test.scampaigns.com/formbuild/inputfield_icon.png" alt=""></a></p></div><div class="checksboxes p_scents chkboxaddnow" id="checksboxes_852"><div id="chkclone"><div for="p_scnts" class="jui-checkbox-row" id="jui-checkbox-row852"><span class="checkboxWrapper"><input value="1" name="name" type="checkbox"> </span> <p class="opt" id="1">option1</p> </div><div class="jui-checkbox-row"> <span class="checkboxWrapper"><input value="2" name="name" type="checkbox"></span> <p class="opt" id="2">option2</p> </div><div class="jui-checkbox-row"><span class="checkboxWrapper"><input value="3" name="name" type="checkbox"></span><p class="opt" id="3">option3</p></div></div><p id="mepp" class="pchkadd"></p></div> <div class="setting-2 prevnext"><a title="delete" class="delete" href="javascript:void(0)"></a><input id="hid" type="hidden"><input value="0" id="imgCount" type="hidden"><a class="prev" href="#">Previous</a>&nbsp;<a class="next" href="#">After</a></div></li><li class="dottedLi ui-draggable"><div id="labeledit" class="labeledit addmechk checkboxdrag"><p id="pid_811" class="opt explicit_edit" contenteditable="false">Label</p></div><div class="checksboxes p_scents chkboxaddnow editmyopt adding" id="checksboxes_335"><div id="chkclone"><div for="p_scnts" class="jui-checkbox-row" id="jui-checkbox-row335"><span class="checkboxWrapper"><input value="1" name="name" type="checkbox"> </span> <p class="opt" id="1">option1</p> </div><div class="jui-checkbox-row"> <span class="checkboxWrapper"><input value="2" name="name" type="checkbox"></span> <p class="opt" id="2">option2</p> </div><div class="jui-checkbox-row"><span class="checkboxWrapper"><input value="3" name="name" type="checkbox"></span><p class="opt" id="3">option3</p></div></div><p id="mepp" class="pchkadd"></p></div> <div class="setting-2 prevnext"><a title="delete" class="delete" href="javascript:void(0)"></a><input id="hid" type="hidden"><input value="0" id="imgCount" type="hidden"><a class="prev" href="#">Previous</a>&nbsp;<a class="next" href="#">After</a></div></li></ul>
<div class="setting-2" style="display:none"><a title="setup" class="setup" href="javascript:void(0)"></a><a title="delete" class="delete" href="javascript:void(0)"></a><input value="753546c511c4a3105-Optinapp--mod-template" id="hid" type="hidden"></div><div class="setting-2" style="display:none"><a title="setup" class="setup" href="javascript:void(0)"></a><a title="delete" class="delete" href="javascript:void(0)"></a><input value="753546c511c4a3105-Optinapp--mod-template" id="hid" type="hidden"></div><div class="setting-2" style="display:none"><a title="setup" class="setup" href="javascript:void(0)"></a><a title="delete" class="delete" href="javascript:void(0)"></a><input value="753546c511c4a3105-Optinapp--mod-template" id="hid" type="hidden"></div></form>[(complete.php)]
</div>
</div>