<!----------- added by Poulami ----------->
<div class="site">
<div class="container-fluid">
<div class="row"><p id="fly-it" class="top_heading col-md-12 center">Upload File</p></div>
<div class="col-lg-8 col-md-offset-2 dev-form dev-form2">
<?php 

$uform = $this->uform;
$uform->setAttribute('action', $this->url('application/default', array('controller'=>'template','action' => 'addTemplate')));
$uform->prepare();

?>

<!-- T?o th? <form...> và các giá tr? thu?c tính c?a th? này -->
<?php echo $this->form()->openTag($uform);?>

<ul class="col-lg-12">
<li>
<?php echo $this->formHidden($uform->get('devId'));?>
</li>
<li>
<?php echo $this->formRow($uform->get('templateName'));?>
</li>
<li>
      <!--In ra giá tr? nhãn  -->
      <span><?php echo '<br />'; echo $this->formLabel($uform->get('file')); ?></span>
      
      <!--T?o ph?n t? HTML cho vi?c Upload -->
      <?php echo $this->formElement($uform->get('file')); ?>
   </li>
<li>
      <!--In ra giá tr? nhãn  -->
      <span><?php echo '<br />'; echo $this->formLabel($uform->get('scImage')); ?></span>
      
      <!--T?o ph?n t? HTML cho vi?c Upload -->
      <?php echo $this->formElement($uform->get('scImage')); ?>
   </li>
<li>
      <!--T?o nút Submit -->
      <?php echo $this->formElement($uform->get('submit'));?>
   </li>
</ul>
<!-- Ðóng th? </form>
-->
<?php echo $this->form()->closeTag() ?>
</div>
</div>
</div>
