 
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>SFPv2 Smartfanpage | SUCCESS</title>
<link rel="shortcut icon" type="image/x-icon" href="<?php echo $this->basePath('img/favicon.ico') ?>" />

<link rel="stylesheet" href="/editcss/publish.css" />
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
</head>

<body>


	<div class="popup_new">

		<h2>Publish</h2>

		<div class="clearfix"></div>

		<div class="tab">
			<!--<ul class="nav nav-pills nav-wizard">
        <li class="active"><a href="index.html">step 1) - preview</a><div class="nav-arrow"></div></li>
        <li><div class="nav-wedge"></div><a href="platform.html">Step 2) - Platforms</a><div class="nav-arrow"></div></li>
        <li><div class="nav-wedge"></div><a href="payment.html">step 3) - Payment</a><div class="nav-arrow"></div></li>
        <li><div class="nav-wedge"></div><a href="publish.html">step 4) - publish</a><div class="nav-arrow"></div></li>
    </ul>-->
			<div id="tab1" class="tab_content">
				<div>
					<p>SORRY YOUR TRANSACTION IS CANCELLED</p>
				</div>
				<a href="<?php echo $this->url('application/default'); ?>" class="close_bottom" title="Close">Close</a>
			</div>
			<!-- end of tab1/tab_content -->
		</div>
	</div>
	<!-- end of popup_new -->
</body>
</html>
