<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>SFPv2 Smartfanpage | SUCCESS</title>
<link rel="shortcut icon" type="image/x-icon" href="<?php echo $this->basePath('img/favicon.ico') ?>" />

<link rel="stylesheet" href="/editcss/publish.css" />
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
<script type="text/javascript" src="/js3/success.js"></script>

</head>

<body>

<input id="tempName" value='<?php echo $tempName;?>' type="hidden"/>
<input id="camName" value='<?php echo $camName;?>' type="hidden"/>
<input id="fbNo" value='<?php echo $fbNo;?>' type="hidden"/>
<input id="fbPageId" value='<?php echo $fbPageId;?>' type="hidden"/>
<input id="fbPageAccessToken" value='<?php echo $pageAccessToken;?>' type="hidden"/>

	<div class="popup_new">

		<h2>Publish</h2>

		<div class="clearfix"></div>

		<div class="tab">
			<!--<ul class="nav nav-pills nav-wizard">
        <li class="active"><a href="index.html">step 1) - preview</a><div class="nav-arrow"></div></li>
        <li><div class="nav-wedge"></div><a href="platform.html">Step 2) - Platforms</a><div class="nav-arrow"></div></li>
        <li><div class="nav-wedge"></div><a href="payment.html">step 3) - Payment</a><div class="nav-arrow"></div></li>
        <li><div class="nav-wedge"></div><a href="publish.html">step 4) - publish</a><div class="nav-arrow"></div></li>
    </ul>-->
			<div id="tab1" class="tab_content">
				<div>
					<ul class="link_all">
						<li><h3>Yesss, you're done!</h3></li>
						<li id="webLView"><strong>Your WEB link is (smartlink):</strong> <a id="webLinkView" target="_blank" href="<?php echo $webUrl;?>"><?php echo $webUrl;?></a>
						</li>
						<li id="fbLView"><strong>Your Facebook link is:</strong> <a id="fbLinkView" target="_blank" ><?php echo $fbUrlD;?></a>
						</li>
					</ul>
					<hr />
					<ul class="link_all">
						<li><h3>Start promoting your campaign</h3></li>
						<li><strong>Share on:</strong>
						</li>
					</ul>
					<ul class="blog_icon_all">
						<li><a href="https://www.facebook.com/" target="_blank"
							title="Facebook" class="facebook">facebook</a></li>
						<!--<li><a href="http://instagram.com/" target="_blank" title="Instagram" class="instagram">instagram</a></li> -->
						<li><a href="https://twitter.com/" target="_blank" title="Twitter"
							class="twitter">twitter</a></li>
						<li><a href="https://www.linkedin.com/" target="_blank"
							title="Linkedin" class="linkedin">linkedin</a></li>
						<!--<li><a href="https://www.pinterest.com/" target="_blank" title="Pinterest" class="pinterest">pinterest</a></li> -->
					</ul>
				</div>
				<a href="<?php echo $this->url('application/default'); ?>" class="close_bottom" title="Close">Close</a>
			</div>
			<!-- end of tab1/tab_content -->
		</div>
	</div>
	<!-- end of popup_new -->
</body>
</html>
