<?php 
function curPageURL() 
{
    $pageURL = 'http';
    if (@$_SERVER["HTTPS"] == "on") {$pageURL .= "s";}
    $pageURL .= "://";
    if ($_SERVER["SERVER_PORT"] != "80") 
    {
        if($_SERVER["REQUEST_URI"] == "/")
            $pageURL .= $_SERVER["SERVER_NAME"].":".$_SERVER["SERVER_PORT"].'/index/index';
        else
            $pageURL .= $_SERVER["SERVER_NAME"].":".$_SERVER["SERVER_PORT"].$_SERVER["REQUEST_URI"];
    } else 
    {
        if($_SERVER["REQUEST_URI"] == "/")
            $pageURL .= $_SERVER["SERVER_NAME"].'/index/index';
        else
            $pageURL .= $_SERVER["SERVER_NAME"].$_SERVER["REQUEST_URI"];
    }
    return $pageURL;
}
$href = explode("/", curPageURL());
$pageB4 = @$href[3];
$page = @$href[4];



?>
<?php echo $this->doctype(); ?>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />    
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="shortcut icon" type="image/x-icon" href="<?php echo $this->basePath('img/favicon.ico') ?>" />
    <?php echo $this->headTitle('SFPv2 '. $this->translate('Smartfanpage | Home'))->setSeparator(' - ')->setAutoEscape(false) ?>
    
    <?php include_once('js.phtml') ?>
    <?php include 'css.phtml'; ?>
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    
</head>
<body>
    <?php if(($pageB4 == 'index') && ($page == 'index') ){ 
        include 'facebook.php';  } ?>
    <!--//========for mobile social icons===========-->
    <div class="mobile-social">
        <a href="#" class="button"></a>
        <ul class="social_icon3">
            <li><a href="#"></a> <a href="#"></a> <a href="#"></a></li>
        </ul>
    </div>
    <!--//========End for mobile social icons===========-->
    <!--===== start menu ===-->
    <div class="mobile_menu">
        <div class="logo-cont"> <a href="<?php echo $this->url('home') ?>" class="logo"></a> </div>
        <a href="#" class="menu-trigger navicon "><span>Open menu</span></a> 
    </div>
    
    <!--===== end menu ===-->
    
    <!--===== body start ===-->
    
    <?php echo $this->content; ?>
    <?php if(($page == 'becomepublisher') && ($pageB4 != 'Admin')){ ?>
    
    <!--===================================tab html end=================================-->
    
    <!--<a class="prev-button" href="#">Previous step</a>-->
        <a href="#" class="submit-button">Let's do it</a>
        <div style="position:relative;"><hr/> <a href="#" class="go_to_up" id="back-to-top"></a></div> <!--=== sign up section ===--> </div>
        </div>
    <?php } 
    ?> 
    
  
    <?php echo $this->inlineScript() ?>
    
    
    
</body>
</html>
