<?php 
if(($page == 'index') || ($page == 'store'))
{ 
    echo $this->headScript()
            ->prependFile($this->basePath() . '/js/main.js',   'text/javascript')
            ->prependFile($this->basePath() . '/js/onload.js',   'text/javascript')
            ->prependFile($this->basePath() . '/js/jquery_004.js',   'text/javascript')
            ->prependFile($this->basePath() . '/js/jquery.responsiveTabs.js',   'text/javascript')
            ->prependFile($this->basePath() . '/js/owl.carousel.js',   'text/javascript')
            ->prependFile($this->basePath() . '/js/jquery.selectBox.js', 'text/javascript')
            ->prependFile($this->basePath() . '/js/jquery.fittext.js')
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery-1.10.1.min.js'); 
            
} 
elseif($page == 'howswork') 
{
    echo $this->headScript()
            ->prependFile($this->basePath() . '/js/main.js',   'text/javascript')
            ->prependFile($this->basePath() . '/js/onload.js',   'text/javascript')
            ->prependFile($this->basePath() . '/js/jquery_004.js',   'text/javascript')
            ->prependFile($this->basePath() . '/js/jquery.responsiveTabs.js',   'text/javascript')
            ->prependFile($this->basePath() . '/js/jquery.selectBox.js', 'text/javascript')
            ->prependFile($this->basePath() . '/js/jquery.fittext.js')
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery-1.10.1.min.js');
    
}
else
{
    echo $this->headScript()
            
            ->prependFile($this->basePath() . '/js/template.js',   'text/javascript')
            ->prependFile($this->basePath() . '/js/jquery.nice-file-input.min.js',   'text/javascript')
            ->prependFile($this->basePath() . '/js/main.js',   'text/javascript')
            ->prependFile($this->basePath() . '/js/onload.js',   'text/javascript')
            ->prependFile($this->basePath() . '/js/jquery_004.js',   'text/javascript')
            ->prependFile($this->basePath() . '/js/jquery.responsiveTabs.js',   'text/javascript')
            ->prependFile($this->basePath() . '/js/owl.carousel.js',   'text/javascript')
            ->prependFile($this->basePath() . '/js/jquery.selectBox.js', 'text/javascript')
            ->prependFile($this->basePath() . '/js/jquery.fittext.js')
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery-1.10.1.min.js');
}
?>