<?php 

function curPageURL() 
{
    $pageURL = 'http';
    if (@$_SERVER["HTTPS"] == "on") {$pageURL .= "s";}
    $pageURL .= "://";
    if ($_SERVER["SERVER_PORT"] != "80") 
    {
        if($_SERVER["REQUEST_URI"] == "/")
            $pageURL .= $_SERVER["SERVER_NAME"].":".$_SERVER["SERVER_PORT"].'/index/index';
        elseif($_SERVER["REQUEST_URI"] == "/index")
            $pageURL .= $_SERVER["SERVER_NAME"].":".$_SERVER["SERVER_PORT"].'/index/index';
        else
            $pageURL .= $_SERVER["SERVER_NAME"].":".$_SERVER["SERVER_PORT"].$_SERVER["REQUEST_URI"];
    } else 
    {
        if($_SERVER["REQUEST_URI"] == "/")
            $pageURL .= $_SERVER["SERVER_NAME"].'/index/index';
        elseif($_SERVER["REQUEST_URI"] == "/index")
            $pageURL .= $_SERVER["SERVER_NAME"].'/index/index';
        else
            $pageURL .= $_SERVER["SERVER_NAME"].$_SERVER["REQUEST_URI"];
    }
    return $pageURL;
}


$href = explode("/", curPageURL());
 $pageB4 = @$href[3];

 $page = @$href[4];


?>
<?php echo $this->doctype(); ?>
<html lang="en"><head>
    <meta charset="utf-8"/>
    <!--[if IE]><meta http-equiv='X-UA-Compatible' content='IE=edge,chrome=1'><![endif]-->
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="shortcut icon" type="image/x-icon" href="<?php echo $this->basePath('img/favicon.ico') ?>" />
    <?php echo $this->headTitle('SFPv2 '. $this->translate('Smartfanpage | Home'))->setSeparator(' - ')->setAutoEscape(false) ?>
    
    
    <?php include 'css.phtml'; ?>
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    
</head>
<body>

 
    <?php if(($pageB4 == 'index') && ($page == 'index') ){ 
       
        include 'facebook.php';  } ?>
    <!--//========for mobile social icons===========-->
    <div class="mobile-social">
        <a href="javascript:void(0)" class="button"></a>
        <ul class="social_icon3">
            <li><a href="javascript:void(0)"></a> <a href="javascript:void(0)"></a> <a href="javascript:void(0)"></a></li>
        </ul>
    </div>
    <!--//========End for mobile social icons===========-->
    <!--===== start menu ===-->
    <div class="mobile_menu">
  
        <div class="logo-cont"> <a href="<?php echo $this->url('home') ?>" class="logo"></a> </div>
        <a href="#" class="menu-trigger navicon "><span>Open menu</span></a> 
    </div>
  
    <?= $this->render('layout/sitemap1.phtml') ?>
    <?= $this->render('layout/mob-sitemap.phtml') ?>
    <!--===== end menu ===-->
    
    <!--===== body start ===-->
    
    <?php echo $this->content; ?>
    <?php if(($page == 'becomepublisher') && ($pageB4 != 'Admin')){ ?>
    
    <!--===================================tab html end=================================-->
    
    <!--<a class="prev-button" href="#">Previous step</a>-->
        <a href="#" class="submit-button">Let's do it</a>
        <div style="position:relative;"><hr/> <a href="#" class="go_to_up" id="back-to-top"></a></div> <!--=== sign up section ===--> </div>
        </div>
    <?php } else { if($pageB4 != 'Admin'){
    ?> 
    <div class="clearfix"></div>
        <hr/>
        <div class="row row_text">
        <div class="col-lg-12">
        <h4>Sign up now, it's free!</h4>
        <p class="row">You can have a 14 days free trial to convince yourself and experience<br>
        the power of Smartfanpage. What are you waiting for?</p>
        <!--<a href="javascript:void(0)" class="sign_up">Sign up free</a>-->
        <a class="sign_up" onclick="logInWithYourFaceBookAccount()" href="javascript:void(0)">Sign up free</a>
        </div>
        </div>
        <div style="position:relative;">
        <hr/>
        <a href="#" class="go_to_up" id="back-to-top"></a></div>
        </div>
        </div><!--===== body_container end ===--> 
        </div> <!--===== main_container end ===--> 
    <?php } } ?>
    <?php echo $this->inlineScript() ?>
    <?php include_once('js.phtml') ?>
    
    
</body>
</html>
