<?php
 $protocol = '';
        if (isset($_SERVER['HTTPS']) &&
       ($_SERVER['HTTPS'] == 'on' || $_SERVER['HTTPS'] == 1) ||
        isset($_SERVER['HTTP_X_FORWARDED_PROTO']) &&
        $_SERVER['HTTP_X_FORWARDED_PROTO'] == 'https') {
         $protocol = 'https://';
        }
        else {
        $protocol = 'http://';
           }
       // echo $_SERVER['SERVER_PROTOCOL'].$_SERVER['HTTP_HOST'].$_SERVER['REQUEST_URI'];
        $url = $protocol.$_SERVER["SERVER_NAME"];
?>

<aside class="mobile container-fluid">
  <nav id="menu1"> <!--<strong class="button"><b>&nbsp;</b></strong>--> <a href="#" class="small_logo"><img src="<?php echo $this->basePath('img/small_logo.png') ?>" alt="" /></a> <a href="<?php echo $this->url('home') ?>" class="big_logo"><img src="<?php echo $this->basePath('img/big_logo.png') ?>" alt="" /></a>
    <div class="download"><img src="<?php echo $this->basePath('img/download.png') ?>" alt="" /></div>
   <!-- <div class="logout"> <img src="<?php echo $this->basePath('img/logout.png') ?>" alt="" />
      <p><a>Studio 365</a>Amsterdam</p>
       </div>-->
    
    <?php
      if($uname != "")
      {
      ?>
      <div class="logout"><a title="Log Out" class="lgot" style="cursor: pointer;" id="logout"><img src="<?php echo $this->basePath('img/logout.png') ?>" alt="" /></a>
        <p><a> <?php
            echo $uname;
        ?></a><?php  if($city == "undefined"){echo "";}else{
            echo $city;
        } ?></p>
       <!---<span>67%</span>---></div>
      <!--<span class="rate"> <img src="<?php //echo $this->basePath('img/rate.png') ?>" alt="" /> <img src="<?php //echo $this->basePath('img/rate.png') ?>" alt="" /> <img src="<?php //echo $this->basePath('img/rate.png') ?>" alt="" /> <img src="<?php// echo $this->basePath('img/unrate.png') ?>" alt="" /> <img src="<?php //echo $this->basePath('img/unrate.png') ?>" alt="" /> </span>---->
      <?php
      }
      else
      {
        ?>
      <div class="login"><a class="login-bt" href="<?php echo $url; ?>/index/accountsignin">sign in</a></div>
      <?php
      }
      ?>
   
    <ul class="nav drop_nav" id="nav1">
    
    <li><a href="<?php echo $this->url('home') ?>"><img src="<?php echo $this->basePath('img/icon1.png') ?>" alt="" /><span>Home</span></a></li>
       
        <li><a href="<?=$this->url('application/default', array('controller' => 'index', 'action' => 'store')); ?>"><img src="<?php echo $this->basePath('img/icon2.png') ?>" alt="" /><span>Template store</span></a></li>
       <!--</a> <li><a href="<?=$this->url('application/default', array('controller' => 'index', 'action' => 'howswork')); ?>"><img src="<?php echo $this->basePath('img/icon3.png') ?>" alt="" /><span>How does it work?</span></a></li>-->
        <li><a href="<?=$this->url('application/default', array('controller' => 'index', 'action' => 'becomepublisher')); ?>"><img src="<?php echo $this->basePath('img/icon4.png') ?>" alt="" /><span>Connected developers</span></a></li>
       <!--- <li><a href="<? /*echo  $this->url('application/default', array('controller' => 'index', 'action' => 'casestudies')); */ ?>"><img src="<?php /* echo $this->basePath('img/icon5.png') */ ?>" alt="" /><span>Case Studies</span></a></li>--->
        <li><a href="<?=$this->url('application/default', array('controller' => 'index', 'action' => 'faq')); ?>"><img src="<?php echo $this->basePath('img/icon6.png') ?>" alt="" /><span>FAQ</span></a></li>
        <li><a href="<?=$this->url('application/default', array('controller' => 'index', 'action' => 'aboutus')); ?>"><img src="<?php echo $this->basePath('img/icon7.png') ?>" alt="" /><span>About us</span></a></li>
        <li><span></span></li>
        
         <li><a href="<?=$this->url('application/default', array('controller' => 'index', 'action' => 'blogoverview')); ?>" ><img src="<?php echo $this->basePath('img/icon8.png') ?>" alt="" /><span>Blog</span></a></li>
         <!---<img src="<?php //echo $this->basePath('img/nav_arrow.png') ?>" alt="" class="arrow"/><img src="<?php// echo $this->basePath('img/nav_arrow2.png') ?>" alt="" class="arrow2"/>---->
          <!---<div> <a href="<?//=$this->url('application/default', array('controller' => 'index', 'action' => 'blogarchive')); ?>">BLOG ARCHIVE</a> <a href="<?//=$this->url('application/default', array('controller' => 'index', 'action' => 'blogoverview')); ?>">BLOG OVERVIEW</a> <a href="<?//=$this->url('application/default', array('controller' => 'index', 'action' => 'blogdetails')); ?>">BLOG DETAILS</a> </div>--->
        
        
        
        <li><a href="<?=$this->url('application/default', array('controller' => 'index', 'action' => 'contact')); ?>"><img src="<?php echo $this->basePath('img/icon9.png') ?>" alt="" /><span>Contact</span></a></li>
    </ul>
    <form action="/" method="post" name="search" class="search">
      <input type="text" name="search" value="" />
    </form>
    <div class="new-dev-section clearfix">
<div class="dev-title-bar">
For Developers
</div>
<ul>
	<li><a href="<?=$this->url('application/default', array('controller' => 'index', 'action' => 'documentation')); ?>"><img src="../img/dev-api.png" alt=""><span>Developer's API</span></a></li>
	<li><a href="<?php echo $url; ?>/sfpdeveloper/index"><img src="../img/dev-img-2.png" alt=""><span>Developer Login</span></a></li>
    <li><a href="<?=$this->url('application/default', array('controller' => 'index', 'action' => 'termscondition')); ?>"><img src="../img/dev-img-3.png" alt=""><span>Terms & Service</span></a></li>
    <li><a href="<?=$this->url('application/default', array('controller' => '', 'action' => 'Disclaimer')); ?>"><img src="../img/dev-img-4.png" alt=""><span>Disclaimer</span></a></li>
    <li><a href="<?=$this->url('application/default', array('controller' => 'index', 'action' => 'privacypolicy')); ?>"><img src="../img/dev-img-5.png" alt=""><span>Privacy Policy</span></a></li>
</ul>
</div>
    <p class="copyright">&copy; Copyright 2013 <a href="#">Smart Fanpage</a></p>
  </nav>
</aside>