
    
    <div class="row">
        <div class="col-lg-8 col-md-offset-2">           
            <div class="table_button">
                <a href="<?php echo $this->url('application/default',array('controller'=>'Admin','action'=>'detailscountry'));?>">Back To Country List</a>
        
            </div>
            <form method="post" action="insertcountry"  name="upload" >
            <table width="100%" border="0" cellspacing="0" cellpadding="0" class="table_wrap sam">
                <tr>
                    <th colspan="4">ADD Company</th>
                </tr>
                <tr>
                    <td><label>Enter Country Name</label></td>
                    <td><input type="text" name="countryname" class ="txtInput txtMedium" /></td>
                </tr>             
               
                    <tr>
                        <td></td>
                        <td><input type="submit" value="Add Country" name="appsubmit" class ="save_btn"  /></td>
                    </tr>
            </table>
            </form>
        </div>
    </div>
