<div class="site">
<div class="row">
<div class="col-lg-8 col-md-offset-2">
<?php 
$form = $this->form;
$form->setAttribute('action', $this->url('application/default', array('controller'=>'admin','action' => 'blogoverview','id'=>$id)));
$form->prepare();
echo $this->form()->openTag($form);
?>
<div class="table_button">
    <a href="<?php echo $this->url('application/default',array('controller'=>'Admin','action'=>'pagedetails'));?>">Back page details</a>
    <a href="<?php echo $this->url('application/default',array('controller'=>'Admin','action'=>'showblogoverview'));?>">Blog list</a>
    <table width="100%" cellspacing="0" cellpadding="0" border="0" class="table_wrap">
    <tr>
        <th colspan="2">BLOG</th>
    </tr>
     <tr>
        <td><label>TOPIC</label></td>
        <td><?php echo $this->formElement($form->get('question'));?></td>
     </tr>
      <tr>
        <td><label>ANSWER</label></td>
        <td><?php echo $this->formElement($form->get('answer'));?></td>
      </tr>
      <tr>
        <td><label>Link Creator</label></td>
        <td><?php echo $this->formElement($form->get('linkCreator'));?></td>
      </tr>
      <tr>
        <td><label>Tag Insert</label></td>
        <td><?php echo $this->formElement($form->get('tagInsert'));?></td>
      </tr>
      <tr>
        <td><label>Meta Title</label></td>
        <td><?php echo $this->formElement($form->get('metaTitle'));?></td>
      </tr>
      <tr>
        <td><label>Meta Keyword</label></td>
        <td><?php echo $this->formElement($form->get('metaKeyword'));?></td>
      </tr>
      <tr>
        <td><label>Meta Description</label></td>
        <td><?php echo $this->formElement($form->get('metaDescription'));?></td>
      </tr>     
      <tr>
        <td><label>Previous Main Image</label></td<td><img src="<?php echo $imagePath;?>" height="100" width="100" /></td>
    </tr>
      <tr>
        <td><label>Cover picture</label></td>
        <td><?php echo $this->formElement($form->get('picture'));?></td>
      </tr>  
      <tr>
        <td>&nbsp;</td>
        <td><?php echo $this->formElement($form->get('submit'));?></td>
      </tr>
</table>
</div>
<?php
if ($this->flashMessenger()->hasMessages())
{
   echo '<div direction="left" class="alert alert-info" id="contenterrorDiv">';
   $messages = $this->flashMessenger()->getMessages();
   foreach($messages as $message) {echo $message;}
   echo '</div>';
}
?> 
</div>
<?php echo $this->form()->closeTag() ?>
<script>
                // Replace the <textarea id="editor1"> with a CKEditor
                // instance, using default configuration.
                CKEDITOR.replace( 'bodyen' );
                function editor(){
                var body = CKEDITOR.instances['bodyen'].getData();
                alert(body);
                }
            </script>