<div class="site">
<div class="row">
<div class="col-lg-8 col-md-offset-2">
<?php 
$form = $this->form;
$form->prepare();
?>
<?php echo $this->form()->openTag($form);?>
<div class="table_button">
    <a href="<?php echo $this->url('application/default',array('controller'=>'Admin','action'=>'pagedetails'));?>">Back page details</a>
    <a href="<?php echo $this->url('application/default',array('controller'=>'Admin','action'=>'showblogoverview'));?>">Blog list</a>
<table width="100%" cellspacing="0" cellpadding="0" border="0" class="table_wrap">
    <tr>
        <th colspan="2">BLOG</th>
    </tr>
     <tr>
        <td><label>TOPIC</label></td>
        <td><?php echo $this->formElement($form->get('question'));?></td>
     </tr>
     <tr>
        <td><label>ANSWER</label></td>
        <td><?php echo $this->formElement($form->get('answer'));?></td>
     </tr>
      <tr>
        <td><label>Link Creator</label></td>
        <td><div class="form_tags"><?php echo $this->formElement($form->get('linkCreator'));?></div></td>    
      </tr>
      <tr>
        <td><label>Tag Insert</label></td>
        <td><?php echo $this->formElement($form->get('tagInsert'));?></td>
      </tr>
      <tr>
        <td><label>Meta Title</label></td>
        <td><?php echo $this->formElement($form->get('metaTitle'));?></td>
      </tr>
      <tr>
        <td><label>Meta Keyword</label></td>
        <td><?php echo $this->formElement($form->get('metaKeyword'));?></td>
      </tr>
      <tr>
        <td><label>Meta Description</label></td>
        <td><?php echo $this->formElement($form->get('metaDescription'));?></td>
      </tr>
      <tr>
        <td><label>Cover picture</label></td>
        <td><?php echo $this->formElement($form->get('picture'));?></td>
      </tr>  
      <tr>
        <td>&nbsp;</td>
        <td><?php echo $this->formElement($form->get('submit'));?></td>
      </tr>
</table>
<div id="contenterrorDiv" class="alert-info" style="display: none;">
</div>
<input type="text" id="blank" value="<?php echo $blank;?>" style="display: none;" />
<input type="text" id="exist" value="<?php echo $exist;?>" style="display: none;" />
<input type="text" id="specialCharacter" value="<?php echo $specialCharacter;?>" style="display: none;" />
<input type="text" id="image" value="<?php echo $image;?>" style="display: none;" />
</div>
</div>
<?php echo $this->form()->closeTag() ?>
<script>
CKEDITOR.replace( 'bodyen' );
</script>
