<div class="site">
<div class="row">
<div class="col-lg-8 col-md-offset-2">
<?php  
    $form = $this->form;
    $form->setAttribute('action', $this->url('application/default', array('controller'=>'Admin','action' => 'updateblogoverviewheader','id'=>$id)));
    $form->prepare();
    echo $this->form()->openTag($form);
    echo $this->formRow($form->get('id'));
?>
<div class="table_button">
    <a href="<?php echo $this->url('application/default',array('controller'=>'Admin','action'=>'pagedetails'));?>">Back to page details</a>
    <a href="<?php echo $this->url('application/default',array('controller'=>'Admin','action'=>'showblogoverview'));?>">Back</a>
</div>
<table width="100%" cellspacing="0" cellpadding="0" border="0" class="table_wrap">
    <tr>
        <th colspan="2">Edit BLOG HEADER</th>
    </tr>
    <tr>
        <td><label>BANNER HEADER</label></td>
        <td><?php echo $this->formRow($form->get('headerLine'));?></td>
    </tr>
    <tr>
        <td><label>Image upload for Frontend:</label></td>
        <td><?php  echo $this->formRow($form->get('picture'));?></td>
    </tr>
    <tr>
        <td><label>Previous Image</label><img src="<?php echo $content;?>" height="100" width="100" /></td>
        <td><?php echo $this->formSubmit($form->get('submit'));?></td>
    </tr>
</table>
<?php echo $this->form()->closeTag();?>
</div>
</div>
