<div class="site">
<div class="row">
<div class="col-lg-8 col-md-offset-2">
<?php 
$form = $this->form;
$form->setAttribute('action', $this->url('application/default', array('controller'=>'admin','action' => 'casestudies','id'=>$id)));
$form->prepare();
echo $this->form()->openTag($form);?>
<div class="table_button">
<a href="<?php echo $this->url('application/default',array('controller'=>'Admin','action'=>'pagedetails'));?>">Back to page details</a>
<a href="<?php echo $this->url('application/default',array('controller'=>'Admin','action'=>'showcasestudies'));?>">Back</a>
<table width="100%" cellspacing="0" cellpadding="0" border="0" class="table_wrap">
  <tr>
      <th colspan="2">Insert Case Studies</th>
  </tr>
  <tr>
      <td><?php echo $this->formLabel($form->get('vedioHeader')); ?></td>
      <td><?php echo $this->formElement($form->get('vedioHeader'));?></td>
  </tr>
  <tr>
      <td><?php echo $this->formLabel($form->get('VedioDescription')); ?></td>
      <td><?php echo $this->formElement($form->get('VedioDescription'));?></td>
  </tr>
  <tr>
      <td><?php echo $this->formLabel($form->get('VedioPath')); ?></td>
      <td><?php echo $this->formElement($form->get('VedioPath'));?></td>
  </tr>
  
  <tr>
      <td><?php echo $this->formLabel($form->get('picture')); ?></td>
      <td><?php echo $this->formElement($form->get('picture')); ?></td>
  </tr>
<?php if($content!=""){?>
  <tr>
      <td><label>Previous Image</label><img src="<?php echo $content;?>" height="100" width="100" ></td>
  </tr>
<?php } ?>
  <tr>
      <td></td>
      <td><?php echo $this->formElement($form->get('submit'));?></td>
  </tr>
</table>
</div>
</div>
<?php echo $this->form()->closeTag() ?>