<div class="site">
&nbsp;&nbsp;<a href="<?php echo $this->url('application/default',array('controller'=>'admin','action'=>'logout'));?>">LOGOUT</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
<a href="<?php echo $this->url('application/default',array('controller'=>'admin','action'=>'pagedetails'));?>">pagedetails</a>
<div class="row">
<div class="col-lg-8 col-md-offset-2">
    <table class="table">
    <tr>
        <th>id</th>
        <th>First Name</th>
        <th>Last Name</th>
        <th>Email</th>
        <th>Action</th>
    </tr>
<?php 
foreach ($developers as $developer) : 
    if($developer->disableDeveloper == 0)
    {
?>
    <tr id="row<?php echo $developer->id; ?> ">
        <td><?php echo $this->escapeHtml($developer->id);?></td>
        <td><?php echo $this->escapeHtml($developer->fName);?></td>
        <td><?php echo $this->escapeHtml($developer->lName);?></td>
        <td><?php echo $this->escapeHtml($developer->eId);?></td>
        <td><a href="<?php echo $this->url('application/default',array('controller'=>'admin','action'=>'devtemplate','id'=>$developer->id));?>">Go</a><p></p></td> 
        <td><a href="javascript:void(0)" id="deldev">Delete</a><p><input type="hidden" id="hiddendev" value="<?php echo $developer->id; ?>" /></p></td> 
    </tr>
<?php 
    } 
endforeach; 
?>
    </table>
</div>
</div>