<div class="site">

<a href="<?php echo $this->url('application/default',array('controller'=>'admin','action'=>'logout'));?>">LOGOUT</a>

<div class="row">
<div class="col-lg-8 col-md-offset-2">
<table class="table">
<tr>
    <th>id</th>
    <th>First Name</th>
   <th>Last Name</th>
   <th>Email</th>
   <th>Action</th>
</tr>

<?php foreach ($developers as $developer) : ?>
<tr>
    <td><?php echo $this->escapeHtml($developer->id);?></td>
    <td><?php echo $this->escapeHtml($developer->fName);?></td>
    <td><?php echo $this->escapeHtml($developer->lName);?></td>
    <td><?php echo $this->escapeHtml($developer->eId);?></td>
    <td><a href="<?php echo $this->url('application/default',array('controller'=>'admin','action'=>'devtemplate','id'=>$developer->id));?>">Go</a><p></p></td> 
    
    
  
</tr>
<?php endforeach; ?>
</table>
</div>
</div>