<div class="site">
    <div class="site">
        <a style="cursor: pointer;" class="goback" href="/Admin/devdetails">Go Back</a>
            <div class="container-fluid">
                <div class="row"><p id="fly-it" class="top_heading col-md-12 center">Template</p></div>
                <div class="col-md-8 col-md-offset-2 dev-form clearfix">
                    <div class="dashboard-wrap col-lg-12">
                        <?php foreach ($temp as $template)
                        { 
                        ?>
                            <div class="dashboard col-lg-12">
                            <p><?php echo $template['template_name'];?></p>
                                <div class="dash-img-holder col-lg-4"> 
                                    <img src='<?php echo $this->basePath('files/'.$template['template_name']."/".$template['tempalte_img']);?>' style="height: 100px; width: 200px;"/>
                                </div>
                                <div class="button-wrapper col-lg-8">
                                    <a href="<?php echo $this->url('application/default',array('controller'=>'Admin','action' =>'tempfile','id'=>$template['template_name'],'devId'=>$template['devId']));?>">Go</a>
                                    <?php
                                    if($template['approval']=="")
                                    {
                                    ?>
                                        Pending for Approval
                                    <?php
                                    }
                                    else if($template['approval']=="1")
                                    {       
                                    ?>
                                        Approved
                                    <?php
                                    }
                                    else if($template['approval']=="0")
                                    {       
                                    ?>
                                        Rejected
                                    <?php
                                    }
                                    ?>
                                </div>
                            </div>
                  <?php } ?>
                </div>
                <a href="<?php echo $this->url('application/default',array('controller'=>'admin','action'=>'devdetails'));?>">Back</a>
            </div>
        </div>
    </div>