<div class="site">
    <div class="container-fluid">
        <div class="row">
            <p id="fly-it" class="top_heading col-md-12 center">Admin Login</p>
        </div>
        <div class="col-md-6 col-md-offset-3 dev-form clearfix">
            <?php $form->setAttribute('action', $this->url('application/default', array('controller'=>'admin','action' => 'login'))); $form->prepare(); echo $this->form()->openTag($form);?>
            <li>
                <?php echo $this->formRow($form->get('uname'));?>
            </li>
            <li>
                <?php echo $this->formRow($form->get('pwd'));?>
            </li>
            <li>
                <?php echo $this->formElement($form->get('submit'));?>
            </li>
            <?php echo $this->form()->closeTag(); ?>
        </div>
    </div>