<?php $con = count($content);?>
<div class="site">
    <div class="row">
        <div class="col-lg-8 col-md-offset-2">
            <div class="table_button">
                <a href="<?php echo $this->url('application/default',array('controller'=>'admin','action'=>'logout'));?>">Logout</a>
                <a href="<?php echo $this->url('application/default',array('controller'=>'admin','action'=>'devdetails'));?>">Developer</a>
                <a href="<?php echo $this->url('application/default',array('controller'=>'admin','action'=>'managecamp'));?>">Manage Campaign</a>
            </div>
            <table width="100%" border="0" cellspacing="0" cellpadding="0" class="table_wrap">
                <tr>
                    <th>Campaign Name</th>
                    <th>Developer</th>
                    <th>Action</th>
                </tr>
            <?php
                for($i=0;$i<$con;$i++)
                {
                  $newrs = explode("/",$content[$i]);
                    if($newrs[0] == "0")
                   {
            ?>
                <tr>
                      <td><?php echo $newrs[1]; ?></td>
                      <td><?php echo $newrs[2]; ?></td>
                      <td id="tab<?php echo $newrs[3]; ?>"><input type="button" id="blocker<?php echo $newrs[3]; ?>" value="block" onclick="unblocker(<?php echo $newrs[3]; ?>)" /></td>  
                </tr>
            <?php
                  }
                  else
                  {
            ?>
                <tr>
                    <td><?php echo $newrs[1]; ?></td>
                    <td><?php echo $newrs[2]; ?></td>
                    <td id="tab<?php echo $newrs[3]; ?>"><input type="button" id="blocker<?php echo $newrs[3]; ?>" value="unblock" onclick="return blocker(<?php echo $newrs[3]; ?>)"/></td>  
                </tr>
            <?php    
                 }
             }
            ?>
        </table>
      </div>
</div>