<div class="site">
    <div class="row">
        <div class="col-lg-8 col-md-offset-2">
            <div class="table_button">
                <a href="<?php echo $this->url('application/default',array('controller'=>'Admin','action' =>'becomepublisher'));?>">Insert Slide </a>
                <a href="<?php echo $this->url('application/default',array('controller'=>'Admin','action' =>'becomepublisherbanner','id'=>'1'));?>">Edit Banner </a>
                <!-- <a href="<?php echo $this->url('application/default',array('controller'=>'Admin','action' =>'showbecomepublisherstudio'));?>">Edit Studio Image </a>--->
                <a href="<?php echo $this->url('application/default',array('controller'=>'Admin','action'=>'pagedetails'));?>">Back to page details</a>
            </div>
            <table width="100%" cellspacing="0" cellpadding="0" border="0" class="table_wrap">
                <tr>
                    <th colspan="2">Become Publisher</th>
                </tr>
                <?php foreach ($res as $a){ $imgurl=$a->picPath; ?>
                <tr>
                    <td><img src="<?php echo $imgurl; ?>" style="width: 100px;height:100px;" /></td>
                    <td><a class="table_btn" href="<?php echo $this->url('application/default',array('controller'=>'Admin','action' =>'becomepublisherview','id' => $a->picId));?>">Edit</a>
                        <a class="table_btn" onclick="if(!confirm('Are you want to delete'))return false;" href="<?php echo $this->url('application/default',array('controller'=>'Admin','action' =>'deletebecomepublisher','id' => $a->picId));?>">Delete</a></td>
                </tr>
                <?php } ?>
            </table>
        </div>
    </div>
</div>