<div class="site">
    <div class="row">
        <div class="col-lg-8 col-md-offset-2">
            <div class="table_button">
                <a href="<?php echo $this->url('application/default',array('controller'=>'Admin','action'=>'pagedetails'));?>">Back to page details</a>
                <a href="<?php echo $this->url('application/default',array('controller'=>'Admin','action'=>'tempedit','id'=>2));?>">Back</a>
                <table width="100%" border="0" cellspacing="0" cellpadding="0" class="table_wrap">
                    <tr>
                        <th colspan="3">Edit Image</th>
                    </tr>
                    <?php foreach ($res as $a){ echo "<tr>"; $imgurl=$a->imgPath; if($a->imgid==1) { echo "<td>"."3rd image"; } else { echo "<td>"."4th image"; } ?>
                            <td><img src="<?php echo $imgurl; ?>" style="width:100px; height:100px;" /></td>
                            <td><a class="table_btn" href="<?php echo $this->url('application/default',array('controller'=>'Admin','action' =>'addtemplateimages','id' => $a->imgid));?>">Edit</a></td>
                    <?php } echo "</tr>"; ?>
                </table>
            </div>
        </div>
    </div>