<div class="site">
    <div class="row">
        <div class="col-lg-8 col-md-offset-2">
            <div class="table_button">
                <a href="<?php echo $this->url('application/default',array('controller'=>'Admin','action' =>'templatecatagory'));?>">Insert Catagory</a>
                <a href="<?php echo $this->url('application/default',array('controller'=>'Admin','action'=>'pagedetails'));?>">Back to page details</a>
            </div>
            <h2 style="text-align: left; margin: 20px 0 0 0; color:#2e3641;">Privacy And Policy</h2>
            <table width="100%" cellspacing="0" cellpadding="0" border="0" class="table_wrap">
                <tr>
                    <th colspan="2">Catagory</th>
                    </th>
                </tr>
                <?php foreach ($res as $a){?>
                <tr>
                    <td>
                        <?php echo $a->catagory;?>
                    
                       
                    </td>
                    <td>
                        <a class="table_btn" href="<?php echo $this->url('application/default',array('controller'=>'Admin','action' =>'templatecatagoryview','id' => $a->id));?>">EDIT</a>
                        <a class="table_btn" onclick="if(!confirm('Are you want to delete'))return false;" href="<?php echo $this->url('application/default',array('controller'=>'Admin','action' =>'deletetemplatecatagory','id' => $a->id));?>">DELETE</a>
                    </td>
                </tr>
                <?php } ?>
            </table>
        </div>
    </div>
</div>