<div class="site">
    <div class="row">
        <div class="col-lg-8 col-md-offset-2">
            <div class="table_button">
                <a href="<?php echo $this->url('application/default',array('controller'=>'Admin','action' =>'blogoverview'));?>">Insert More</a>
                <a href="<?php echo $this->url('application/default',array('controller'=>'Admin','action'=>'pagedetails'));?>">Back to page details</a>
                <a href="<?php echo $this->url('application/default',array('controller'=>'Admin','action'=>'blogoverviewheader'));?>">Edit the banner</a>
            </div>
            <table width="76%" cellspacing="0" cellpadding="0" border="0" class="table_wrap">
                <tr>
                    <th colspan="2">BLOG POST </th>
                </tr>
                <?php foreach ($res as $listing) : ?>
                <tr>
                    <td width="420"><?php $date=$listing->date; $details = date("l, F j, Y", strtotime($date) ); echo substr( $listing->question,0,40);echo "...";echo "<h3 class='datevalue'>"."DATE: ".$details."</h3>";?></td>
                    <td><a class="table_btn" href="<?php echo $this->url('application/default',array('controller'=>'Admin','action' =>'blogoverviewview','id' => $listing->id));?>">edit</a><a class="table_btn" onclick="if(!confirm('Are you want to delete'))return false;" href="<?php echo $this->url('application/default',array('controller'=>'Admin','action' =>'deleteblogoverview','id' => $listing->id));?>">Delete</a></td>
                </tr>
                <?php endforeach; ?>
            </table>
        </div>
    </div>

