<div class="site">
    <div class="row"> 
        <div class="col-lg-8 col-md-offset-2">
            <div class="table_button">
                <!--  <a href="<?php echo $this->url('application/default',array('controller'=>'Admin','action' =>'animation'));?>"> Insert Application Image</a>-->
                <a href="<?php echo $this->url('application/default',array('controller'=>'Admin','action'=>'pagedetails'));?>">Back to page details</a>
                <a href="<?php echo $this->url('application/default',array('controller'=>'Admin','action'=>'edit','id'=>1));?>">Back</a>
       
            </div>
            <table width="100%" cellspacing="0" cellpadding="0" border="0" class="table_wrap">
                <tr>
                    <th colspan="3"> Images</th>
                </tr>
                <?php foreach ($res as $a){ $imgurl=$a->imagePath; $id = $a->imageId; ?>
                <tr>
                    <td><img src="<?php echo $imgurl; ?>" style="width: 100px;height:100px;" /></td>
                    <td><?php if($id == 7) echo 'Animated Image'; else  echo 'App Image';?></td>
                    <td><a class="table_btn" href="<?php echo $this->url('application/default',array('controller'=>'Admin','action' =>'updateanimatedimage','id' => $a->imageId));?>">edit </a><!--<a class="table_btn" onclick="if(!confirm('Are you want to delete'))return false;" href="<?php echo $this->url('application/default',array('controller'=>'Admin','action' =>'deleteanimatedimage','id' => $a->imageId));?>">Delete</a>--></td>
                </tr>
        </div>
        <?php } ?>
        </table>
    </div>



