<div class="site">
    <?php $form=$this->form; $form->setAttribute('action', $this->url('application/default', array('controller'=>'admin','action' => 'slideadd','id'=>$id))); $form->prepare(); ?>
    <div class="row">
        <div class="col-lg-8 col-md-offset-2">
            <?php echo $this->form()->openTag($form);?>
            <div class="table_button">
                <a href="<?php echo $this->url('application/default',array('controller'=>'Admin','action'=>'pagedetails'));?>">Back to page details</a>
                <a href="<?php echo $this->url('application/default',array('controller'=>'Admin','action'=>'show'));?>">View Community</a>

                <table width="100%" border="0" cellspacing="0" cellpadding="0" class="table_wrap">
                    <tr>
                        <th colspan="2">Add Slider</th>
                    </tr>
                    <tr>
                        <td><?php echo $this->formLabel($form->get('Title')); ?></td>
                        <td><?php echo $this->formElement($form->get('Title'));?></td>
                    </tr>
                    
                    <tr>
                        <td><?php echo $this->formLabel($form->get('imageLink')); ?></td>
                        <td><?php echo $this->formElement($form->get('imageLink'));?></td>
                    </tr>
                    <tr>
                        <td><?php echo $this->formLabel($form->get('picture')); ?></td>
                        <td><?php echo $this->formElement($form->get('picture')); ?></td>
                    </tr>
                    <tr>
                        <td><label>Previous Image</label><img src="<?php echo $content;?>" height="100" width="100"/></td>
                    </tr>
                    <tr>
                        <td></td>
                        <td><?php echo $this->formElement($form->get('submit'));?></td>
                    </tr>
                </table>
            </div>
        </div>
<?php echo $this->form()->closeTag() ?>