<div class="site">
    <div class="row">
        <div class="col-lg-8 col-md-offset-2">
            <?php $form=$this->form; $form->setAttribute('action', $this->url('application/default', array('controller'=>'Admin','action' => 'updatevaluetemp','id'=>$id))); $form->prepare(); echo $this->form()->openTag($form); echo $this->formRow($form->get('id')); ?>
            <div class="table_button"><a href="<?php echo $this->url('application/default',array('controller'=>'Admin','action'=>'showtemplateimages'));?>">Image section</a>
                <a href="<?php echo $this->url('application/default',array('controller'=>'Admin','action'=>'pagedetails'));?>">Back to page details</a>
            </div>
            <table width="100%" border="0" cellspacing="0" cellpadding="0" class="table_wrap">
                <tr>
                    <th colspan="2">Template Page Edit</th>
                </tr>
                <tr>
                    <td>
                        <label>Banner Header</label>
                    </td>
                    <td><?php echo $this->formRow($form->get('BannerHeader'));?></td>
                </tr>
                <tr>
                    <td>
                        <label>Banner Desc</label>
                    </td>
                    <td><?php echo $this->formRow($form->get('BannerDesc'));?></td>
                </tr>
                <tr>
                    <td>
                        <label>campaign ques</label>
                    </td>
                    <td><?php echo $this->formRow($form->get('campaignques'));?></td>
                </tr>
                <tr>
                    <td>
                        <label>campaign heading</label>
                    </td>
                    <td><?php echo $this->formRow($form->get('campaignheading'));?></td>
                </tr>
                <tr>
                    <td>
                        <label>campaign subhead</label>
                    </td>
                    <td><?php echo $this->formRow($form->get('campaignsubhead'));?></td>
                </tr>
                <tr>
                    <td>
                        <label>campaign desc</label>
                    </td>
                    <td><?php echo $this->formRow($form->get('campaigndesc'));?></td>
                </tr>
                <tr>
                    <td>
                        <label>campaign Image</label>
                    </td>
                    <td><?php echo $this->formRow($form->get('campaignlink'));?></td>
                </tr>
                <tr>
                    <td>
                        <label>Previous campaign Image </label><img src="<?php echo $clink;?>" height="100" width="100"/>
                    </td>
                    <td>
                        <tr>
                            <td>
                                <label>Image upload for Frontend:</label>
                            </td>
                            <td><?php echo $this->formRow($form->get('pname'));?></td>
                        </tr>
                        <?php echo $this->formRow($form->get('id')); ?></td>
                </tr>
                <tr>
                    <td>
                        <label>Previous Frontend Image</label><img src="<?php echo $content;?>" height="100" width="100"/>
                    </td>
                    <td>
                        <?php echo $this->formSubmit($form->get('submit')); echo $this->form()->closeTag(); ?>
                    </td>
                </tr>
            </table>
        </div>
    </div>


 