<!DOCTYPE html>
<head>
    <div class="site">
        &nbsp;&nbsp;<a style="cursor: pointer;" onclick="goBack()">Go Back</a>
        <div class="showfile col-lg-12">
            <?php $parts=Explode( '///', $editor); $comma_separated=implode( "/", $parts); ?>
            <div class="col-lg-2 col-md-offset-8 browseopen">
                <a href="<?php echo $this->url('application/default',array('controller'=>'Admin','action' => 'tempapprove','id'=>$temp_name,'pId'=>$devId));?>">Approve</a>
                <a href="<?php echo $this->url('application/default',array('controller'=>'Admin','action' => 'tempreject','id'=>$temp_name,'pId'=>$devId));?>">Reject</a>
            </div>
            <div class="fileopen col-lg-8 col-md-offset-2">
                <?php echo $editor?>
            </div>
        </div>
 

