<!DOCTYPE html>
<head>
<script>
 
function requestUrlWithAjax(url)
{
    //alert(url);
    var xmlhttp;
 
    //1. create the xmlhttp object
 
    if (window.XMLHttpRequest)
    {// code for IE7+, Firefox, Chrome, Opera, Safari
        xmlhttp=new XMLHttpRequest();
    }
    else
    {// code for IE6, IE5
        xmlhttp=new ActiveXObject("Microsoft.XMLHTTP");
    }
 
    //2. assign the handler for the onchange event of the object
    xmlhttp.onreadystatechange=function()
    {
        if (xmlhttp.readyState==4 && xmlhttp.status==200)
        {
            // we arrive here when we have successfully retrieved  the url we asked for
            //1. Set the response text to the text area's value
            //document.getElementById('ajaxResultTarget').html =  url;
             var NWin = window.open((url), '', 'height=400,width=500');
         if (window.focus) 
        {
        NWin.focus();
        }
        return false;
            //2. copy the name of the file retrieved directly above the text-area
         //var iFrame = $('#ajaxResultTarget');
        // iFrame.load(xmlhttp.responseText);
            
            
            // $('#textvalurl').val(url);
            //3. set the filename to the hidden input - see line 199
//          document.getElementById('frmFileName').value = url;

 
            //4. scroll the document down to editingFilename - just above the text-area
           // var xPos, yPos, tgtElem;
          //  tgtElem = document.getElementById('editingFilename');
          //  xPos = 0;
          //  yPos = tgtElem.offsetTop;
          //  window.scrollTo(xPos, yPos);
        }
    }
 
    //3. specify a GET request for the indicated filename,
    //   set asynchronous to true (dont wait for the send method to complete before continuing)
    xmlhttp.open("GET",url,true);
 
    //4. make the request
    xmlhttp.send();
}
 
</script>

<div class="site">
<div class="showfile col-lg-12">
<?php

$parts = Explode('///', $editor);
  $comma_separated = implode("/", $parts);
   
?>
<div class="col-lg-2 col-md-offset-8 browseopen">
<a href="<?php echo $this->url('application/default',array('controller'=>'Admin','action' => 'tempapprove','id'=>$temp_name,'devId'=>$devId));?>">Approve</a>
<a href="<?php echo $this->url('application/default',array('controller'=>'Admin','action' => 'tempreject','id'=>$temp_name,'devId'=>$devId));?>">Reject</a>
</div>
<div class="fileopen col-lg-8 col-md-offset-2">
<?php echo $editor?>
</div> 
</div>
 

