<div class="site">
    <?php $form=$this->form; $form->setAttribute('action', $this->url('application/default', array('controller'=>'admin','action' => 'walloffame','id'=>$id))); $form->prepare(); ?>
    <div class="row">
        <div class="col-lg-8 col-md-offset-2">
            <?php echo $this->form()->openTag($form);?>
            <div class="table_button">
                <a href="<?php echo $this->url('application/default',array('controller'=>'Admin','action'=>'pagedetails'));?>">Back to page details</a>
                <a href="<?php echo $this->url('application/default',array('controller'=>'Admin','action'=>'showwalloffame'));?>">Back</a>
            </div>
            <table width="100%" border="0" cellspacing="0" cellpadding="0" class="table_wrap sam">
                <tr>
                    <th colspan="4">Wall of Fame Image Upload</th>
                </tr>
                <tr>
                    <td><?php echo $this->formLabel($form->get('picture')); ?></td>
                    <td><?php echo $this->formElement($form->get('picture')); ?></td>
                </tr>
                <tr>
                    <td>
                        <label>Previous Image:</label>
                    </td>
                    <td><img src="<?php echo $piclink;?>" height="100" width="100"/></td>
                </tr>
                <tr>
                    <td>
                        <label>Picture Name</label>
                    </td>
                    <td><?php echo $this->formElement($form->get('pname')); ?></td>
                    <tr>
                        <tr>
                    <td>
                        <label>Picture description</label>
                    </td>
                    <td><?php echo $this->formElement($form->get('description')); ?></td>
                    <tr>
                    
                        <td></td>
                        <td><?php echo $this->formElement($form->get('submit'));?></td>
                    </tr>
            </table>
        </div>
    </div>
<?php echo $this->form()->closeTag() ?>