<div  class="site">
  <div class="container-fluid"> 
   <!--===== start banner ===-->
    <div class="row">
      <div class="store_banner">
        <ul class="social_icon">
          <li><a href="#">Share this website</a></li>
          <li><a href="#"></a> <a href="#"></a> <a href="#"></a></li>
        </ul>
        <div class="clearfix"></div>
        <div class="banner_caption col-md-8 t-store" >
          <h1 class="fittext2">Template store</h1>
          <h2>Find and customize the most challenging<br>
            and effective online campaign templates</h2>
          <a href="#">Sign up free</a> </div>
      </div>
      
    </div>
    <!--===== end banner ===--> 
    <div class="container-fluid store-wrapper" > 
      
     <!--===== start dropdown ===-->
      <div class="row" >
        <p class="top_heading col-md-12" id="fly-it">What kind of campaign are you looking for?</p>
        <div class="col-md-3 col-xs-12" >
          <select id="standard-dropdown" name="standard-dropdown" class="custom-class1 custom-class2">
            <option value="1" class="test-class-1">Keyword</option>
            <option value="1" class="test-class-1">dfgsdfgsdgfd</option>
            <option value="1" class="test-class-1">Select category</option>
          </select>
        </div>
        <div class="col-md-3 col-xs-12">
          <select id="standard-dropdown" name="standard-dropdown" class="custom-class1 custom-class2">
            <option value="1" class="test-class-1">Select category</option>
            <option value="1" class="test-class-1">dfgsdfgsdgfd</option>
            <option value="1" class="test-class-1">Publishing platform</option>
          </select>
        </div>
        <div class="col-md-3 col-xs-12">
          <select id="standard-dropdown" name="standard-dropdown" class="custom-class1 custom-class2">
            <option value="1" class="test-class-1">Publishing platform</option>
            <option value="1" class="test-class-1">dfgsdfgsdgfd</option>
            <option value="1" class="test-class-1">Price</option>
          </select>
        </div>
        
        
        
        
        
        <!--<form class="navbar-form col-md-2 col-xs-12">
            <input type="text" placeholder="Search..." class="form-control">
          </form>-->
      <!--  <div class="col-md-2 col-xs-12"><a href="#" class="discover_button">Discover</a></div>-->
        <div class="col-md-1 col-xs-12 pull-right"><a href="#" class="refresh_button"></a></div>
        <div class="col-md-3 col-xs-12 pull-right">
         
          
          <div class="input-group cust-search">
            <input class="form-control" placeholder="Search" name="srch-term" id="srch-term" type="text">
            <div class="input-group-btn">
              <button class="btn btn-default" type="submit"><span class="glyphicon glyphicon-search"></span></button>
            </div>
          </div>
        
         
        </div>
       <!-- <div class="col-md-2 col-xs-12"><a href="#" class="see_all">No filter
          see all</a></div>-->
      </div>
      <!--===== end dropdown ===--> 
      <!--===== start first caraousal ===-->
      
      <div class="row">
        <hr>
          
         <div class="row store-margin">
         <div class="col-lg-12">
         <ul class="slider">
    	<li class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
        	<strong>Blog competition</strong>
            <span><img src="<?php echo $this->basePath('img/slider_img.jpg') ?>" alt="" /></span>
            <div>
            	<p>Blog / Creative / Writing /  Facebook app</p>
                <strong>Author: Studio 365 (Amsterdam)</strong>
                <span>
                    <img src="<?php echo $this->basePath('img/rate.png') ?>" alt="" />
                    <img src="<?php echo $this->basePath('img/rate.png') ?>" alt="" />
                    <img src="<?php echo $this->basePath('img/rate.png') ?>" alt="" />
                    <img src="<?php echo $this->basePath('img/unrate2.png') ?>" alt="" />
                    <img src="<?php echo $this->basePath('img/unrate2.png') ?>" alt="" />
                </span>
                <a href="#">Start right away!</a>
                <b>€19</b>
            </div>
        </li>
        <li class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
        	<strong>Blog competition</strong>
            <span><img src="<?php echo $this->basePath('img/slider_img.jpg') ?>" alt="" /></span>
            <div>
            	<p>Blog / Creative / Writing /  Facebook app</p>
                <strong>Author: Studio 365 (Amsterdam)</strong>
                <span>
                    <img src="<?php echo $this->basePath('img/rate.png') ?>" alt="" />
                    <img src="<?php echo $this->basePath('img/rate.png') ?>" alt="" />
                    <img src="<?php echo $this->basePath('img/rate.png') ?>" alt="" />
                    <img src="<?php echo $this->basePath('img/unrate2.png') ?>" alt="" />
                    <img src="<?php echo $this->basePath('img/unrate2.png') ?>" alt="" />
                </span>
                <a href="#">Start right away!</a>
                <b>€19</b>
            </div>
        </li>
        <li class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
        	<strong>Blog competition</strong>
            <span><img src="<?php echo $this->basePath('img/slider_img.jpg') ?>" alt="" /></span>
            <div>
            	<p>Blog / Creative / Writing /  Facebook app</p>
                <strong>Author: Studio 365 (Amsterdam)</strong>
                <span>
                    <img src="<?php echo $this->basePath('img/rate.png') ?>" alt="" />
                    <img src="<?php echo $this->basePath('img/rate.png') ?>" alt="" />
                    <img src="<?php echo $this->basePath('img/rate.png') ?>" alt="" />
                    <img src="<?php echo $this->basePath('img/unrate2.png') ?>" alt="" />
                    <img src="<?php echo $this->basePath('img/unrate2.png') ?>" alt="" />
                </span>
                <a href="#">Start right away!</a>
                <b>€19</b>
            </div>
        </li>
        <li class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
        	<strong>Blog competition</strong>
            <span><img src="<?php echo $this->basePath('img/slider_img.jpg') ?>" alt="" /></span>
            <div>
            	<p>Blog / Creative / Writing /  Facebook app</p>
                <strong>Author: Studio 365 (Amsterdam)</strong>
                <span>
                    <img src="<?php echo $this->basePath('img/rate.png') ?>" alt="" />
                    <img src="<?php echo $this->basePath('img/rate.png') ?>" alt="" />
                    <img src="<?php echo $this->basePath('img/rate.png') ?>" alt="" />
                    <img src="<?php echo $this->basePath('img/unrate2.png') ?>" alt="" />
                    <img src="<?php echo $this->basePath('img/unrate2.png') ?>" alt="" />
                </span>
                <a href="#">Start right away!</a>
                <b>€19</b>
            </div>
        </li>
        
        <li class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
        	<strong>Blog competition</strong>
            <span><img src="<?php echo $this->basePath('img/slider_img.jpg') ?>" alt="" /></span>
            <div>
            	<p>Blog / Creative / Writing /  Facebook app</p>
                <strong>Author: Studio 365 (Amsterdam)</strong>
                <span>
                    <img src="<?php echo $this->basePath('img/rate.png') ?>" alt="" />
                    <img src="<?php echo $this->basePath('img/rate.png') ?>" alt="" />
                    <img src="<?php echo $this->basePath('img/rate.png') ?>" alt="" />
                    <img src="<?php echo $this->basePath('img/unrate2.png') ?>" alt="" />
                    <img src="<?php echo $this->basePath('img/unrate2.png') ?>" alt="" />
                </span>
                <a href="#">Start right away!</a>
                <b>€19</b>
            </div>
        </li>
        <li class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
        	<strong>Blog competition</strong>
            <span><img src="<?php echo $this->basePath('img/slider_img.jpg') ?>" alt="" /></span>
            <div>
            	<p>Blog / Creative / Writing /  Facebook app</p>
                <strong>Author: Studio 365 (Amsterdam)</strong>
                <span>
                    <img src="<?php echo $this->basePath('img/rate.png') ?>" alt="" />
                    <img src="<?php echo $this->basePath('img/rate.png') ?>" alt="" />
                    <img src="<?php echo $this->basePath('img/rate.png') ?>" alt="" />
                    <img src="<?php echo $this->basePath('img/unrate2.png') ?>" alt="" />
                    <img src="<?php echo $this->basePath('img/unrate2.png') ?>" alt="" />
                </span>
                <a href="#">Start right away!</a>
                <b>€19</b>
            </div>
        </li>
        <li class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
        	<strong>Blog competition</strong>
            <span><img src="<?php echo $this->basePath('img/slider_img.jpg') ?>" alt="" /></span>
            <div>
            	<p>Blog / Creative / Writing /  Facebook app</p>
                <strong>Author: Studio 365 (Amsterdam)</strong>
                <span>
                    <img src="<?php echo $this->basePath('img/rate.png') ?>" alt="" />
                    <img src="<?php echo $this->basePath('img/rate.png') ?>" alt="" />
                    <img src="<?php echo $this->basePath('img/rate.png') ?>" alt="" />
                    <img src="<?php echo $this->basePath('img/unrate2.png') ?>" alt="" />
                    <img src="<?php echo $this->basePath('img/unrate2.png') ?>" alt="" />
                </span>
                <a href="#">Start right away!</a>
                <b>€19</b>
            </div>
        </li>
        <li class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
        	<strong>Blog competition</strong>
            <span><img src="<?php echo $this->basePath('img/slider_img.jpg') ?>" alt="" /></span>
            <div>
            	<p>Blog / Creative / Writing /  Facebook app</p>
                <strong>Author: Studio 365 (Amsterdam)</strong>
                <span>
                    <img src="<?php echo $this->basePath('img/rate.png') ?>" alt="" />
                    <img src="<?php echo $this->basePath('img/rate.png') ?>" alt="" />
                    <img src="<?php echo $this->basePath('img/rate.png') ?>" alt="" />
                    <img src="<?php echo $this->basePath('img/unrate2.png') ?>" alt="" />
                    <img src="<?php echo $this->basePath('img/unrate2.png') ?>" alt="" />
                </span>
                <a href="#">Start right away!</a>
                <b>€19</b>
            </div>
        </li>
        
        <li class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
        	<strong>Blog competition</strong>
            <span><img src="<?php echo $this->basePath('img/slider_img.jpg') ?>" alt="" /></span>
            <div>
            	<p>Blog / Creative / Writing /  Facebook app</p>
                <strong>Author: Studio 365 (Amsterdam)</strong>
                <span>
                    <img src="<?php echo $this->basePath('img/rate.png') ?>" alt="" />
                    <img src="<?php echo $this->basePath('img/rate.png') ?>" alt="" />
                    <img src="<?php echo $this->basePath('img/rate.png') ?>" alt="" />
                    <img src="<?php echo $this->basePath('img/unrate2.png') ?>" alt="" />
                    <img src="<?php echo $this->basePath('img/unrate2.png') ?>" alt="" />
                </span>
                <a href="#">Start right away!</a>
                <b>€19</b>
            </div>
        </li>
        <li class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
        	<strong>Blog competition</strong>
            <span><img src="<?php echo $this->basePath('img/slider_img.jpg') ?>" alt="" /></span>
            <div>
            	<p>Blog / Creative / Writing /  Facebook app</p>
                <strong>Author: Studio 365 (Amsterdam)</strong>
                <span>
                    <img src="<?php echo $this->basePath('img/rate.png') ?>" alt="" />
                    <img src="<?php echo $this->basePath('img/rate.png') ?>" alt="" />
                    <img src="<?php echo $this->basePath('img/rate.png') ?>" alt="" />
                    <img src="<?php echo $this->basePath('img/unrate2.png') ?>" alt="" />
                    <img src="<?php echo $this->basePath('img/unrate2.png') ?>" alt="" />
                </span>
                <a href="#">Start right away!</a>
                <b>€19</b>
            </div>
        </li>
        <li class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
        	<strong>Blog competition</strong>
            <span><img src="<?php echo $this->basePath('img/slider_img.jpg') ?>" alt="" /></span>
            <div>
            	<p>Blog / Creative / Writing /  Facebook app</p>
                <strong>Author: Studio 365 (Amsterdam)</strong>
                <span>
                    <img src="<?php echo $this->basePath('img/rate.png') ?>" alt="" />
                    <img src="<?php echo $this->basePath('img/rate.png') ?>" alt="" />
                    <img src="<?php echo $this->basePath('img/rate.png') ?>" alt="" />
                    <img src="<?php echo $this->basePath('img/unrate2.png') ?>" alt="" />
                    <img src="<?php echo $this->basePath('img/unrate2.png') ?>" alt="" />
                </span>
                <a href="#">Start right away!</a>
                <b>€19</b>
            </div>
        </li>
        <li class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
        	<strong>Blog competition</strong>
            <span><img src="<?php echo $this->basePath('img/slider_img.jpg') ?>" alt="" /></span>
            <div>
            	<p>Blog / Creative / Writing /  Facebook app</p>
                <strong>Author: Studio 365 (Amsterdam)</strong>
                <span>
                    <img src="<?php echo $this->basePath('img/rate.png') ?>" alt="" />
                    <img src="<?php echo $this->basePath('img/rate.png') ?>" alt="" />
                    <img src="<?php echo $this->basePath('img/rate.png') ?>" alt="" />
                    <img src="<?php echo $this->basePath('img/unrate2.png') ?>" alt="" />
                    <img src="<?php echo $this->basePath('img/unrate2.png') ?>" alt="" />
                </span>
                <a href="#">Start right away!</a>
                <b>€19</b>
            </div>
        </li>
    </ul>
         </div>
         
         
         </div>
         
        
        
      </div>
      <!--===== end first caraousal ===--> 
      <hr>
      <div class="row store">
      <div class="col-lg-9 col-sm-7">
       <h3>Inspiring<br><strong>Share-in- Moment</strong></h3>
          <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
          <p><a role="button" href="#" class="btn btn-primary">TRY THIS CAMPAIGN</a></p>
      </div>
      <div class="col-lg-3 col-sm-5">
       <figure>
                <img alt="" src="<?php echo $this->basePath('img/store-img-1.jpg') ?>"/>
                </figure>
      </div>
      </div>
      <hr>
      
      <div class="row store-margin">
         <div class="col-lg-12 padd-less">
         <ul class="slider">
    	<li class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
        	<strong>Blog competition</strong>
            <span><img src="<?php echo $this->basePath('img/slider_img.jpg') ?>" alt="" /></span>
            <div>
            	<p>Blog / Creative / Writing /  Facebook app</p>
                <strong>Author: Studio 365 (Amsterdam)</strong>
                <span>
                    <img src="<?php echo $this->basePath('img/rate.png') ?>" alt="" />
                    <img src="<?php echo $this->basePath('img/rate.png') ?>" alt="" />
                    <img src="<?php echo $this->basePath('img/rate.png') ?>" alt="" />
                    <img src="<?php echo $this->basePath('img/unrate2.png') ?>" alt="" />
                    <img src="<?php echo $this->basePath('img/unrate2.png') ?>" alt="" />
                </span>
                <a href="#">Start right away!</a>
                <b>€19</b>
            </div>
        </li>
        <li class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
        	<strong>Blog competition</strong>
            <span><img src="<?php echo $this->basePath('img/slider_img.jpg') ?>" alt="" /></span>
            <div>
            	<p>Blog / Creative / Writing /  Facebook app</p>
                <strong>Author: Studio 365 (Amsterdam)</strong>
                <span>
                    <img src="<?php echo $this->basePath('img/rate.png') ?>" alt="" />
                    <img src="<?php echo $this->basePath('img/rate.png') ?>" alt="" />
                    <img src="<?php echo $this->basePath('img/rate.png') ?>" alt="" />
                    <img src="<?php echo $this->basePath('img/unrate2.png') ?>" alt="" />
                    <img src="<?php echo $this->basePath('img/unrate2.png') ?>" alt="" />
                </span>
                <a href="#">Start right away!</a>
                <b>€19</b>
            </div>
        </li>
        <li class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
        	<strong>Blog competition</strong>
            <span><img src="<?php echo $this->basePath('img/slider_img.jpg') ?>" alt="" /></span>
            <div>
            	<p>Blog / Creative / Writing /  Facebook app</p>
                <strong>Author: Studio 365 (Amsterdam)</strong>
                <span>
                    <img src="<?php echo $this->basePath('img/rate.png') ?>" alt="" />
                    <img src="<?php echo $this->basePath('img/rate.png') ?>" alt="" />
                    <img src="<?php echo $this->basePath('img/rate.png') ?>" alt="" />
                    <img src="<?php echo $this->basePath('img/unrate2.png') ?>" alt="" />
                    <img src="<?php echo $this->basePath('img/unrate2.png') ?>" alt="" />
                </span>
                <a href="#">Start right away!</a>
                <b>€19</b>
            </div>
        </li>
        <li class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
        	<strong>Blog competition</strong>
            <span><img src="<?php echo $this->basePath('img/slider_img.jpg') ?>" alt="" /></span>
            <div>
            	<p>Blog / Creative / Writing /  Facebook app</p>
                <strong>Author: Studio 365 (Amsterdam)</strong>
                <span>
                    <img src="<?php echo $this->basePath('img/rate.png') ?>" alt="" />
                    <img src="<?php echo $this->basePath('img/rate.png') ?>" alt="" />
                    <img src="<?php echo $this->basePath('img/rate.png') ?>" alt="" />
                    <img src="<?php echo $this->basePath('img/unrate2.png') ?>" alt="" />
                    <img src="<?php echo $this->basePath('img/unrate2.png') ?>" alt="" />
                </span>
                <a href="#">Start right away!</a>
                <b>€19</b>
            </div>
        </li>
        
        <li class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
        	<strong>Blog competition</strong>
            <span><img src="<?php echo $this->basePath('img/slider_img.jpg') ?>" alt="" /></span>
            <div>
            	<p>Blog / Creative / Writing /  Facebook app</p>
                <strong>Author: Studio 365 (Amsterdam)</strong>
                <span>
                    <img src="<?php echo $this->basePath('img/rate.png') ?>" alt="" />
                    <img src="<?php echo $this->basePath('img/rate.png') ?>" alt="" />
                    <img src="<?php echo $this->basePath('img/rate.png') ?>" alt="" />
                    <img src="<?php echo $this->basePath('img/unrate2.png') ?>" alt="" />
                    <img src="<?php echo $this->basePath('img/unrate2.png') ?>" alt="" />
                </span>
                <a href="#">Start right away!</a>
                <b>€19</b>
            </div>
        </li>
        <li class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
        	<strong>Blog competition</strong>
            <span><img src="<?php echo $this->basePath('img/slider_img.jpg') ?>" alt="" /></span>
            <div>
            	<p>Blog / Creative / Writing /  Facebook app</p>
                <strong>Author: Studio 365 (Amsterdam)</strong>
                <span>
                    <img src="<?php echo $this->basePath('img/rate.png') ?>" alt="" />
                    <img src="<?php echo $this->basePath('img/rate.png') ?>" alt="" />
                    <img src="<?php echo $this->basePath('img/rate.png') ?>" alt="" />
                    <img src="<?php echo $this->basePath('img/unrate2.png') ?>" alt="" />
                    <img src="<?php echo $this->basePath('img/unrate2.png') ?>" alt="" />
                </span>
                <a href="#">Start right away!</a>
                <b>€19</b>
            </div>
        </li>
        <li class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
        	<strong>Blog competition</strong>
            <span><img src="<?php echo $this->basePath('img/slider_img.jpg') ?>" alt="" /></span>
            <div>
            	<p>Blog / Creative / Writing /  Facebook app</p>
                <strong>Author: Studio 365 (Amsterdam)</strong>
                <span>
                    <img src="<?php echo $this->basePath('img/rate.png') ?>" alt="" />
                    <img src="<?php echo $this->basePath('img/rate.png') ?>" alt="" />
                    <img src="<?php echo $this->basePath('img/rate.png') ?>" alt="" />
                    <img src="<?php echo $this->basePath('img/unrate2.png') ?>" alt="" />
                    <img src="<?php echo $this->basePath('img/unrate2.png') ?>" alt="" />
                </span>
                <a href="#">Start right away!</a>
                <b>€19</b>
            </div>
        </li>
        <li class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
        	<strong>Blog competition</strong>
            <span><img src="<?php echo $this->basePath('img/slider_img.jpg') ?>" alt="" /></span>
            <div>
            	<p>Blog / Creative / Writing /  Facebook app</p>
                <strong>Author: Studio 365 (Amsterdam)</strong>
                <span>
                    <img src="<?php echo $this->basePath('img/rate.png') ?>" alt="" />
                    <img src="<?php echo $this->basePath('img/rate.png') ?>" alt="" />
                    <img src="<?php echo $this->basePath('img/rate.png') ?>" alt="" />
                    <img src="<?php echo $this->basePath('img/unrate2.png') ?>" alt="" />
                    <img src="<?php echo $this->basePath('img/unrate2.png') ?>" alt="" />
                </span>
                <a href="#">Start right away!</a>
                <b>€19</b>
            </div>
        </li>
        
        <li class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
        	<strong>Blog competition</strong>
            <span><img src="<?php echo $this->basePath('img/slider_img.jpg') ?>" alt="" /></span>
            <div>
            	<p>Blog / Creative / Writing /  Facebook app</p>
                <strong>Author: Studio 365 (Amsterdam)</strong>
                <span>
                    <img src="<?php echo $this->basePath('img/rate.png') ?>" alt="" />
                    <img src="<?php echo $this->basePath('img/rate.png') ?>" alt="" />
                    <img src="<?php echo $this->basePath('img/rate.png') ?>" alt="" />
                    <img src="<?php echo $this->basePath('img/unrate2.png') ?>" alt="" />
                    <img src="<?php echo $this->basePath('img/unrate2.png') ?>" alt="" />
                </span>
                <a href="#">Start right away!</a>
                <b>€19</b>
            </div>
        </li>
        <li class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
        	<strong>Blog competition</strong>
            <span><img src="<?php echo $this->basePath('img/slider_img.jpg') ?>" alt="" /></span>
            <div>
            	<p>Blog / Creative / Writing /  Facebook app</p>
                <strong>Author: Studio 365 (Amsterdam)</strong>
                <span>
                    <img src="<?php echo $this->basePath('img/rate.png') ?>" alt="" />
                    <img src="<?php echo $this->basePath('img/rate.png') ?>" alt="" />
                    <img src="<?php echo $this->basePath('img/rate.png') ?>" alt="" />
                    <img src="<?php echo $this->basePath('img/unrate2.png') ?>" alt="" />
                    <img src="<?php echo $this->basePath('img/unrate2.png') ?>" alt="" />
                </span>
                <a href="#">Start right away!</a>
                <b>€19</b>
            </div>
        </li>
        <li class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
        	<strong>Blog competition</strong>
            <span><img src="<?php echo $this->basePath('img/slider_img.jpg') ?>" alt="" /></span>
            <div>
            	<p>Blog / Creative / Writing /  Facebook app</p>
                <strong>Author: Studio 365 (Amsterdam)</strong>
                <span>
                    <img src="<?php echo $this->basePath('img/rate.png') ?>" alt="" />
                    <img src="<?php echo $this->basePath('img/rate.png') ?>" alt="" />
                    <img src="<?php echo $this->basePath('img/rate.png') ?>" alt="" />
                    <img src="<?php echo $this->basePath('img/unrate2.png') ?>" alt="" />
                    <img src="<?php echo $this->basePath('img/unrate2.png') ?>" alt="" />
                </span>
                <a href="#">Start right away!</a>
                <b>€19</b>
            </div>
        </li>
        <li class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
        	<strong>Blog competition</strong>
            <span><img src="<?php echo $this->basePath('img/slider_img.jpg') ?>" alt="" /></span>
            <div>
            	<p>Blog / Creative / Writing /  Facebook app</p>
                <strong>Author: Studio 365 (Amsterdam)</strong>
                <span>
                    <img src="<?php echo $this->basePath('img/rate.png') ?>" alt="" />
                    <img src="<?php echo $this->basePath('img/rate.png') ?>" alt="" />
                    <img src="<?php echo $this->basePath('img/rate.png') ?>" alt="" />
                    <img src="<?php echo $this->basePath('img/unrate2.png') ?>" alt="" />
                    <img src="<?php echo $this->basePath('img/unrate2.png') ?>" alt="" />
                </span>
                <a href="#">Start right away!</a>
                <b>€19</b>
            </div>
        </li>
    </ul>
         </div>
         
         
         </div>
      
       <hr>
      <div class="row store-2">
      <div class="col-lg-7 pull-right col-sm-8">
       <h3>Resturant<br><strong>Coupon Give away</strong></h3>
          <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
          <p><a role="button" href="#" class="btn btn-primary">START RIGHT AWAY</a></p>
      </div>
      
      </div>
      <hr>
      
      <div class="row store-margin">
         <div class="col-lg-12 padd-less">
         <ul class="slider">
    	<li class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
        	<strong>Blog competition</strong>
            <span><img src="<?php echo $this->basePath('img/slider_img.jpg') ?>" alt="" /></span>
            <div>
            	<p>Blog / Creative / Writing /  Facebook app</p>
                <strong>Author: Studio 365 (Amsterdam)</strong>
                <span>
                    <img src="<?php echo $this->basePath('img/rate.png') ?>" alt="" />
                    <img src="<?php echo $this->basePath('img/rate.png') ?>" alt="" />
                    <img src="<?php echo $this->basePath('img/rate.png') ?>" alt="" />
                    <img src="<?php echo $this->basePath('img/unrate2.png') ?>" alt="" />
                    <img src="<?php echo $this->basePath('img/unrate2.png') ?>" alt="" />
                </span>
                <a href="#">Start right away!</a>
                <b>€19</b>
            </div>
        </li>
        <li class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
        	<strong>Blog competition</strong>
            <span><img src="<?php echo $this->basePath('img/slider_img.jpg') ?>" alt="" /></span>
            <div>
            	<p>Blog / Creative / Writing /  Facebook app</p>
                <strong>Author: Studio 365 (Amsterdam)</strong>
                <span>
                    <img src="<?php echo $this->basePath('img/rate.png') ?>" alt="" />
                    <img src="<?php echo $this->basePath('img/rate.png') ?>" alt="" />
                    <img src="<?php echo $this->basePath('img/rate.png') ?>" alt="" />
                    <img src="<?php echo $this->basePath('img/unrate2.png') ?>" alt="" />
                    <img src="<?php echo $this->basePath('img/unrate2.png') ?>" alt="" />
                </span>
                <a href="#">Start right away!</a>
                <b>€19</b>
            </div>
        </li>
        <li class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
        	<strong>Blog competition</strong>
            <span><img src="<?php echo $this->basePath('img/slider_img.jpg') ?>" alt="" /></span>
            <div>
            	<p>Blog / Creative / Writing /  Facebook app</p>
                <strong>Author: Studio 365 (Amsterdam)</strong>
                <span>
                    <img src="<?php echo $this->basePath('img/rate.png') ?>" alt="" />
                    <img src="<?php echo $this->basePath('img/rate.png') ?>" alt="" />
                    <img src="<?php echo $this->basePath('img/rate.png') ?>" alt="" />
                    <img src="<?php echo $this->basePath('img/unrate2.png') ?>" alt="" />
                    <img src="<?php echo $this->basePath('img/unrate2.png') ?>" alt="" />
                </span>
                <a href="#">Start right away!</a>
                <b>€19</b>
            </div>
        </li>
        <li class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
        	<strong>Blog competition</strong>
            <span><img src="<?php echo $this->basePath('img/slider_img.jpg') ?>" alt="" /></span>
            <div>
            	<p>Blog / Creative / Writing /  Facebook app</p>
                <strong>Author: Studio 365 (Amsterdam)</strong>
                <span>
                    <img src="<?php echo $this->basePath('img/rate.png') ?>" alt="" />
                    <img src="<?php echo $this->basePath('img/rate.png') ?>" alt="" />
                    <img src="<?php echo $this->basePath('img/rate.png') ?>" alt="" />
                    <img src="<?php echo $this->basePath('img/unrate2.png') ?>" alt="" />
                    <img src="<?php echo $this->basePath('img/unrate2.png') ?>" alt="" />
                </span>
                <a href="#">Start right away!</a>
                <b>€19</b>
            </div>
        </li>
        
        <li class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
        	<strong>Blog competition</strong>
            <span><img src="<?php echo $this->basePath('img/slider_img.jpg') ?>" alt="" /></span>
            <div>
            	<p>Blog / Creative / Writing /  Facebook app</p>
                <strong>Author: Studio 365 (Amsterdam)</strong>
                <span>
                    <img src="<?php echo $this->basePath('img/rate.png') ?>" alt="" />
                    <img src="<?php echo $this->basePath('img/rate.png') ?>" alt="" />
                    <img src="<?php echo $this->basePath('img/rate.png') ?>" alt="" />
                    <img src="<?php echo $this->basePath('img/unrate2.png') ?>" alt="" />
                    <img src="<?php echo $this->basePath('img/unrate2.png') ?>" alt="" />
                </span>
                <a href="#">Start right away!</a>
                <b>€19</b>
            </div>
        </li>
        <li class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
        	<strong>Blog competition</strong>
            <span><img src="<?php echo $this->basePath('img/slider_img.jpg') ?>" alt="" /></span>
            <div>
            	<p>Blog / Creative / Writing /  Facebook app</p>
                <strong>Author: Studio 365 (Amsterdam)</strong>
                <span>
                    <img src="<?php echo $this->basePath('img/rate.png') ?>" alt="" />
                    <img src="<?php echo $this->basePath('img/rate.png') ?>" alt="" />
                    <img src="<?php echo $this->basePath('img/rate.png') ?>" alt="" />
                    <img src="<?php echo $this->basePath('img/unrate2.png') ?>" alt="" />
                    <img src="<?php echo $this->basePath('img/unrate2.png') ?>" alt="" />
                </span>
                <a href="#">Start right away!</a>
                <b>€19</b>
            </div>
        </li>
        <li class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
        	<strong>Blog competition</strong>
            <span><img src="<?php echo $this->basePath('img/slider_img.jpg') ?>" alt="" /></span>
            <div>
            	<p>Blog / Creative / Writing /  Facebook app</p>
                <strong>Author: Studio 365 (Amsterdam)</strong>
                <span>
                    <img src="<?php echo $this->basePath('img/rate.png') ?>" alt="" />
                    <img src="<?php echo $this->basePath('img/rate.png') ?>" alt="" />
                    <img src="<?php echo $this->basePath('img/rate.png') ?>" alt="" />
                    <img src="<?php echo $this->basePath('img/unrate2.png') ?>" alt="" />
                    <img src="<?php echo $this->basePath('img/unrate2.png') ?>" alt="" />
                </span>
                <a href="#">Start right away!</a>
                <b>€19</b>
            </div>
        </li>
        <li class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
        	<strong>Blog competition</strong>
            <span><img src="<?php echo $this->basePath('img/slider_img.jpg') ?>" alt="" /></span>
            <div>
            	<p>Blog / Creative / Writing /  Facebook app</p>
                <strong>Author: Studio 365 (Amsterdam)</strong>
                <span>
                    <img src="<?php echo $this->basePath('img/rate.png') ?>" alt="" />
                    <img src="<?php echo $this->basePath('img/rate.png') ?>" alt="" />
                    <img src="<?php echo $this->basePath('img/rate.png') ?>" alt="" />
                    <img src="<?php echo $this->basePath('img/unrate2.png') ?>" alt="" />
                    <img src="<?php echo $this->basePath('img/unrate2.png') ?>" alt="" />
                </span>
                <a href="#">Start right away!</a>
                <b>€19</b>
            </div>
        </li>
        
        <li class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
        	<strong>Blog competition</strong>
            <span><img src="<?php echo $this->basePath('img/slider_img.jpg') ?>" alt="" /></span>
            <div>
            	<p>Blog / Creative / Writing /  Facebook app</p>
                <strong>Author: Studio 365 (Amsterdam)</strong>
                <span>
                    <img src="<?php echo $this->basePath('img/rate.png') ?>" alt="" />
                    <img src="<?php echo $this->basePath('img/rate.png') ?>" alt="" />
                    <img src="<?php echo $this->basePath('img/rate.png') ?>" alt="" />
                    <img src="<?php echo $this->basePath('img/unrate2.png') ?>" alt="" />
                    <img src="<?php echo $this->basePath('img/unrate2.png') ?>" alt="" />
                </span>
                <a href="#">Start right away!</a>
                <b>€19</b>
            </div>
        </li>
        <li class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
        	<strong>Blog competition</strong>
            <span><img src="<?php echo $this->basePath('img/slider_img.jpg') ?>" alt="" /></span>
            <div>
            	<p>Blog / Creative / Writing /  Facebook app</p>
                <strong>Author: Studio 365 (Amsterdam)</strong>
                <span>
                    <img src="<?php echo $this->basePath('img/rate.png') ?>" alt="" />
                    <img src="<?php echo $this->basePath('img/rate.png') ?>" alt="" />
                    <img src="<?php echo $this->basePath('img/rate.png') ?>" alt="" />
                    <img src="<?php echo $this->basePath('img/unrate2.png') ?>" alt="" />
                    <img src="<?php echo $this->basePath('img/unrate2.png') ?>" alt="" />
                </span>
                <a href="#">Start right away!</a>
                <b>€19</b>
            </div>
        </li>
        <li class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
        	<strong>Blog competition</strong>
            <span><img src="<?php echo $this->basePath('img/slider_img.jpg') ?>" alt="" /></span>
            <div>
            	<p>Blog / Creative / Writing /  Facebook app</p>
                <strong>Author: Studio 365 (Amsterdam)</strong>
                <span>
                    <img src="<?php echo $this->basePath('img/rate.png') ?>" alt="" />
                    <img src="<?php echo $this->basePath('img/rate.png') ?>" alt="" />
                    <img src="<?php echo $this->basePath('img/rate.png') ?>" alt="" />
                    <img src="<?php echo $this->basePath('img/unrate2.png') ?>" alt="" />
                    <img src="<?php echo $this->basePath('img/unrate2.png') ?>" alt="" />
                </span>
                <a href="#">Start right away!</a>
                <b>€19</b>
            </div>
        </li>
        <li class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
        	<strong>Blog competition</strong>
            <span><img src="<?php echo $this->basePath('img/slider_img.jpg') ?>" alt="" /></span>
            <div>
            	<p>Blog / Creative / Writing /  Facebook app</p>
                <strong>Author: Studio 365 (Amsterdam)</strong>
                <span>
                    <img src="<?php echo $this->basePath('img/rate.png') ?>" alt="" />
                    <img src="<?php echo $this->basePath('img/rate.png') ?>" alt="" />
                    <img src="<?php echo $this->basePath('img/rate.png') ?>" alt="" />
                    <img src="<?php echo $this->basePath('img/unrate2.png') ?>" alt="" />
                    <img src="<?php echo $this->basePath('img/unrate2.png') ?>" alt="" />
                </span>
                <a href="#">Start right away!</a>
                <b>€19</b>
            </div>
        </li>
    </ul>
         </div>
         
         
         </div>
      
       
      <div class="row store-3">
      <div class="col-lg-7 pull-right col-sm-8">
       <h3>Try Our Spicy<br><strong>Hot or not campaign app</strong></h3>
          <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
          <p><a role="button" href="#" class="btn btn-primary">START RIGHT AWAY</a></p>
      </div>
      
      </div>
     
      
     
     