<img src="https://test.scampaigns.com/img/divider.png" id="imgdragable" style="position: absolute; top: 776px; display: none;">
 


<!--SFPPAGE-->



<meta http-equiv="Content-Type" content="text/html; charset=utf-8">

<link rel="stylesheet" href="//test.scampaigns.com/user_template/7785476c10e224076-Optinapp--mod-template/css/style.css">
<!--<link rel="stylesheet" href="http://localhost/zf_new/public/css/styles.css"/>
<link rel="stylesheet" href="http://localhost/zf_new/public/css/textarea.css"/>---->

<link rel="stylesheet" type="text/css" media="all" href="//test.scampaigns.com/user_template/7785476c10e224076-Optinapp--mod-template/css/jui.checkboxes.css">

<!-- <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>
   <script src = "http://js.nicedit.com/nicEdit-latest.js"></script>--->
 

<!---<script type="text/javascript" src="http://localhost/zf_new/public/js/jquery.form.js"></script>
<script type="text/javascript" src="http://localhost/zf_new/public/js/style.js"></script>---->




<div class="details-n-winn-wrapper">
<div class="SFPTWO_IMAGEEDIT"><img id="images1" src="//test.scampaigns.com/user_template/7785476c10e224076-Optinapp--mod-template/img/top-img.jpg" alt="" style="width: 100%; margin:0 0 8px 0;"><div class="setting-2" style="display: none;"><a title="Edit" class="edit" href="javascript:void(0)"></a><a title="delete" class="delete" href="javascript:void(0)"></a><input type="hidden" value="7785476c10e224076-Optinapp--mod-template" id="hid"><input type="hidden" value="0" id="imgCount"></div></div> 
<div class="SFPTWO_IMAGEEDIT rand_266" style="display: none;"><img id="images1" src="//test.scampaigns.com/user_template/7785476c10e224076-Optinapp--mod-template/img/top-img.jpg" alt="" style="width: 100%;"><div class="setting-2" style="display:none"><a title="Edit" class="edit" href="javascript:void(0)"></a><a title="delete" class="delete" href="javascript:void(0)"></a><input type="hidden" value="7785476c10e224076-Optinapp--mod-template" id="hid"><input type="hidden" value="0" id="imgCount"></div></div>         
        
<div class="tool-tip SFPTWO_TEXTEDIT"><h2 class="textedit SFPTWO_TAGEDIT edit explicit_edit" contenteditable="false">Fill in your details and win! </h2><div class="setting-2" id="text" style="display: none;"><a title="delete" class="delete" href="javascript:void(0)"></a></div></div>
<div class="form-container jui-checkboxes-container" id="checkboxesInit2">


<ul class="designelements clearfix" style="position:absolute;left:0; z-index:9999;">
 <li id="lilabelme" style="position: relative; top: 95px; left: -56px; display: none;"><a style="cursor: pointer;" onclick="chechTypeAndAdd(this.rel)" rel="checkbox" id="checkbox" class="disabled"><span>Checkbox</span><img src="https://test.scampaigns.com/formbuild/checkbox_icon.png" alt=""></a></li>
   
</ul>
<form id="editable" action="complete.php" class="SFPTWO_EDITFORM" style="margin-top:25px;" method="post" name="form_1518122">

 <img src="https://test.scampaigns.com/img/divider.png" id="imgdrag" style="position: relative; top: 694px; display: none;">
 <img src="https://test.scampaigns.com/img/divider.png" id="imgdragable" style="display: none;">

<ul class="sortable-list" style="">
<li id="trigme" style="display: none;">
  <div>dd</div> 
  <div id="ullidrag" class="ullidrag" style="display:none; cursor:move;"><img src="/img/1416497040_cursor_drag_arrow_2.jpg"></div><div class="setting-2 prevnext"><a title="delete" class="delete" href="javascript:void(0)"></a><input type="hidden" id="hid"><input type="hidden" value="0" id="imgCount"></div><div id="ullidrag" class="ullidrag" style="display:none; cursor:move;"><img src="/img/1416497040_cursor_drag_arrow_2.jpg"></div></li>
	<li class="dottedLi randtxt_383 element1" style="display: none;"><div id="labeledit" class="labeledit emaildrag"><p style="font-size: 19px;" id="pid_" class="opt explicit_edit" contenteditable="false"><font color="#15ace7">EmaiL address</font></p></div><input name="textboxelement1" type="text">
    
    <div id="ullidrag" class="ullidrag" style="display:none; cursor:move;"><img src="/img/1416497040_cursor_drag_arrow_2.jpg"></div><div class="setting-2 prevnext"><a title="delete" class="delete" href="javascript:void(0)"></a><input type="hidden" id="hid"><input type="hidden" value="0" id="imgCount"></div><div id="ullidrag" class="ullidrag" style="display:none; cursor:move;"><img src="/img/1416497040_cursor_drag_arrow_2.jpg"></div></li>
    

	<li class="dottedLi randtxt_345 element2" style="display: none;"><div id="diveditme" class="labeledit addmechk checkboxdrag"><p style="font-size: 19px;" id="pid_form" class="opt explicit_edit" contenteditable="false"><font color="#15ace7">What kind of campaign are you Looking for? </font>
    </p></div><div class="checksboxes p_scents chkboxaddnow" id="checksboxes_form657"><div id="chkclone"><div for="p_scnts" class="jui-checkbox-row" id="jui-checkbox-rowform657"><span class="checkboxWrapper"><input type="checkbox" value="1" name="check_4"> </span> <p class="opt explicit_edit" id="1" contenteditable="false"><font color="#15ace7">option1</font></p> </div><div class="jui-checkbox-row"> <span class="checkboxWrapper"><input type="checkbox" value="2" name="check_5"></span> <p class="opt explicit_edit" id="2" contenteditable="false"><font color="#15ace7">option2</font></p> </div><div class="jui-checkbox-row"><span class="checkboxWrapper"><input type="checkbox" value="3" name="check_6"></span><p class="opt explicit_edit" id="3" contenteditable="false"><font color="#15ace7">option3</font></p></div></div><p id="mepp" class="pchkadd"></p></div> <div id="ullidrag" class="ullidrag" style="display:none; cursor:move;"><img src="/img/1416497040_cursor_drag_arrow_2.jpg"></div><div class="setting-2 prevnext"><a title="delete" class="delete" href="javascript:void(0)"></a><input type="hidden" id="hid"><input type="hidden" value="0" id="imgCount"></div><div id="ullidrag" class="ullidrag" style="display:none; cursor:move;"><img src="/img/1416497040_cursor_drag_arrow_2.jpg"></div></li>
    

	 <li class="dottedLi randtxt_495 element3" style="display: none;"><div id="diveditme" class="labeledit"><p style="font-size: 19px;" id="pid_formmsg" class="opt explicit_edit" contenteditable="false"><font color="#15ace7">Your message</font></p><div><textarea id="editmetext" name="textareaelement3"></textarea></div></div><div id="ullidrag" class="ullidrag" style="display:none; cursor:move;"><img src="/img/1416497040_cursor_drag_arrow_2.jpg"></div><div class="setting-2 prevnext"><a title="delete" class="delete" href="javascript:void(0)"></a><input type="hidden" id="hid"><input type="hidden" value="0" id="imgCount"></div><div id="ullidrag" class="ullidrag" style="display:none; cursor:move;"><img src="/img/1416497040_cursor_drag_arrow_2.jpg"></div></li>
	<li style="display: none;" class="randtxt_221"><input name="" type="submit" value="Send" class="inputdisabled"><div id="ullidrag" class="ullidrag" style="display:none; cursor:move;"><img src="/img/1416497040_cursor_drag_arrow_2.jpg"></div><div class="setting-2 prevnext"><a title="delete" class="delete" href="javascript:void(0)"></a><input type="hidden" id="hid"><input type="hidden" value="0" id="imgCount"></div><div id="ullidrag" class="ullidrag" style="display:none; cursor:move;"><img src="/img/1416497040_cursor_drag_arrow_2.jpg"></div></li>

<li class="" style="display: list-item;">
    	<li class="dottedLi"><div id="labeledit" class="labeledit textdrag"><p id="pid_91" class="opt explicit_edit" contenteditable="false"><font color="#15ace7">Label</font></p></div><input type="text" name="" id="txtbox_56"><div id="ullidrag" class="ullidrag" style="display:none; cursor:move;"><img src="/img/1416497040_cursor_drag_arrow_2.jpg"></div><div class="setting-2 prevnext"><a title="delete" class="delete" href="javascript:void(0)"></a><input type="hidden" id="hid"><input type="hidden" value="0" id="imgCount"></div><div id="ullidrag" class="ullidrag" style="display:none; cursor:move;"><img src="/img/1416497040_cursor_drag_arrow_2.jpg"></div></li>
    <div id="ullidrag" class="ullidrag" style="display:none; cursor:move;"><img src="/img/1416497040_cursor_drag_arrow_2.jpg"></div><div class="setting-2 prevnext"><a title="delete" class="delete" href="javascript:void(0)"></a><input type="hidden" id="hid"><input type="hidden" value="0" id="imgCount"></div><div id="ullidrag" class="ullidrag" style="display:none; cursor:move;"><img src="/img/1416497040_cursor_drag_arrow_2.jpg"></div></li><li class="ui-draggable" style="display: list-item;">
    	<li class="dottedLi"><div id="labeledit" class="labeledit emaildrag"><p id="pid_259" class="opt explicit_edit" contenteditable="false"><font color="#15ace7">Label</font></p></div><input type="email" name="" id="email_616"><div id="ullidrag" class="ullidrag" style="display:none; cursor:move;"><img src="/img/1416497040_cursor_drag_arrow_2.png"></div><div class="setting-2 prevnext"><a title="delete" class="delete" href="javascript:void(0)"></a><input type="hidden" id="hid"><input type="hidden" value="0" id="imgCount"></div></li>
    </li><li class="ui-draggable" style="display: list-item;">
    	<li class="dottedLi ui-draggable"><p id="pid_341" class="opt explicit_edit" contenteditable="false"><font color="#15ace7">Label</font></p><div onclick="selectboxclick(this)" class="dropdowndrag adddrop"><select class="select" id="hours160" style="font-family: times new roman;font-size: 20px; height: 30px;margin-bottom: 10px;width: 120px;"><option value="0">Select</option><option id="1" value="option1">option1</option><option id="2" value="option2">option2</option><option value="Option3">Option3</option><option value="Option4">Option4</option><option value="Option5">Option5</option></select></div><div id="ullidrag" class="ullidrag" style="display:none; cursor:move;"><img src="/img/1416497040_cursor_drag_arrow_2.png"></div><div class="setting-2 prevnext"><a title="delete" class="delete" href="javascript:void(0)"></a><input type="hidden" id="hid"><input type="hidden" value="0" id="imgCount"></div><div id="ullidrag" class="ullidrag" style="display:none; cursor:move;"><img src="/img/1416497040_cursor_drag_arrow_2.jpg"></div></li>
    <div id="ullidrag" class="ullidrag" style="display:none; cursor:move;"><img src="/img/1416497040_cursor_drag_arrow_2.jpg"></div><div class="setting-2 prevnext"><a title="delete" class="delete" href="javascript:void(0)"></a><input type="hidden" id="hid"><input type="hidden" value="0" id="imgCount"></div></li><li class="ui-draggable" style="display: list-item;">
    	<li class="dottedLi"><div id="labeledit" class="labeledit radioboxdrag"><p id="pid_705" class="opt explicit_edit" contenteditable="false"><font color="#15ace7">Label</font></p></div><div class="checksboxes p_scents selectboxaddnow editmyopt addingselect" id="checksboxes_614"><div id="radioclone"><div for="p_scnts" class="jui-checkbox-row" id="jui-checkbox-row614"><span class="checkboxWrapper"><input type="radio" value="1" name="name"> </span> <p class="opt explicit_edit" id="1" contenteditable="false"><font color="#15ace7">option1</font></p> </div><div class="jui-checkbox-row"> <span class="checkboxWrapper"><input type="radio" value="2" name="name"></span> <p class="opt explicit_edit" id="2" contenteditable="false"><font color="#15ace7">option2</font></p> </div><div class="jui-checkbox-row"><span class="checkboxWrapper" id="p_scnt_3" name="p_scnt_3"><input type="radio" value="2" name="name"></span><p class="opt explicit_edit" id="3" name="3" contenteditable="false"><font color="#15ace7">option3</font></p></div><div class="jui-checkbox-row"><span class="checkboxWrapper" id="p_scnt_4" name="p_scnt_4"><input type="radio" value="2" name="name"></span><p class="opt explicit_edit" id="4" name="4" contenteditable="false"><font color="#15ace7">option4</font></p></div></div><p id="mepp" class="pselectadd"></p></div><div id="ullidrag" class="ullidrag" style="display:none; cursor:move;"><img src="/img/1416497040_cursor_drag_arrow_2.png"></div><div class="setting-2 prevnext"><a title="delete" class="delete" href="javascript:void(0)"></a><input type="hidden" id="hid"><input type="hidden" value="0" id="imgCount"></div></li>
    </li><li class="" style="display: list-item; position: relative;">
    	<li class="dottedLi"><div id="labeledit" class="labeledit addmechk checkboxdrag"><p id="pid_3" class="opt explicit_edit" contenteditable="false"><font color="#15ace7">Label</font></p></div><div class="checksboxes p_scents chkboxaddnow adding" id="checksboxes_884"><div id="chkclone"><div for="p_scnts" class="jui-checkbox-row" id="jui-checkbox-row884"><span class="checkboxWrapper"><input type="checkbox" value="1" name="name"> </span> <p class="opt explicit_edit" id="1" contenteditable="false"><font color="#6b0075">first</font></p> </div><div class="jui-checkbox-row"> <span class="checkboxWrapper"><input type="checkbox" value="2" name="name"></span> <p class="opt explicit_edit" id="2" contenteditable="false"><font color="#750800">second</font></p> </div><div class="jui-checkbox-row"><span class="checkboxWrapper"><input type="checkbox" value="3" name="name"></span><p class="opt explicit_edit" id="3" contenteditable="false"><font face="Helvetica">third</font></p></div></div><p id="mepp" class="pchkadd"></p></div><div id="ullidrag" class="ullidrag" style="display:none; cursor:move;"><img src="/img/1416497040_cursor_drag_arrow_2.jpg"></div><div class="setting-2 prevnext"><a title="delete" class="delete" href="javascript:void(0)"></a><input type="hidden" id="hid"><input type="hidden" value="0" id="imgCount"></div><div id="ullidrag" class="ullidrag" style="display:none; cursor:move;"><img src="/img/1416497040_cursor_drag_arrow_2.jpg"></div></li>
    <div id="ullidrag" class="ullidrag" style="display:none; cursor:move;"><img src="/img/1416497040_cursor_drag_arrow_2.jpg"></div><div class="setting-2 prevnext"><a title="delete" class="delete" href="javascript:void(0)"></a><input type="hidden" id="hid"><input type="hidden" value="0" id="imgCount"></div><div id="ullidrag" class="ullidrag" style="display:none; cursor:move;"><img src="/img/1416497040_cursor_drag_arrow_2.jpg"></div></li><li class="ui-draggable" style="display: list-item;">
    	<li class="dottedLi"><div id="getbtnme" class="submitdrag editmybtn"><input class="inputdisabled" type="submit" name="" value="SEND"></div><div id="ullidrag" class="ullidrag" style="display:none; cursor:move;"><img src="/img/1416497040_cursor_drag_arrow_2.jpg"></div><div class="setting-2 prevnext"><a title="delete" class="delete" href="javascript:void(0)"></a><input type="hidden" id="hid"><input type="hidden" value="0" id="imgCount"></div><div id="ullidrag" class="ullidrag" style="display:none; cursor:move;"><img src="/img/1416497040_cursor_drag_arrow_2.jpg"></div></li>
    <div id="ullidrag" class="ullidrag" style="display:none; cursor:move;"><img src="/img/1416497040_cursor_drag_arrow_2.jpg"></div><div class="setting-2 prevnext"><a title="delete" class="delete" href="javascript:void(0)"></a><input type="hidden" id="hid"><input type="hidden" value="0" id="imgCount"></div><div id="ullidrag" class="ullidrag" style="display:none; cursor:move;"><img src="/img/1416497040_cursor_drag_arrow_2.jpg"></div></li></ul>
</form>
</div>
</div>