<div class="site">
  <div class="container-fluid"> 
    <!--===== start banner ===-->
  <div class="row">  
  <div class="banner case-studies-bg">
        <ul class="social_icon2">
          <li><a href="#">Share this website</a></li>
          <li><a href="#"></a> <a href="#"></a> <a href="#"></a></li>
        </ul>
        <div class="clearfix"></div>
        <div class="banner_caption4 col-md-8" >
          <h1>Meet our team</h1>
          
           </div>
      </div>
    
    </div>
    <div class="row no-pad">
     <div class="col-lg-12 no-pad">
     
     <div class="col-lg-8 no-pad">
     
     
     <div class="col-lg-12"><figure><img alt="" src="<?php echo $this->basePath('img/abt-img-1.jpg') ?>"><div class="abt-img-wrap col-lg-12">
     <div class="abt-title"><h3>Koen van de Wetering</h3>
     <p>Founder</p>
     </div>
     <div class="abt-social">
     <ul class="social_icon3">
      <li><a href="#"></a> <a href="#"></a> <a href="#"></a></li>
        </ul>
     </div>
     </div></figure></div>
     <div class="col-lg-6 col-sm-6"><figure><img alt="" src="<?php echo $this->basePath('img/abt-img-2.jpg') ?>"><div class="abt-img-wrap col-lg-12">
     <div class="abt-title"><h3>Eva Machielse</h3>
     <p>Sales and marketing</p>
     </div>
     <div class="abt-social">
     <ul class="social_icon3">
      <li><a href="#"></a> <a href="#"></a> <a href="#"></a></li>
        </ul>
     </div>
     </div></figure></div>
      <div class="col-lg-6 col-sm-6"> <figure><img alt="" src="<?php echo $this->basePath('img/abt-img-3.jpg') ?>"><div class="abt-img-wrap col-lg-12">
     <div class="abt-title"><h3>Floris Donkers</h3>
     <p>Projectmanagement</p>
     </div>
     <div class="abt-social">
     <ul class="social_icon3">
      <li><a href="#"></a> <a href="#"></a> <a href="#"></a></li>
        </ul>
     </div>
     </div></figure></div>
      <div class="col-lg-6 col-sm-6"> <figure><img alt="" src="<?php echo $this->basePath('img/abt-img-4.jpg') ?>"><div class="abt-img-wrap col-lg-12">
     <div class=" abt-title"><h3>Joris de groot</h3>
     <p>Development</p>
     </div>
     <div class="abt-social">
     <ul class="social_icon3">
      <li><a href="#"></a> <a href="#"></a> <a href="#"></a></li>
        </ul>
     </div>
     </div></figure></div>
      <div class="col-lg-6 col-sm-6"><figure><img alt="" src="<?php echo $this->basePath('img/abt-img-5.jpg') ?>"><div class="abt-img-wrap col-lg-12">
     <div class="abt-title"><h3>Anne van dijk</h3>
     <p>Office</p>
     </div>
     <div class="abt-social">
     <ul class="social_icon3">
      <li><a href="#"></a> <a href="#"></a> <a href="#"></a></li>
        </ul>
     </div>
     </div></figure></div>
     
     
     </div>
     
     <div class="col-lg-4 no-pad">
      <div class="col-lg-12 col-sm-6"><figure><img alt="" src="<?php echo $this->basePath('img/abt-img-6.jpg') ?>"><div class="abt-img-wrap col-lg-12">
     <div class="abt-title"><h3>Marc van der Wielen</h3>
     <p>Marketing</p>
     </div>
     <div class="abt-social">
     <ul class="social_icon3">
      <li><a href="#"></a> <a href="#"></a> <a href="#"></a></li>
        </ul>
     </div>
     </div></figure></div>
     <div class="col-lg-12 col-sm-6"><figure><img alt="" src="<?php echo $this->basePath('img/abt-img-7.jpg') ?>"><div class="abt-img-wrap col-lg-12">
     <div class="abt-title"><h3>Eva Machielse</h3>
     <p>Sales and marketing</p>
     </div>
     <div class="abt-social">
     <ul class="social_icon3">
      <li><a href="#"></a> <a href="#"></a> <a href="#"></a></li>
        </ul>
     </div>
     </div></figure></div>
      <div class="col-lg-12 col-sm-6"><figure><img alt="" src="<?php echo $this->basePath('img/abt-img-8.jpg') ?>"><div class="abt-img-wrap col-lg-12">
     <div class="abt-title"><h3>Eva Machielse</h3>
     <p>Sales and marketing</p>
     </div>
     <div class="abt-social">
     <ul class="social_icon3">
      <li><a href="#"></a> <a href="#"></a> <a href="#"></a></li>
        </ul>
     </div>
     </div></figure></div>
     
     </div> 
     
    
      
    </div><!--===== end banner ===--> 
    <div class="clearfix"></div>