        <?php
     $protocol = '';
        if (isset($_SERVER['HTTPS']) &&
       ($_SERVER['HTTPS'] == 'on' || $_SERVER['HTTPS'] == 1) ||
        isset($_SERVER['HTTP_X_FORWARDED_PROTO']) &&
        $_SERVER['HTTP_X_FORWARDED_PROTO'] == 'https') {
         $protocol = 'https://';
        }
        else {
        $protocol = 'http://';
           }
       // echo $_SERVER['SERVER_PROTOCOL'].$_SERVER['HTTP_HOST'].$_SERVER['REQUEST_URI'];
        $url = $protocol.$_SERVER["SERVER_NAME"];

?>


 <script>
  function fbs_click()
    {
    var base_url = window.location.origin;
    u=base_url+"/index/accountsignin";
    t='smartfanpage';
    var child = window.open('http://www.facebook.com/sharer.php?u='+encodeURIComponent(u)+'&t='+encodeURIComponent(t),'sharer','toolbar=0,status=0,width=626,height=436');
    }
    function twt_click()
    {
    var base_url = window.location.origin;
    u=base_url+"/index/accountsignin";
    t='smartfanpage';
    var child = window.open('http://twitter.com/share?u='+encodeURIComponent(u)+'&t='+encodeURIComponent(t),'sharer','toolbar=0,status=0,width=626,height=436');   
    }
    
    function linkedinButton(){
    var base_url = window.location.origin;
    var articleUrl = encodeURIComponent(base_url+'/index/accountsignin');
       var articleTitle = encodeURIComponent('smartfanpage');
       var articleSummary = encodeURIComponent('publisher login');
       var articleSource = encodeURIComponent('best');
       var goto = 'http://www.linkedin.com/shareArticle?mini=true'+
           '&url='+articleUrl+
           '&title='+articleTitle+
           '&summary='+articleSummary+
           '&source='+articleSource;
       window.open(goto, "LinkedIn", "width=660,height=600,scrollbars=yes;resizable=no");         
}         
  </script>
<style>
#log-alert > p#login-alert {
  color: red;
  font-size: 12px;
}
#log-alert1 > p#login-alert1 {
  color: red;
  font-size: 12px;
}
a#here{
    color:blue;
    
}
</style>



<div  class="site">
  <div class="container-fluid"> 
     <!--===== start banner ===-->
    <div class="row">
      <div class="banner_contact">
        <ul class="social_icon">
          <li><a href="#">Share this website</a></li>
          <li><a href="javascript:void(0)" onclick="return fbs_click()"></a> <a style="cursor:pointer" onclick="return twt_click()"></a> <a style="cursor:pointer" onclick="return linkedinButton()"></a></li>
        </ul> <!--=== social icon ===-->
        <div class="cont-title sfp-accnt">
        <h1>Publish great campaigns.</h1>
        </div>
      </div>
      
    </div><!--===== end banner ===--> 
    

     <div class="row">
     <div class="col-lg-12">
     <div class="create-ur-sfp-account-form col-lg-8 col-lg-offset-2">
     <h4>Login in smartfanpage</h4>
     <div class="create-ur-sfp-account-form">
     <ul>
     <li>
     <label for="">Email address <span>*</span></label>
     <input type="text" id="username" name="">
     </li>
     <li>
     <label for="">Password <span>*</span></label>
     <input type="password" id="password" name="">
     </li>
     <li id="log-alert" style="display: none;"><label></label><p id="login-alert">* please provide valid username or password</p></li>
     <li id="log-alert1" style="display: none;">                                                                            
     <p id="login-alert1">You are registered with facebook.If you really want to create your account without facebook , register <a href="<?php echo $url;?>/index/accountsignup">Here</a></p>
     </li>
          
   <li>
   <label>&nbsp;</label>
   <a class="continue" onclick="continuelog1()" href="javascript:void(0)">Let's get started</a></li>
   
   <li><label>&nbsp;</label>
   <p class="prefer-to-login">
     I prefer to login with<a onclick="logInWithYourFaceBookAccount()" href="javascript:void(0)"><img src="<?php echo $this->basePath('img/fb-icon - Copywe.png');?>"/></a>
    
   <!--  <p> Forget your password ? <a class="click-me" id="click-pass" href="<?php echo $this->url('application/default',array('controller'=>'Index','action'=>'forgetpassword'));?>">click here</a></p>-->
     </p>
    
     
   
   </li>
     </ul>
     
    
     </div>
     
     
    
     </div>
    
     </div>
     
     </div>
  <script>



  function forgetPasswordFunction(){
    
      
  }
  
  </script>
  
  
  
<style type="text/css">
.banner_contact
{
 background: url(../img/store_banner-modified.jpg) no-repeat top center;
    display: block;
    height: 330px;
    margin: auto;
    overflow: hidden;
    width: 100%;
    background-size:cover ;

}
.continue {
  background: none repeat scroll 0 0 #252b34;
  border: medium none;
  color: #fff;
  display: block;
  float: left;
  font-family: "ubuntubold";
  font-size: 16px;
  height: 52px;
  line-height: 52px;
  margin: 0;
  text-align: center;
  text-transform: uppercase;
  width: 50%;
}

 .alert-info {
    width: 220px;
    padding: 10px;
    border: 5px solid gray;
    text-align: center;
    display: block;
    margin: 0 auto;
    background-color: ghostwhite;
    color: red;    
     
}

.create-ur-sfp-account-form > h4 {
  margin: 53px 0;
  text-align: center;
  width: 87%;
}
.create-ur-sfp-account-form ul li {
  height: auto;
  list-style: outside none none;
  margin-bottom: 7px;
  overflow: hidden;
}
.create-ur-sfp-account-form ul li label {
  color: #2e3641;
  display: block;
  float: left;
  font-size: 13px;
  height: 50px;
  line-height: 50px;
  width: 144px;
}
.create-ur-sfp-account-form ul li input[type="text"], .create-ur-sfp-account-form ul li input[type="password"] {
  border: 1px solid #ccc;
  height: 50px;
  text-indent: 5px;
  width:50%;
}
.create-ur-sfp-account-form > ul {
  padding: 0;
}
.sfp-accnt h1 {font-size: 33px; padding: 0 11% 0 0;text-align: right;}
.has-js .label_check {
	background: url(../image_gallery/check-off.jpg) no-repeat left top;
	height: 32px;
	padding: 0 0 0 44px;
	line-height: 32px;
}
.has-js .label_check input, .has-js .label_radio input{
	position: absolute;
	left: -9999px;
}
.has-js label.c_on {
	background: url(../image_gallery/check-on.jpg) no-repeat;
}

.create-ur-sfp-account-form ul li span a {
  color: #a9c5bc;
  display: block;
  float: left;
  margin-top: 4px;
}
.create-ur-sfp-account-form ul li div img {
  display: block;
  float: left;
  margin-left: 7px;
  vertical-align: bottom;
}
.create-ur-sfp-account-form ul li div p {
  float: left;
}

.create-ur-sfp-account-form ul li span fieldset > label {
  margin-right: 8px;
  width: auto;
}
.prefer-to-login a img {
  margin: 0 0 2px;
  width: 55px;
}
.prefer-to-login > a {
  margin-left: 5px;
}
.prefer-to-login {
  float: left;
  font-size: 12px;
  text-align: center;
}

#click-pass{
color:red;
}
</style>




