 <script>
  function fbs_click()
    {
    var base_url = window.location.origin;
    u=base_url+"/index/accountsignup"
    t='smartfanpage';
    var child = window.open('http://www.facebook.com/sharer.php?u='+encodeURIComponent(u)+'&t='+encodeURIComponent(t),'sharer','toolbar=0,status=0,width=626,height=436');
    }
    
      function twt_click()
    {
        var base_url = window.location.origin;
       u=base_url+"/index/accountsignup"
     t='smartfanpage';
    var child = window.open('http://twitter.com/share?u='+encodeURIComponent(u)+'&t='+encodeURIComponent(t),'sharer','toolbar=0,status=0,width=626,height=436');   
    }
    
    function linkedinButton(){
    var base_url = window.location.origin;
   var articleUrl = encodeURIComponent(base_url+'/index/accountsignup');
       var articleTitle = encodeURIComponent('smartfanpage');
       var articleSummary = encodeURIComponent('publisher sign up');
       var articleSource = encodeURIComponent('best');
       var goto = 'http://www.linkedin.com/shareArticle?mini=true'+
           '&url='+articleUrl+
           '&title='+articleTitle+
           '&summary='+articleSummary+
           '&source='+articleSource;
       window.open(goto, "LinkedIn", "width=660,height=600,scrollbars=yes;resizable=no");         
}
  </script>




<div  class="site">
  <div class="container-fluid"> 
     <!--===== start banner ===-->
    <div class="row">
      <div class="banner_contact">
        <ul class="social_icon">
          <li><a href="#">Share this website</a></li>
          <li><a href="javascript:void(0)" onclick="return fbs_click()"></a> <a style="cursor:pointer" onclick="return twt_click()"></a> <a style="cursor:pointer" onclick="return linkedinButton()"></a></li>
        </ul> <!--=== social icon ===-->
        <div class="cont-title sfp-accnt">
        <h1>Publish great campaigns.</h1>
        </div>
      </div>
      
    </div><!--===== end banner ===--> 
    

     <div class="row">
     <div class="col-lg-12">
     <div class="create-ur-sfp-account-form col-lg-8 col-lg-offset-2">
     <h4>Create your Smart fanpage account</h4>
     <div class="create-ur-sfp-account-form">
     <ul>
     <li>
     <label for=""> First name <span>*</span></label>
     <input type="text" id="fname" name="" />
     </li>
     
     <li>
     <label for="">Last name <span>*</span></label>
     <input type="text" id="lname" name="" />
     </li>
     
     
     
     <li>
     <label for="">E-mailadress<span>*</span></label>
     <input type="text" id="username" name="" />
     </li>
   
     <li> 
     <label for="">&nbsp;</label>
     <span><fieldset class="checkboxes check">
                                                
                          <label class="label_check"><input name="sample" value="1" id="sfpchk1" type="checkbox" /> <p>I accept the</p></label><a href="#">terms and conditions</a>                            
                                                     
                        </fieldset></span>
     
     </li>
     <li>
     <label>&nbsp;</label>
     <a class="continue" onclick="getpassword_throughemail()" href="javascript:void(0)">get password</a></li>
     <li id="email_exists" style="display: none;"><label></label><p>* Email already exists</p></li>
     <li id="mail_sent" style="display: none;"><label></label><p>Check your inbox to set password</p></li>
       <li>
     <label for="">&nbsp;</label>
    <div class="prefer-to-login"><p>I prefer to Register with</p><a onclick="logInWithYourFaceBookAccount()" href="javascript:void(0)"><img src="<?php echo $this->basePath('img/fb-icon - Copywe.png');?>"/></a></div>
     </li>
     </ul>
     </div>
     </div>
     </div>
     
     </div>

      
      
<style type="text/css">
.banner_contact
{
 background: url(../img/store_banner-modified.jpg) no-repeat top center;
    display: block;
    height: 330px;
    margin: auto;
    overflow: hidden;
    width: 100%;

}
.continue {
  background: none repeat scroll 0 0 #252b34;
  border: medium none;
  color: #fff;
  display: block;
  font-family: "ubuntubold";
  font-size: 16px;
  height: 52px;
  line-height: 52px;
  margin: 0 auto 12px;
  text-align: center;
  text-transform: uppercase;
  width: 47%;
  float: left;
}
.create-ur-sfp-account-form > ul {
  padding: 0;
}
.prefer-to-login > a {
  display: block;
  float: left;
  margin: 3px 0 0;
}
 .alert-info {
    width: 220px;
    padding: 10px;
    border: 5px solid gray;
    text-align: center;
    display: block;
    margin: 0 auto;
    background-color: ghostwhite;
    color: red;    
     
}

.create-ur-sfp-account-form > h4 {
  margin: 53px 0;
}
.create-ur-sfp-account-form ul li {
  height: auto;
  list-style: outside none none;
  margin-bottom: 7px;
  overflow: hidden;
}
.create-ur-sfp-account-form ul li label {
  color: #2e3641;
  display: block;
  float: left;
  font-size: 13px;
  height: 50px;
  line-height: 50px;
  width: 150px;
}
.create-ur-sfp-account-form ul li input[type="text"], .create-ur-sfp-account-form ul li input[type="password"] {
  border: 1px solid #ccc;
  height: 50px;
  text-indent: 5px;
  width: 326px;
}

.sfp-accnt h1 {font-size: 33px; padding: 0 11% 0 0;text-align: right;}
.has-js .label_check {
	background: url(../image_gallery/check-off.jpg) no-repeat left top;
	height: 32px;
	padding: 0 0 0 44px;
	line-height: 32px;
}
.has-js .label_check input, .has-js .label_radio input{
	position: absolute;
	left: -9999px;
}
.has-js label.c_on {
	background: url(../image_gallery/check-on.jpg) no-repeat;
}

.create-ur-sfp-account-form ul li span a {
  color: #a9c5bc;
  display: block;
  float: left;
  margin-top: 4px;
}
.create-ur-sfp-account-form ul li div img {
  display: block;
  float: left;
  margin-left: 0;
  vertical-align: bottom;
}
.create-ur-sfp-account-form ul li div p {
  float: left;
}

.create-ur-sfp-account-form ul li span fieldset > label {
  margin-right: 8px;
  width: auto;
}
.prefer-to-login a img {
  display: block;
  margin: -2px 0 0;
  width: 52px;
}
.prefer-to-login > a {
  margin-left: 5px;
}
.prefer-to-login {
  float: left;
  font-size: 12px;
  text-align: center;
}
.create-ur-sfp-account-form ul li:nth-child(2) label {
  height: 36px;
  margin-bottom: 0;
}
</style>




