
<div  class="site">
  <div class="container-fluid"> 
    <!--===== start banner ===-->
  <div class="row">  
  <div class="banner case-studies-bg">
        <ul class="social_icon2">
          <li><a href="#">Share this website</a></li>
          <li><a href="#"></a> <a href="#"></a> <a href="#"></a></li>
        </ul>
        <div class="banner_caption4 col-md-8" >
          <h1 class="">CASE STUDIES</h1>
          
           </div>
      </div>
    
    </div>
    <div class="row">
     <div class="col-lg-12 case-studies">
      <?php foreach ($contentpass as $p) :?>
     <div class="case-studies-wrapper clearfix col-lg-6 col-sm-6">
      <?php

    if($p->VedioPath != ''  )
  
    {
        $vedio =$p->VedioPath ;
        
    
    /*if($vediourl != '' || $imageurl !='')
    if($vediourl != '' || $imageurl =='')
    if($vediourl == '' || $imageurl !='')*/
    if (preg_match('%(?:youtube(?:-nocookie)?\.com/(?:[^/]+/.+/|(?:v|e(?:mbed)?)/|.*[?&]v=)|youtu\.be/)([^"&?/ ]{11})%i', $vedio, $match)) {
    $video_id = $match[1];
    }
   ?>     
     
         
               
     <?php
            }
        else{
        ?>
        <img src="<?php echo $p->imgPath;?>" alt="" style="width: 100%;">

<?php } ?>
                
               
      <div>
      <h3><?php echo $p->vedioHeader;?></h3>
      <p><?php echo $p->VedioDescription;?></p>
      </div>          
                
     </div>
     <?php endforeach; ?>
     
     </div> 
      
  
