




<div  class="site">
  <div class="container-fluid"> 
  <div class="row"> 
    
      <div class="banner_contact">
        <ul class="social_icon">
          <li><a href="#">Share this website</a></li>
          <li><a href="#"></a> <a href="#"></a> <a href="#"></a></li>
        </ul> <!--=== social icon ===-->
        <div class="cont-title sfp-accnt">
        <h1>Publish great campaigns.</h1>
        </div>
      </div>
      
    
    

     
     <div class="create-ur-sfp-account-form col-lg-8 col-lg-offset-2 col-md-offset-2">
     <div class="create-ur-sfp-account-form">
     
     <ul>
     <li><h4>Choose your password</h4></li>
     <li><label for="">Email Address :</label><label id="username"><?php echo $contentpass->email; ?></label></li>
     <li>
     <label for="">Type your password :</label>
     <input type="password" id="password" name="" />
     </li>
<li>
     <label for="">Retype your password :</label>
     <input type="password" id="repassword" name="" />
     </li>
     <li><a class="continue" onclick="updatepass()" href="javascript:void(0)">Let's get started</a></li>
     </ul>
     </div>
     </div>
     



</div>
</div>
</div>
      
      
<style type="text/css">


.banner_contact{
	background:url(../../img/store_banner-modified.jpg) no-repeat top center;
	width:100%;
	background-size:cover;
	overflow:hidden;
	margin:auto;
	min-height: 420px;
}



.continue {
  background: none repeat scroll 0 0 #252b34;
  border: medium none;
  color: #fff;
  display: inline-block;
  font-family: "ubuntubold";
  font-size: 16px;
  height: 52px;
  line-height: 52px;
  margin: 0 0 0 150px;
  text-align: center;
  text-transform: uppercase;
  width: 200px;
}

 .alert-info {
    width: 220px;
    padding: 10px;
    border: 5px solid gray;
    text-align: center;
    display: block;
    margin: 0 auto;
    background-color: ghostwhite;
    color: red;    
     
}

.create-ur-sfp-account-form h4 {
  margin: 53px 0;
}
.create-ur-sfp-account-form ul li {
  height: auto;
  list-style: outside none none;
  margin-bottom: 7px;
  overflow: hidden;
}
.create-ur-sfp-account-form ul li label {
  color: #2e3641;
  display: block;
  float: left;
  font-size: 13px;
  height: 50px;
  line-height: 50px;
  width: 150px;
}
.create-ur-sfp-account-form ul li input[type="text"], .create-ur-sfp-account-form ul li input[type="password"] {
  border: 1px solid #ccc;
  height: 50px;
  text-indent: 5px;
  width: 460px;
}

.sfp-accnt h1 {font-size: 33px; padding: 0 11% 0 0;text-align: right;}
.has-js .label_check {
	background: url(../image_gallery/check-off.jpg) no-repeat left top;
	height: 32px;
	padding: 0 0 0 44px;
	line-height: 32px;
}
.has-js .label_check input, .has-js .label_radio input{
	position: absolute;
	left: -9999px;
}
.has-js label.c_on {
	background: url(../image_gallery/check-on.jpg) no-repeat;
}
</style>




