<?php echo "this is testing"; ?>
<div  class="site">
  <div class="container-fluid"> 
    <!--===== start banner ===-->
    <div class="row">
      <div class="banner">
        <ul class="social_icon">
          <li><a href="#">Share this website</a></li>
          <li><a href="#"></a> <a href="#"></a> <a href="#"></a></li>
        </ul>
        
        
        
        <div class="banner_caption col-md-8" >
          <h1 class="fittext2">Smart Fanpage<br>
            PUBLISH. BOOST. ENGAGE! </h1>
          <h2>Find and customize the most challenging<br>
            and effective online campaign templates</h2>
          <a href="#">Sign up free</a> </div>
      </div>
      
    </div>
    <!--===== end banner ===--> 
    <div class="container-fluid" > 
      
      <!--===== start dropdown ===-->
      <div class="row" >
        <p class="top_heading col-md-12" id="fly-it">What kind of campaign are you looking for?</p>
        <div class="col-md-3 col-xs-12" >
          <select id="standard-dropdown" name="standard-dropdown" class="custom-class1 custom-class2">
            <option value="1" class="test-class-1">Keyword</option>
            <option value="1" class="test-class-1">dfgsdfgsdgfd</option>
            <option value="1" class="test-class-1">Select category</option>
          </select>
        </div>
        <div class="col-md-3 col-xs-12">
          <select id="standard-dropdown" name="standard-dropdown" class="custom-class1 custom-class2">
            <option value="1" class="test-class-1">Select category</option>
            <option value="1" class="test-class-1">dfgsdfgsdgfd</option>
            <option value="1" class="test-class-1">Publishing platform</option>
          </select>
        </div>
        <div class="col-md-3 col-xs-12">
          <select id="standard-dropdown" name="standard-dropdown" class="custom-class1 custom-class2">
            <option value="1" class="test-class-1">Publishing platform</option>
            <option value="1" class="test-class-1">dfgsdfgsdgfd</option>
            <option value="1" class="test-class-1">Price</option>
          </select>
        </div>
        
        
        
        
        
        <!--<form class="navbar-form col-md-2 col-xs-12">
            <input type="text" placeholder="Search..." class="form-control">
          </form>-->
      <!--  <div class="col-md-2 col-xs-12"><a href="#" class="discover_button">Discover</a></div>-->
        <div class="col-md-1 col-xs-12 pull-right"><a href="#" class="refresh_button"></a></div>
        <div class="col-md-3 col-xs-12 pull-right">
         
          
          <div class="input-group cust-search">
            <input class="form-control" placeholder="Search" name="srch-term" id="srch-term" type="text">
            <div class="input-group-btn">
              <button class="btn btn-default" type="submit"><span class="glyphicon glyphicon-search"></span></button>
            </div>
          </div>
        
         
        </div>
       <!-- <div class="col-md-2 col-xs-12"><a href="#" class="see_all">No filter
          see all</a></div>-->
      </div>
      <!--===== end dropdown ===--> 
      <!--===== start first caraousal ===-->
      
      <div class="row row_margin">
        <hr class="mar-eaighteen">
        <h3>Hot one hundred</h3>
        <div class="slider_wrap col-lg-12 col-xs-12" >
          <div class="carousel-normal">
            <div class="owl-demo" >
              <div class="item small_carausal"> <strong>Blog competition</strong> <span><img src="<?php echo $this->basePath('img/slider_img.jpg') ?>" alt="" /></span>
                <div>
                  <p>Blog / Creative / Writing /  Facebook app</p>
                  <strong>Author: Studio 365 (Amsterdam)</strong> <span> <img src="<?php echo $this->basePath('img/rate.png') ?>" alt="" /> <img src="<?php echo $this->basePath('img/rate.png') ?>" alt="" /> <img src="<?php echo $this->basePath('img/rate.png') ?>" alt="" /> <img src="<?php echo $this->basePath('img/unrate2.png') ?>" alt="" /> <img src="<?php echo $this->basePath('img/unrate2.png') ?>" alt="" /> </span> <a href="#">Use now</a> <b>€19</b> </div>
              </div>
              <div class="item small_carausal"> <strong>Blog competition</strong> <span><img src="<?php echo $this->basePath('img/slider_img.jpg') ?>" alt="" /></span>
                <div>
                  <p>Blog / Creative / Writing /  Facebook app</p>
                  <strong>Author: Studio 365 (Amsterdam)</strong> <span> <img src="<?php echo $this->basePath('img/rate.png') ?>" alt="" /> <img src="<?php echo $this->basePath('img/rate.png') ?>" alt="" /> <img src="<?php echo $this->basePath('img/rate.png') ?>" alt="" /> <img src="<?php echo $this->basePath('img/unrate2.png') ?>" alt="" /> <img src="<?php echo $this->basePath('img/unrate2.png') ?>" alt="" /> </span> <a href="#">Use now</a> <b>€19</b> </div>
              </div>
              <div class="item small_carausal"> <strong>Blog competition</strong> <span><img src="<?php echo $this->basePath('img/slider_img.jpg') ?>" alt="" /></span>
                <div>
                  <p>Blog / Creative / Writing /  Facebook app</p>
                  <strong>Author: Studio 365 (Amsterdam)</strong> <span> <img src="<?php echo $this->basePath('img/rate.png') ?>" alt="" /> <img src="<?php echo $this->basePath('img/rate.png') ?>" alt="" /> <img src="<?php echo $this->basePath('img/rate.png') ?>" alt="" /> <img src="<?php echo $this->basePath('img/unrate2.png') ?>" alt="" /> <img src="<?php echo $this->basePath('img/unrate2.png') ?>" alt="" /> </span> <a href="#">Use now</a> <b>€19</b> </div>
              </div>
              <div class="item small_carausal"> <strong>Blog competition</strong> <span><img src="<?php echo $this->basePath('img/slider_img.jpg') ?>" alt="" /></span>
                <div>
                  <p>Blog / Creative / Writing /  Facebook app</p>
                  <strong>Author: Studio 365 (Amsterdam)</strong> <span> <img src="<?php echo $this->basePath('img/rate.png') ?>" alt="" /> <img src="<?php echo $this->basePath('img/rate.png') ?>" alt="" /> <img src="<?php echo $this->basePath('img/rate.png') ?>" alt="" /> <img src="<?php echo $this->basePath('img/unrate2.png') ?>" alt="" /> <img src="<?php echo $this->basePath('img/unrate2.png') ?>" alt="" /> </span> <a href="#">Use now</a> <b>€19</b> </div>
              </div>
              <div class="item small_carausal"> <strong>Blog competition</strong> <span><img src="<?php echo $this->basePath('img/slider_img.jpg') ?>" alt="" /></span>
                <div>
                  <p>Blog / Creative / Writing /  Facebook app</p>
                  <strong>Author: Studio 365 (Amsterdam)</strong> <span> <img src="<?php echo $this->basePath('img/rate.png') ?>" alt="" /> <img src="<?php echo $this->basePath('img/rate.png') ?>" alt="" /> <img src="<?php echo $this->basePath('img/rate.png') ?>" alt="" /> <img src="<?php echo $this->basePath('img/unrate2.png') ?>" alt="" /> <img src="<?php echo $this->basePath('img/unrate2.png') ?>" alt="" /> </span> <a href="#">Use now</a> <b>€19</b> </div>
              </div>
              <div class="item small_carausal"> <strong>Blog competition</strong> <span><img src="<?php echo $this->basePath('img/slider_img.jpg') ?>" alt="" /></span>
                <div>
                  <p>Blog / Creative / Writing /  Facebook app</p>
                  <strong>Author: Studio 365 (Amsterdam)</strong> <span> <img src="<?php echo $this->basePath('img/rate.png') ?>" alt="" /> <img src="<?php echo $this->basePath('img/rate.png') ?>" alt="" /> <img src="<?php echo $this->basePath('img/rate.png') ?>" alt="" /> <img src="<?php echo $this->basePath('img/unrate2.png') ?>" alt="" /> <img src="<?php echo $this->basePath('img/unrate2.png') ?>" alt="" /> </span> <a href="#">Use now</a> <b>€19</b> </div>
              </div>
              <div class="item small_carausal"> <strong>Blog competition</strong> <span><img src="<?php echo $this->basePath('img/slider_img.jpg') ?>" alt="" /></span>
                <div>
                  <p>Blog / Creative / Writing /  Facebook app</p>
                  <strong>Author: Studio 365 (Amsterdam)</strong> <span> <img src="<?php echo $this->basePath('img/rate.png') ?>" alt="" /> <img src="<?php echo $this->basePath('img/rate.png') ?>" alt="" /> <img src="<?php echo $this->basePath('img/rate.png') ?>" alt="" /> <img src="<?php echo $this->basePath('img/unrate2.png') ?>" alt="" /> <img src="<?php echo $this->basePath('img/unrate2.png') ?>" alt="" /> </span> <a href="#">Use now</a> <b>€19</b> </div>
              </div>
              <div class="item small_carausal"> <strong>Blog competition</strong> <span><img src="<?php echo $this->basePath('img/slider_img.jpg') ?>" alt="" /></span>
                <div>
                  <p>Blog / Creative / Writing /  Facebook app</p>
                  <strong>Author: Studio 365 (Amsterdam)</strong> <span> <img src="<?php echo $this->basePath('img/rate.png') ?>" alt="" /> <img src="<?php echo $this->basePath('img/rate.png') ?>" alt="" /> <img src="<?php echo $this->basePath('img/rate.png') ?>" alt="" /> <img src="<?php echo $this->basePath('img/unrate2.png') ?>" alt="" /> <img src="<?php echo $this->basePath('img/unrate2.png') ?>" alt="" /> </span> <a href="#">Use now</a> <b>€19</b> </div>
              </div>
            </div>
          </div>
          <div class="carousel_nav"> <a class="carousel_nav_prev">prev</a> <a class="carousel_nav_next">next</a> </div>
        </div>
      </div>
      <!--===== end first caraousal ===--> 
      <!--===== start secoend caraousal ===-->
      <div class="row row_margin"  id="spotlight_section">
        <h3>In the spotlight</h3>
        <div class="owl-demo2 owl-carousel col-lg-12 col-xs-12">
          <div class="item"> <img src="<?php echo $this->basePath('img/slider1.jpg') ?>" alt="" />
            <div class="text_option">
              <h3>Restaurant</h3>
              <h2>coupon give-away</h2>
              <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc suscipit est at massa commodo porttitor. Nulla dictum pharetra libero eget facilisis. Lorem ipsum dolor amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc suscipit est at massa commodo porttitor. Nulla dictum pharetra libero eget facilisis. Lorem ipsum dolor amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc suscipit est at massa commodo porttitor.</p>
              <a href="#">Use now</a><b>€19</b> </div>
          </div>
          <div class="item"> <img src="<?php echo $this->basePath('img/slider1.jpg') ?>" alt="" />
            <div class="text_option">
              <h3>Restaurant</h3>
              <h2>coupon give-away</h2>
              <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc suscipit est at massa commodo porttitor. Nulla dictum pharetra libero eget facilisis. Lorem ipsum dolor amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc suscipit est at massa commodo porttitor. Nulla dictum pharetra libero eget facilisis. Lorem ipsum dolor amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc suscipit est at massa commodo porttitor.</p>
              <a href="#">Use now</a><b>€19</b> </div>
          </div>
          <div class="item"> <img src="<?php echo $this->basePath('img/slider1.jpg') ?>" alt="" />
            <div class="text_option">
              <h3>Restaurant</h3>
              <h2>coupon give-away</h2>
              <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc suscipit est at massa commodo porttitor. Nulla dictum pharetra libero eget facilisis. Lorem ipsum dolor amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc suscipit est at massa commodo porttitor. Nulla dictum pharetra libero eget facilisis. Lorem ipsum dolor amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc suscipit est at massa commodo porttitor.</p>
              <a href="#">Use now</a><!--<b>€19</b>--> </div>
          </div>
        </div>
      </div>
      
      <!--===== end secoend caraousal ===--> 
      <!--===== start third caraousal ===-->
      <div class="row row_margin">
        <h3> Top rated </h3>
        <div class="slider_wrap col-lg-12 col-xs-12" >
          <div class="carousel-normal">
            <div class="owl-demo" >
              <div class="item small_carausal"> <strong>Blog competition</strong> <span><img src="<?php echo $this->basePath('img/slider_img.jpg') ?>" alt="" /></span>
                <div>
                  <p>Blog / Creative / Writing /  Facebook app</p>
                  <strong>Author: Studio 365 (Amsterdam)</strong> <span> <img src="<?php echo $this->basePath('img/rate.png') ?>" alt="" /> <img src="<?php echo $this->basePath('img/rate.png') ?>" alt="" /> <img src="<?php echo $this->basePath('img/rate.png') ?>" alt="" /> <img src="<?php echo $this->basePath('img/unrate2.png') ?>" alt="" /> <img src="<?php echo $this->basePath('img/unrate2.png') ?>" alt="" /> </span> <a href="#">Use now</a> <b>€19</b> </div>
              </div>
              <div class="item small_carausal"> <strong>Blog competition</strong> <span><img src="<?php echo $this->basePath('img/slider_img.jpg') ?>" alt="" /></span>
                <div>
                  <p>Blog / Creative / Writing /  Facebook app</p>
                  <strong>Author: Studio 365 (Amsterdam)</strong> <span> <img src="<?php echo $this->basePath('img/rate.png') ?>" alt="" /> <img src="<?php echo $this->basePath('img/rate.png') ?>" alt="" /> <img src="<?php echo $this->basePath('img/rate.png') ?>" alt="" /> <img src="<?php echo $this->basePath('img/unrate2.png') ?>" alt="" /> <img src="<?php echo $this->basePath('img/unrate2.png') ?>" alt="" /> </span> <a href="#">Use now</a> <b>€19</b> </div>
              </div>
              <div class="item small_carausal"> <strong>Blog competition</strong> <span><img src="<?php echo $this->basePath('img/slider_img.jpg') ?>" alt="" /></span>
                <div>
                  <p>Blog / Creative / Writing /  Facebook app</p>
                  <strong>Author: Studio 365 (Amsterdam)</strong> <span> <img src="<?php echo $this->basePath('img/rate.png') ?>" alt="" /> <img src="<?php echo $this->basePath('img/rate.png') ?>" alt="" /> <img src="<?php echo $this->basePath('img/rate.png') ?>" alt="" /> <img src="<?php echo $this->basePath('img/unrate2.png') ?>" alt="" /> <img src="<?php echo $this->basePath('img/unrate2.png') ?>" alt="" /> </span> <a href="#">Use now</a> <b>€19</b> </div>
              </div>
              <div class="item small_carausal"> <strong>Blog competition</strong> <span><img src="<?php echo $this->basePath('img/slider_img.jpg') ?>" alt="" /></span>
                <div>
                  <p>Blog / Creative / Writing /  Facebook app</p>
                  <strong>Author: Studio 365 (Amsterdam)</strong> <span> <img src="<?php echo $this->basePath('img/rate.png') ?>" alt="" /> <img src="<?php echo $this->basePath('img/rate.png') ?>" alt="" /> <img src="<?php echo $this->basePath('img/rate.png') ?>" alt="" /> <img src="<?php echo $this->basePath('img/unrate2.png') ?>" alt="" /> <img src="<?php echo $this->basePath('img/unrate2.png') ?>" alt="" /> </span> <a href="#">Use now</a> <b>€19</b> </div>
              </div>
              <div class="item small_carausal"> <strong>Blog competition</strong> <span><img src="<?php echo $this->basePath('img/slider_img.jpg') ?>" alt="" /></span>
                <div>
                  <p>Blog / Creative / Writing /  Facebook app</p>
                  <strong>Author: Studio 365 (Amsterdam)</strong> <span> <img src="<?php echo $this->basePath('img/rate.png') ?>" alt="" /> <img src="<?php echo $this->basePath('img/rate.png') ?>" alt="" /> <img src="<?php echo $this->basePath('img/rate.png') ?>" alt="" /> <img src="<?php echo $this->basePath('img/unrate2.png') ?>" alt="" /> <img src="<?php echo $this->basePath('img/unrate2.png') ?>" alt="" /> </span> <a href="#">Use now</a> <b>€19</b> </div>
              </div>
              <div class="item small_carausal"> <strong>Blog competition</strong> <span><img src="<?php echo $this->basePath('img/slider_img.jpg') ?>" alt="" /></span>
                <div>
                  <p>Blog / Creative / Writing /  Facebook app</p>
                  <strong>Author: Studio 365 (Amsterdam)</strong> <span> <img src="<?php echo $this->basePath('img/rate.png') ?>" alt="" /> <img src="<?php echo $this->basePath('img/rate.png') ?>" alt="" /> <img src="<?php echo $this->basePath('img/rate.png') ?>" alt="" /> <img src="<?php echo $this->basePath('img/unrate2.png') ?>" alt="" /> <img src="<?php echo $this->basePath('img/unrate2.png') ?>" alt="" /> </span> <a href="#">Use now</a> <b>€19</b> </div>
              </div>
              <div class="item small_carausal"> <strong>Blog competition</strong> <span><img src="<?php echo $this->basePath('img/slider_img.jpg') ?>" alt="" /></span>
                <div>
                  <p>Blog / Creative / Writing /  Facebook app</p>
                  <strong>Author: Studio 365 (Amsterdam)</strong> <span> <img src="<?php echo $this->basePath('img/rate.png') ?>" alt="" /> <img src="<?php echo $this->basePath('img/rate.png') ?>" alt="" /> <img src="<?php echo $this->basePath('img/rate.png') ?>" alt="" /> <img src="<?php echo $this->basePath('img/unrate2.png') ?>" alt="" /> <img src="<?php echo $this->basePath('img/unrate2.png') ?>" alt="" /> </span> <a href="#">Use now</a> <b>€19</b> </div>
              </div>
              <div class="item small_carausal"> <strong>Blog competition</strong> <span><img src="<?php echo $this->basePath('img/slider_img.jpg') ?>" alt="" /></span>
                <div>
                  <p>Blog / Creative / Writing /  Facebook app</p>
                  <strong>Author: Studio 365 (Amsterdam)</strong> <span> <img src="<?php echo $this->basePath('img/rate.png') ?>" alt="" /> <img src="<?php echo $this->basePath('img/rate.png') ?>" alt="" /> <img src="<?php echo $this->basePath('img/rate.png') ?>" alt="" /> <img src="<?php echo $this->basePath('img/unrate2.png') ?>" alt="" /> <img src="<?php echo $this->basePath('img/unrate2.png') ?>" alt="" /> </span> <a href="#">Use now</a> <b>€19</b> </div>
              </div>
            </div>
          </div>
          <div class="carousel_nav"> <a class="carousel_nav_prev">prev</a> <a class="carousel_nav_next">next</a> </div>
        </div>
      </div>
      <!--===== end third caraousal ===--> 
      </div>
     
      <!--===== start forth caraousal ===-->
      <div class="row row_margin carausal_bg">
        <h3>New releases</h3>
        <div class="slider_wrap col-lg-12 col-xs-12" >
          <div class="carousel-normal">
            <div class="owl-demo" >
              <div class="item small_carausal"> <strong>Blog competition</strong> <span><img src="<?php echo $this->basePath('img/slider_img.jpg') ?>" alt="" /></span>
                <div>
                  <p>Blog / Creative / Writing /  Facebook app</p>
                  <strong>Author: Studio 365 (Amsterdam)</strong> <span> <img src="<?php echo $this->basePath('img/rate.png') ?>" alt="" /> <img src="<?php echo $this->basePath('img/rate.png') ?>" alt="" /> <img src="<?php echo $this->basePath('img/rate.png') ?>" alt="" /> <img src="<?php echo $this->basePath('img/unrate2.png') ?>" alt="" /> <img src="<?php echo $this->basePath('img/unrate2.png') ?>" alt="" /> </span> <a href="#">Use now</a> <b>€19</b> </div>
              </div>
              <div class="item small_carausal"> <strong>Blog competition</strong> <span><img src="<?php echo $this->basePath('img/slider_img.jpg') ?>" alt="" /></span>
                <div>
                  <p>Blog / Creative / Writing /  Facebook app</p>
                  <strong>Author: Studio 365 (Amsterdam)</strong> <span> <img src="<?php echo $this->basePath('img/rate.png') ?>" alt="" /> <img src="<?php echo $this->basePath('img/rate.png') ?>" alt="" /> <img src="<?php echo $this->basePath('img/rate.png') ?>" alt="" /> <img src="<?php echo $this->basePath('img/unrate2.png') ?>" alt="" /> <img src="<?php echo $this->basePath('img/unrate2.png') ?>" alt="" /> </span> <a href="#">Use now</a> <b>€19</b> </div>
              </div>
              <div class="item small_carausal"> <strong>Blog competition</strong> <span><img src="<?php echo $this->basePath('img/slider_img.jpg') ?>" alt="" /></span>
                <div>
                  <p>Blog / Creative / Writing /  Facebook app</p>
                  <strong>Author: Studio 365 (Amsterdam)</strong> <span> <img src="<?php echo $this->basePath('img/rate.png') ?>" alt="" /> <img src="<?php echo $this->basePath('img/rate.png') ?>" alt="" /> <img src="<?php echo $this->basePath('img/rate.png') ?>" alt="" /> <img src="<?php echo $this->basePath('img/unrate2.png') ?>" alt="" /> <img src="<?php echo $this->basePath('img/unrate2.png') ?>" alt="" /> </span> <a href="#">Use now</a> <b>€19</b> </div>
              </div>
              <div class="item small_carausal"> <strong>Blog competition</strong> <span><img src="<?php echo $this->basePath('img/slider_img.jpg') ?>" alt="" /></span>
                <div>
                  <p>Blog / Creative / Writing /  Facebook app</p>
                  <strong>Author: Studio 365 (Amsterdam)</strong> <span> <img src="<?php echo $this->basePath('img/rate.png') ?>" alt="" /> <img src="<?php echo $this->basePath('img/rate.png') ?>" alt="" /> <img src="<?php echo $this->basePath('img/rate.png') ?>" alt="" /> <img src="<?php echo $this->basePath('img/unrate2.png') ?>" alt="" /> <img src="<?php echo $this->basePath('img/unrate2.png') ?>" alt="" /> </span> <a href="#">Use now</a> <b>€19</b> </div>
              </div>
              <div class="item small_carausal"> <strong>Blog competition</strong> <span><img src="<?php echo $this->basePath('img/slider_img.jpg') ?>" alt="" /></span>
                <div>
                  <p>Blog / Creative / Writing /  Facebook app</p>
                  <strong>Author: Studio 365 (Amsterdam)</strong> <span> <img src="<?php echo $this->basePath('img/rate.png') ?>" alt="" /> <img src="<?php echo $this->basePath('img/rate.png') ?>" alt="" /> <img src="<?php echo $this->basePath('img/rate.png') ?>" alt="" /> <img src="<?php echo $this->basePath('img/unrate2.png') ?>" alt="" /> <img src="<?php echo $this->basePath('img/unrate2.png') ?>" alt="" /> </span> <a href="#">Use now</a> <b>€19</b> </div>
              </div>
              <div class="item small_carausal"> <strong>Blog competition</strong> <span><img src="<?php echo $this->basePath('img/slider_img.jpg') ?>" alt="" /></span>
                <div>
                  <p>Blog / Creative / Writing /  Facebook app</p>
                  <strong>Author: Studio 365 (Amsterdam)</strong> <span> <img src="<?php echo $this->basePath('img/rate.png') ?>" alt="" /> <img src="<?php echo $this->basePath('img/rate.png') ?>" alt="" /> <img src="<?php echo $this->basePath('img/rate.png') ?>" alt="" /> <img src="<?php echo $this->basePath('img/unrate2.png') ?>" alt="" /> <img src="<?php echo $this->basePath('img/unrate2.png') ?>" alt="" /> </span> <a href="#">Use now</a> <b>€19</b> </div>
              </div>
              <div class="item small_carausal"> <strong>Blog competition</strong> <span><img src="<?php echo $this->basePath('img/slider_img.jpg') ?>" alt="" /></span>
                <div>
                  <p>Blog / Creative / Writing /  Facebook app</p>
                  <strong>Author: Studio 365 (Amsterdam)</strong> <span> <img src="<?php echo $this->basePath('img/rate.png') ?>" alt="" /> <img src="<?php echo $this->basePath('img/rate.png') ?>" alt="" /> <img src="<?php echo $this->basePath('img/rate.png') ?>" alt="" /> <img src="<?php echo $this->basePath('img/unrate2.png') ?>" alt="" /> <img src="<?php echo $this->basePath('img/unrate2.png') ?>" alt="" /> </span> <a href="#">Use now</a> <b>€19</b> </div>
              </div>
              <div class="item small_carausal"> <strong>Blog competition</strong> <span><img src="<?php echo $this->basePath('img/slider_img.jpg') ?>" alt="" /></span>
                <div>
                  <p>Blog / Creative / Writing /  Facebook app</p>
                  <strong>Author: Studio 365 (Amsterdam)</strong> <span> <img src="<?php echo $this->basePath('img/rate.png') ?>" alt="" /> <img src="<?php echo $this->basePath('img/rate.png') ?>" alt="" /> <img src="<?php echo $this->basePath('img/rate.png') ?>" alt="" /> <img src="<?php echo $this->basePath('img/unrate2.png') ?>" alt="" /> <img src="<?php echo $this->basePath('img/unrate2.png') ?>" alt="" /> </span> <a href="#">Use now</a> <b>€19</b> </div>
              </div>
            </div>
          </div>
          <div class="carousel_nav"> <a class="carousel_nav_prev">prev</a> <a class="carousel_nav_next">next</a> </div>
        </div>
      </div>
      <!--===== end forth caraousal ===--> 
       <div class="container-fluid">
      <!--===== start Wall of fame ===-->
      <div class="row row_text row_margin">
        <h4>Wall of fame</h4>
        <p>Smart Fanpage is a community with design & development agencies. These agencies provide our platform of beautiful campaign templates 
          for you to use and transform into your own campaign... suited for your business or needs. We've recently given these fresh new producers 
          a warm welcome:</p>
        <div id="show" class="introduction-section col-lg-12" style="margin-top:24px;">
          <ul class="introduction-details">
            <li class="col-lg-4 col-sm-4"><img alt="" src="<?php echo $this->basePath('img/fame.jpg') ?>"> <span>Studio 365</span> </li>
            <li  class="col-lg-4 col-sm-4"><img alt="" src="<?php echo $this->basePath('img/fame2.jpg') ?>"><span style="float:none;">Kittyhawk</span></li>
            <li class="col-lg-4 col-sm-4"><img alt="" src="<?php echo $this->basePath('img/fame3.jpg') ?>"><span>Lost Boys</span></li>
          </ul>
        </div>
      </div>
      <div class="row row_text row_margin"> <a href="#" class="big_button">FInd a publisher in your area</a><a href="#" class="big_button">become a publisher</a> </div>
      <!--===== end Wall of fame ===--> 
      <!--===== start campaigns ===-->
      <hr>
      <div class="row row_text row_margin">
        <h4>Publish your campaigns</h4>
        <p>We do not only provide Facebook apps, you can easily<br>
          publish your campaigns as:</p>
        <div style="margin-top:35px;"> <img src="<?php echo $this->basePath('img/home_publisher.png') ?>"> </div>
        <div class="row" style="margin-top:40px;"> <a href="#" class="big_button">More about publishing</a> </div>
      </div>
      <!--===== end campaigns ===--> 