<?php
     $protocol = '';
        if (isset($_SERVER['HTTPS']) &&
       ($_SERVER['HTTPS'] == 'on' || $_SERVER['HTTPS'] == 1) ||
        isset($_SERVER['HTTP_X_FORWARDED_PROTO']) &&
        $_SERVER['HTTP_X_FORWARDED_PROTO'] == 'https') {
         $protocol = 'https://';
        }
        else {
        $protocol = 'http://';
           }
       // echo $_SERVER['SERVER_PROTOCOL'].$_SERVER['HTTP_HOST'].$_SERVER['REQUEST_URI'];
        $url = $protocol.$_SERVER["SERVER_NAME"];

?>

<script>
function subscribeReal() 
{
    var base_url = window.location.origin; 
    var email = $("#email").val();
    var name = $("#name").val();
    var phn = $("#phn").val();
    var regexemail = /^((([a-z]|\d|[!#\$%&'\*\+\-\/=\?\^_`{\|}~]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])+(\.([a-z]|\d|[!#\$%&'\*\+\-\/=\?\^_`{\|}~]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])+)*)|((\x22)((((\x20|\x09)*(\x0d\x0a))?(\x20|\x09)+)?(([\x01-\x08\x0b\x0c\x0e-\x1f\x7f]|\x21|[\x23-\x5b]|[\x5d-\x7e]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(\\([\x01-\x09\x0b\x0c\x0d-\x7f]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF]))))*(((\x20|\x09)*(\x0d\x0a))?(\x20|\x09)+)?(\x22)))@((([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])*([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])))\.)+(([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])*([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])))\.?$/;
    
    if($('#name').val()==''){
        
    	
       $("#log-alert1").html("* please put your name").show().delay(3000).fadeOut();
       return false;
    
    
    }
    else if($('#phn').val()==''){

    	
    	   $("#log-alert2").html("* please put your phone no").show().delay(3000).fadeOut();
        return false;
     
    }
    else if($('#email').val()==''){
    	
    	  $("#log-alert3").html("* please provide valid Email id").show().delay(3000).fadeOut();
     
        return false;
    }
    else if (!email.match(regexemail)) 
    {  
           $("#log-alert3").html("Please put valid E-mail").show().delay(3000).fadeOut();
           return false;
   } 
       
    else{
       $.ajax({
    type : 'POST',
    url : '/index/sendrequest',
    data : {email:email,phn:phn,name:name},
    success : function(data)
    { 
    	$('#email').val('');
    	$('#name').val('');
    	$('#phn').val('');
    alert(data);
    
    setTimeout(function(){
    	 window.location.href= base_url+"/index/index";
       }, 2000);
   
 
    }
  });  
    }
    
}

$(document).ready(function () {
	  //called when key is pressed in textbox
	  $("#phn").keypress(function (e) {
	     //if the letter is not digit then display error and don't type anything
	     if (e.which != 8 && e.which != 0 && (e.which < 48 || e.which > 57)) {
	        //display error message
	        //$("#log-alert1").html("Digits Only").show().fadeOut("slow");
	               return false;
	    }
	   });
	});



</script>
<style>
#log-alert1{
  color: red;
  font-size: 12px;
}
#log-alert2 {
  color: red;
  font-size: 12px;
}
#log-alert3 {
  color: red;
  font-size: 12px;
}
a#here{
    color:blue;
    
}

</style>



<div  class="site">
  <div class="container-fluid"> 

    

     <div class="row">
           <div class="banner_contact">
        <ul class="social_icon">
          <li><a href="#">Share this website</a></li>
          <li><a href="javascript:void(0)" onclick="return fbs_click()"></a> <a style="cursor:pointer" onclick="return twt_click()"></a> <a style="cursor:pointer" onclick="return linkedinButton()"></a></li>
        </ul> <!--=== social icon ===-->
        <div class="cont-title sfp-accnt">
        <h1>Publish great campaigns.</h1>
        </div>
      </div>
      
    </div><!--===== end banner ===--> 
     <div class="col-lg-12">
     <div class="create-ur-sfp-account-form col-lg-8 col-lg-offset-2">
     <h4>Subscribe for beta testing</h4>
     <div class="create-ur-sfp-account-form">
     <ul>
     <li>
     <label for="">Name<span>*</span></label>
     <input type="text" id="name" name="name"><p id="log-alert1" style="display:none">   </p> 
     </li>
       <li>
     <label for="">Phone No <span>*</span></label>
     <input type="text" id="phn" name="phn" /><p id="log-alert2" style="display:none">   </p> 
     </li>
     <li>
     <label for="">Email address <span>*</span></label>
     <input type="text" id="email" name="email"><p id="log-alert3" style="display:none">   </p> 
     </li>
       
   <li>
 
   <label>&nbsp;</label>
   <a class="continue" onclick="subscribeReal()" href="javascript:void(0)">Subscribe</a></li>
   
   <li><label>&nbsp;</label>
   </li>
 
     </ul>
      
      
    
     </div>
     
     
    
     </div>
    
     </div>
     
     </div>
  
<style type="text/css">
.banner_contact
{
 background: url(../img/store_banner-modified.jpg) no-repeat top center;
    display: block;
    height: 330px;
    margin: auto;
    overflow: hidden;
    width: 100%;
    background-size:cover ;

}
.continue {
  background: none repeat scroll 0 0 #252b34;
  border: medium none;
  color: #fff;
  display: block;
  float: left;
  font-family: "ubuntubold";
  font-size: 16px;
  height: 52px;
  line-height: 52px;
  margin: 0;
  text-align: center;
  text-transform: uppercase;
  width: 50%;
}

 .alert-info {
    width: 220px;
    padding: 10px;
    border: 5px solid gray;
    text-align: center;
    display: block;
    margin: 0 auto;
    background-color: ghostwhite;
    color: red;    
     
}

.create-ur-sfp-account-form > h4 {
  margin: 53px 0;
  text-align: center;
  width: 87%;
}
.create-ur-sfp-account-form ul li {
  height: auto;
  list-style: outside none none;
  margin-bottom: 7px;
  overflow: hidden;
}
.create-ur-sfp-account-form ul li label {
  color: #2e3641;
  display: block;
  float: left;
  font-size: 13px;
  height: 50px;
  line-height: 50px;
  width: 144px;
}
.create-ur-sfp-account-form ul li input[type="text"], .create-ur-sfp-account-form ul li input[type="password"] {
  border: 1px solid #ccc;
  height: 50px;
  text-indent: 5px;
  width:50%;
}
.create-ur-sfp-account-form > ul {
  padding: 0;
}
.sfp-accnt h1 {font-size: 33px; padding: 0 11% 0 0;text-align: right;}
.has-js .label_check {
	background: url(../image_gallery/check-off.jpg) no-repeat left top;
	height: 32px;
	padding: 0 0 0 44px;
	line-height: 32px;
}
.has-js .label_check input, .has-js .label_radio input{
	position: absolute;
	left: -9999px;
}
.has-js label.c_on {
	background: url(../image_gallery/check-on.jpg) no-repeat;
}

.create-ur-sfp-account-form ul li span a {
  color: #a9c5bc;
  display: block;
  float: left;
  margin-top: 4px;
}
.create-ur-sfp-account-form ul li div img {
  display: block;
  float: left;
  margin-left: 7px;
  vertical-align: bottom;
}
.create-ur-sfp-account-form ul li div p {
  float: left;
}

.create-ur-sfp-account-form ul li span fieldset > label {
  margin-right: 8px;
  width: auto;
}
.prefer-to-login a img {
  margin: 0 0 2px;
  width: 55px;
}
.prefer-to-login > a {
  margin-left: 5px;
}
.prefer-to-login {
  float: left;
  font-size: 12px;
  text-align: center;
}
</style>




