
<style>
.creat-acc-section form .info label {
  color: #2e3641;
  float: left;
  font-size: 13px;
  font-weight: normal;
  height: 29px;
  width: 166px;
}
.has-js label.r_off, .has-js label.r_on {
  line-height: normal;
  padding-left: 37px;
  width: auto !important;
}
.has-js .label_radio {
  background: url("../img/radio-off.png") no-repeat scroll left center rgba(0, 0, 0, 0);
  line-height: normal !important;
}
.creat-acc-section form .info span > label.r_off, .creat-acc-section form .info span > label.r_on {
  margin-right: 24px;
  width: auto;
}
.creat-acc-section form .info span {
  display: block;
  float: left;
  height: auto;
  overflow: hidden;
}
span.sfp-fb label {
    display: block;
    margin: 0 0 0 100px;
}
span.sfp-fb label {
    display: block;
    width: 100% !important;
}

span.sfp-fb2 label {
    display: block;
    margin: 0 0 0 100px;
}
span.sfp-fb2 label {
    display: block;
    width: 100% !important;
}
.creat-acc-section form .info span label > p {
  line-height: normal;
  margin: 0 29px;
  padding: 5px 0 0;
}
.selectBox-dropdown {margin:0;width: 406px !important;}

.selectBox-dropdown .selectBox-arrow { right: 8px;top: 20px; height: 12px !important;}
.selectBox-dropdown .selectBox-label {width: 353px !important;}


span.information {
	background:#E3F2F7 url(../img/information_icon.png) no-repeat 10px 10px;
	border-color:#B4DBE8;
	margin:0 0 10px 0;
	padding:10px 10px 10px 36px;
	color:#444444;
	display:block;
	-webkit-border-radius: 5px;
	-moz-border-radius: 5px;
	border-radius: 5px;
	font-family:Arial, Helvetica, sans-serif;
	font-size: 12px;
}
</style>
<!----------- added by Poulami ----------->


 <style>
body {
 /*color:#fff;*/font-family: 'ubunturegular';
 background:url(/sfpdeveloper/img/nav-bg.jpg) left top repeat-y;
}
#developer-main-container {
	height:auto;
	width:100%;
    position: relative;
}
.developer-menu-left-pannel {
	width:/*218px18%*/ 243px;
	padding:12px 0;
	background:#2e3641;
	position:relative;
	float:left
}
.logo img {
	display:block;
	margin:0 auto
}
h5.dev-title {
	font-family: 'Economica', sans-serif;
	text-align:center;
	font-size:21px;
	margin:22px 0;
	color: #fff;
}
.copyright-menu li {
	display:block;
	font-size:12px;
	font-family: 'ubunturegular';
	margin-bottom:5px;
}
.copyright-menu li:last-child {
	color:#7c7f83;
	margin-top:12px
}
.copyright-menu ul li a span {
	display: block;
	float: left;
	margin: 3px 6px 0 0;
}
.copyright-menu {
	bottom: 19px;
	position: absolute;
    left: 12px;
}
.main-menu li {
	height:auto;
	overflow:hidden;
	display:block;
	font-size:12px;
}
.main-menu li > a {
	height:42px;
	line-height:42px;
	border-bottom:1px solid #39404b;
	display:block;
	text-transform: uppercase;
	padding-left: 12px;
    color: #fff;
}

.main-menu {
	margin-top: 48px;
}
.main-menu li a:hover {
	color:#a9c5bc
}
.main-menu li a:hover:after {
	content:">";
	float:right;
	margin-right:12px;
	font-size:15px
}
.new-left-pannel {
	padding:12px 0
}
.development-center-wrapper {
	padding:12px;
}
.developer-menu-right-pannel {
  float: left;
  width: 80%;
}
.site {
  padding-left: 0;
}
.creat-acc-section .personal-data-form {
  margin: 50px auto;
  overflow: hidden;
  width: 67%;
}
.home_publisher_tab {
  margin: 40px auto !important;
  overflow: hidden;
  position: static;
  text-align: center;
  width: 74%;
  padding: 0;
}
.main-menu > ul, .copyright-menu > ul {
  padding: 0;
}
.copyright-menu a {
  color: #fff;
}
a.logo{ float: none;}

.log-out-person {
  height: auto;
  float: left;
  padding-left: 8px;
}
.log-out-person strong {
  color: #fff;
  display: block;
  font-family: "ubuntubold";
  font-size: 12px;
}
.log-out-person p {
  color: #7e7e7e;
  float: left;
  font-size: 12px;
}
.go_to_up {
  
    color: #2e3641;
    display: block;
    font-family: "ubuntubold";
    font-size: 12px;
    height: 21px;
    left: 49.7%;
    margin-left: -47px;
    padding-top: 24px;
    position: absolute;
    text-align: center;
    top: -9px;
    width: 95px;
}
.copyright-menu img {
  margin-top: -6px;
}
.log-out-bt {
  display: block;
  float: left;
  height: auto;
  overflow: hidden;
}
.main-menu li:first-child {
  border-top:1px solid #39404b;
}
.selectBox-dropdown{ float: left;}
    </style>

  <div id="developer-main-container" class="clearfix">
     <?php
    $protocol = '';
        if (isset($_SERVER['HTTPS']) &&
       ($_SERVER['HTTPS'] == 'on' || $_SERVER['HTTPS'] == 1) ||
        isset($_SERVER['HTTP_X_FORWARDED_PROTO']) &&
        $_SERVER['HTTP_X_FORWARDED_PROTO'] == 'https') {
         $protocol = 'https://';
        }
        else {
        $protocol = 'http://';
           }
       // echo $_SERVER['SERVER_PROTOCOL'].$_SERVER['HTTP_HOST'].$_SERVER['REQUEST_URI'];
        $url = $protocol.$_SERVER["SERVER_NAME"];
?>   
        
        <div class="developer-menu-left-pannel clearfix new-left-pannel">
        
        <div class="development-center-wrapper clearfix">
        
        <a href="#" class="logo"><figure><img src="<?php echo $this->basePath('sfpdeveloper/img/dev_logo.png') ?>" alt=""></figure></a>
        <h5 class="dev-title"> -  Development centre  - </h5>
        
        <div class="log-out-container clearfix">
        <a class="log-out-bt" href="<?php echo $url;?>/sfpdeveloper/devlogout"><span><img src="<?php echo $url;?>/sfpdeveloper/img/ft-img-2.jpg"/></span></a>
        <div class="log-out-person">
          <strong><?php echo $result->fName." ".$result->lName; ?></strong>
        <p><?php echo $result->ccity; ?></p>
        </div>
        </div>
        
        </div>
        <div class="main-menu2 clearfix">
        <ul>
        	<li><a href="<?php echo $this->url('application/default',array('controller'=>'sfpdeveloper','action' =>'dashboard','id'=>$id."|".$encryptedId,));?>">Dashboard </a> </li>
        	<!---<li><a href="<?php echo $this->url('application/default',array('controller'=>'Frontend','action' =>'index'));?>">My campaigns</a></li>
        	<li><a href="<?php echo $this->url('application/default',array('controller'=>'Template','action' =>'#'));?>">Upload wizard</a></li>
        	<li><a href="#">My account</a></li>--->
        	<li><a  target="_blank" href="<?php echo $url;?>/index/documentation#tab-1">Documentation</a></li>
        </ul>
        </div>
        
        
        
        </div>
        <div class="copyright-menu clearfix">
        <ul>
        	<li><a href="#"><span><img src="<?php echo $url;?>/sfpdeveloper/img/ft-img.jpg"/></span> Terms & service </a></li>
        	<li><a href="#"> <span><img src="<?php echo $url;?>/sfpdeveloper/img/ft-img.jpg"/></span> Disclaimer </a></li>
        	<li><a href="#"><span><img src="<?php echo $url;?>/sfpdeveloper/img/ft-img.jpg"/></span> Privacy policy </a></li>
        	<li> Copyright 2015 Smart Fanpage</li>
        </ul>
        </div>
        <div class="developer-menu-right-pannel clearfix">
        <div class="developer-menu-right-pannel-image-holder clearfix">
      
   
<div class="container-fluid"> 
    <!--===== start banner ===-->
     <!--===== start banner ===-->
    <div class="row">
      <div class="banner wizard">
      	
      </div>
      
    </div>     

       

<!--===== end banner ===--> <!--===== end banner ===--> 
    


<!--===================================tab html start=================================-->
<div class="wizard-cont row col-lg-12">

<div class="horizontalTab1" >
  <ul class="resp-tabs-list home_publisher_tab">
  <li class="upload r-tabs-state-active"><a>1) Upload archive file</a></li>
   <li class="setup"><a>2) Set up pages</a></li>
   <li class="valid"><a>3) Validation</a></li>

  </ul>
  <?php if($error == 'null') echo "<p>Please log in to continue</p>";?>
  <hr style="margin-top:45px; width: 73%; margin: 0 auto;;"/>

<!--<a href="<?php echo $this->url('application/default',array('controller'=>'developer','action'=>'dashboard'));?>">DASHBOARD</a><br />-->

  <div id="tab-1" class="creat-acc-section">
  <h1 class="heading">Step 1 - Upload archive file</h1>
    <?php 
$uform = $this->uform;
$uform->setAttribute('action', $this->url('application/default', array('controller'=>'template','action' => 'addtemplate')));
$uform->prepare();
echo $this->form()->openTag($uform);
?>
    <div class="personal-data-form">
    
    <?php 
    if($error == 1)
    {
        //echo "Template with same name exists.Sorry to upload!!";
        echo "<span class='information'>Template with same name exists.Sorry to upload!!</span>";
    }
    else if($error == 2)
    {
        echo "<span class='information'>Please upload zip file only</span>";
    }
    else if($error == 3)
    {
        echo "<span class='information'>Index file is missing.Sorry to upload!!</span>";
    }
    else if($error == 4)
    {
        echo "<span class='information'>UPLOAD .jpg or .jpeg or .png format screenshot image.Sorry to upload!!</span>";
    }
    else if($error == 5)
    {
        echo "<span class='information'>Please fill in correct appId.Sorry to upload!!</span>";
    }
    else if($error == 6)
    {
        echo "<span class='information'>Database file is missing.Sorry to upload!!</span>";
    }
    else if($error == 44)
    {
    	echo "<span class='information'>UPLOAD .jpg or .jpeg or .png format</span>";
    }
    else if($error == 45)
    {
    	echo "<span class='information'>UPLOAD .jpg or .jpeg or .png format</span>";
    }
    ?>
    
    
    
    
     <div class="info company-profile-info">
        <label>Name your campaign</label>
        <span class="first-name"><?php echo $this->formRow($uform->get('templateName'));?></span><div id="name">
</div>
</div>        
        
      <div class="info company-profile-info">
        <label>Campaign description</label>
        <span class="first-name company-profile"><?php echo $this->formRow($uform->get('templateDesc'));?></span></div>
        
        <div class="info company-profile-info">
        <label>Your template price (&#8364;)</label>
        <div class="currency_section">
        
            <span class="first-name company-profile"><?php echo $this->formRow($uform->get('templatePrice'));?></span>
           <!-- <span class="price_euro">&#8364;</span>-->
        
        </div>
        
        
        
        
        
        </div>
        
        <div class="info company-profile-info">
        <label>One year subscription (&#8364;)</label>
        <div class="currency_section">
        
            <span class="first-name company-profile"><?php echo $this->formRow($uform->get('oneTimePrice'));?></span>
           <!-- <span class="price_euro">&#8364;</span>-->
        
        </div>
        </div>
      <div class="info company-profile-info">
        <label>Your template archive</label>
        <a class="first-name"><span id="button"><?php echo $this->formElement($uform->get('file')); ?></span></a><div id="zip">
</div></div>
        
        
        <div class="info company-profile-info">
        <label>Your template screenshot</label>
        <a class="first-name"><span id="button"> <?php echo $this->formElement($uform->get('scImage')); ?></span><p class="word-limitation">Exact 200 x 200 pixels (max. filesize 500 kb)</p></a><div id="image">
</div></div>
        
        <div class="info company-profile-info">
        <label>Desktop view</label>
        <a class="first-name"><span id="button"> <?php echo $this->formElement($uform->get('desktopImage')); ?></span><p class="word-limitation">Minumum 1200 x 600 pixels </p></a><div id="image">
</div></div>
        
        <div class="info company-profile-info">
        <label>Mobile view</label>
        <a class="first-name"><span id="button"> <?php echo $this->formElement($uform->get('mobileImage')); ?></span><p class="word-limitation">Mnimum 320 x 480 pixels </p></a><div id="image">
</div></div>
        
        
        
      <!-- <div class="col-md-9 col-xs-12" >
          <select id="standard-dropdown" name="standard-dropdown" class="custom-class1 custom-class2">
            <option value="1" class="test-class-1">Keyword</option>
            <option value="1" class="test-class-1">dfgsdfgsdgfd</option>
            <option value="1" class="test-class-1">Select category</option>
          </select>
        </div>-->
         
         <div class="info company-profile-info">
        <label>Add Your Widgets</label>
        <span class="first-name"><?php echo $this->formRow($uform->get('widget'));?></span>
        
        
        <dl class="mdropdown"> 
  
        <dt>
        <a>
          <span class="hida">Select</span>    
          <p class="multiSel"></p>  
        </a>
        </dt>
      
        <dd>
            <div class="mutliSelect">
                <ul>
                    <li>
                        <input type="checkbox" value="map" />MAP</li>
                    <li>
                        <input type="checkbox" value="cForm" />CONTACT FORM</li>
                    <!--<li>
                        <input type="checkbox" value="nLtr" />NEWSLETTER</li>-->
                </ul>
            </div>
        </dd>
    </dl>
        
        
        </div> 
         
  <div class="info company-profile-info">
          <label>Select Template Category</label>
          <select id="standard-dropdown2" name="template_select" class="custom-class1 custom-class2">
            <option value="0" >Select Template</option>
            <?php foreach ($temp as $tempCatagory){?>
            <option value="<?php echo $tempCatagory->catagory?>" ><?php echo $tempCatagory->catagory?></option>
            
            <?php }?>
          </select>
        </div>
      
      
      <div class="info company-profile-info">
            <span>
              <p>&nbsp;</p>
                <label class="label_check" for="checkbox-01"><input name="sample-checkbox-01" id="checkbox-01" value="1" type="checkbox" style="display: none;"/><p> Want a database connection? </p></label>
            </span>
        </div>
      
        <div class="info company-profile-info">
           
              <span>
              <label class="label_check" for="checkbox-02"><input name="sample-checkbox-02" id="checkbox-02" value="2" type="checkbox" style="display: none;"/><p> Want a facebook connection? </p></label>
              </span>
        </div>
        
        
   
           
              <div class="info company-profile-info"> 
             
              
                <span class="sfp-fb" id="sfp" style="display: none;">
                
                <div class="multicheckbox">
                <label class="label_check" for="checkbox-03"><input name="sample" id="checkbox-03" value="1" type="checkbox" style="display: none;"/><p>Use the connect setting of Smartfanpage</p>
                </div>
                
                </span>
             
            </div>
            
            
       
         
         <div class="info company-profile-info">
           
              
             
              
                <span class="sfp-fb2" id="sfp" style="display: none;">
                
                <div class="multicheckbox">
                <label class="label_check" for="checkbox-04"><input style="display: none;" name="sample1" id="checkbox-04" value="email" type="checkbox"  /><p>Email Address</p></label> 
                <label class="label_check" for="checkbox-05"><input style="display: none;" name="sample2" id="checkbox-05" value="public_action" type="checkbox"  /><p>Description about user</p></label>  
                </div>
                
                </span>
             
            
         </div>
        
        
        
       <!-- <div class="info company-profile-info custom-temppp">
            <label>View for your template </label>
            <span>
               <label class="label_radio"><input id="radio-01" value="0" type="radio" /> DESKTOP </label>
                <label class="label_radio"><input id="radio-02" value="0" type="radio" /> MOBILE </label>
                <label class="label_radio"><input id="radio-03" value="0" type="radio" /> RESPONSIVE </label>
            </span>
        </div>
        
      
      <div class="info company-profile-info">
        <label>Supported platforms</label>
        
        
        <ul class="blog_social">
            <li><a href="https://www.facebook.com/" target="_blank" title="Facebook">facebook</a></li>
            <li><a href="http://www.twitter.com/" target="_blank" title="Twitter">twitter</a></li>
            <li><a href="https://www.linkedin.com/" target="_blank" title="Linkedin">linkedin</a></li>
            <li><a href="http://instagram.com/" target="_blank" title="Instagram">instagram</a></li>
            <li><a href="https://www.pinterest.com/" target="_blank" title="Pinterest">pinterest</a></li>
        </ul>
        
        </div>-->
        
        
      
      

    
    </div>
  
    <input type="button" name="button" value="Send data" class ="save_btn" id="clck" onClick="return submitFunction();" />
    <?php echo $this->formElement($uform->get('submit'));?>
    <?php echo $this->form()->closeTag() ?>
    
  </div>

  


</div> 


<div style="position:relative;"><hr> <a id="back-to-top" class="go_to_up" href="#">Back to top</a></div>


 </div> 

  

<!--===================================tab html end=================================-->





 
    </div>
    
    <script type="text/javascript">
    
    
    /*added by dibyendu*/
    function priceFunction(evt) 
{
    
         
            var charCode = (evt.which) ? evt.which : event.keyCode;
            //alert(charCode);return false;
            if ((charCode >= 48 && charCode <= 57 ) || (charCode >= 96 && charCode <= 105 ) || charCode ==8 || charCode ==9)
            {
            return true;
            }
            
            else{
            return false;
            }
           
}
    
    function oneTimePriceFunction(evt) 
    {
        
             
                var charCode = (evt.which) ? evt.which : event.keyCode;
                //alert(charCode);return false;
                if ((charCode >= 48 && charCode <= 57 ) || (charCode >= 96 && charCode <= 105 ) || charCode ==8 || charCode ==9)
                {
                return true;
                }
                
                else{
                return false;
                }
               
    }
           
    
 /*added by Anima */ 
 
 
 
function submitFunction()
{
     var name=$("#templateName").val();
     var message=$("#templateDesc").val();
     var price=$("#templatePrice").val();
     var oneTimePrice=$("#oneTimePrice").val();
     var Image=$("#file").val();
     var desktopImage=$("#desktopImage").val();
     var mobileImage=$("#mobileImage").val();
     var Image1=$("#file2").val();
      var euro=$("#euro").val();
     var dollar=$("#dollar").val();
    //if(euro==0&&dollar==0)
//    {
//    alert("please check your price");
//    }
//    if(euro==1)
//    {
//        alert("euro");
//    }
//     if(dollar==1)
//    {
//        alert("dollar");
//    }
//        
//     
//       
//      return false;
    //alert(euro);return false;
    //dolar=$('input[name=dolar]:checked').val();

 //  if(euro == undefined )
//   {
//    alert ("please select one currency");
//    return false;
//    }
//    if(euro == 1)
//    {
//    alert ("euro mama");
//    return false;  
//    }
//     if(euro == 0)
//    {
//      alert ("dolar mama");
//    return false;  
//    }
//    alert(name);
//   alert(Image);
//   alert(message);
// alert(currency);
//  exit;
    
      if (name==null || name=="")
        {    
        alert("Please name your campaign");
        document.getElementById('name').focus();
        
        return false;
        }   
   else if (message==null || message=="")
        {    
        alert("Please put your campaign description");
        document.getElementById('message').focus();
        
        return false;
        }
    
      else if (price==null || price=="")
        {    
        alert("Please set your campaign price to proceed");
        document.getElementById('price').focus();
        
        return false;
        }  
      else if (oneTimePrice==null || oneTimePrice=="")
      {    
      alert("Please set the price for one year premium subscription");
      document.getElementById('oneTimePrice').focus();
      
      return false;
      }  
    
      else if (desktopImage==null || desktopImage=="")
          {    
          alert("Please put your desktop view of template");
          document.getElementById('Image').focus();
          
          return false;
          }
      
      else if (mobileImage==null || mobileImage=="")
          {    
          alert("Please put your mobile view of templatee");
          document.getElementById('Image').focus();
          
          return false;
          }
              
    else if (Image==null || Image=="")
        {    
        alert("Please upload your template archive");
        document.getElementById('Image').focus();
        
        return false;
        }
     else if (Image1==null || Image1=="")
        {    
        alert("Please put your template screenshot");
        document.getElementById('Image1').focus();
        
        return false;
        }
        else
        {
          $('#submit').trigger('click');
          $('#submit').show();
          $('#clck').hide();
          
        }
      

}


</script>
